[#sect-sync-warp-lightclient]
= Warp Sync for Light Clients

Warp sync (<<sect-msg-warp-sync>>) only downloads the block headers where
authority set changes occurred, so-called fragments (<<defn-warp-sync-proof>>),
and by verifying the GRANDPA justifications (<<defn-grandpa-justification>>).
This protocol allows nodes to arrive at the desired state much faster than fast
sync. Warp sync is primarily designed for Light Clients. Although, warp sync could be used by full nodes, the sync process mahy lack information to cater to complete functionality set of full nodes. 

For light clients, it is too expensive to download the state (approx. 550MB) to respond to queries. Rather, the queries are submitted to the Full node and only the response of the full node is validated using the hash of the state root.   Requests for warp sync are performed using the `/dot/sync/warp` _Request-Response_ substream, the corresponding network messages are detailed in <<sect-protocols-substreams>>. 

Light clients base their trust in provided snapshots and the ability to slash grandpa votes for equivocation for the period they are syncing via warp sync. Full nodes and above in contrast verify each block indvidually.

In theory, the `warp sync` process takes the Genesis Block as input and outputs the hash of the state trie root at the latest finalized block. This root hash acts as proof to further validate the responses to queries by the full node. The `warp sync` works by starting from a trusted specified block (for e.g. from a snapshot) and verifying the block headers only at the authority set changes. 

Eventually, the light client verifies the finality of the block returned by a full node to ensure that the block is indeed the latest finalized block. This entails two things: 
    . check the authenticity of GRANDPA Justifications messages from Genesis to the last finalized block, 
    . Check the timestamp of the last finalized block to ensure that no other blocks might have been finalized at a later timestamp. 

WARNING: *Long-Range Attack Vulnerabilities*: Warp syncing is particularly vulnerable to what is called long-range attacks. The authorities allowed to finalize blocks can generate multiple proofs of finality for
multiple different blocks of the same height, hence, they can finalize more than one chain at a time.
It is possible for two-thirds of the validators that were active at a certain
past block N to collude and decide to finalize a different block N', even when N has been
finalized for the first time several weeks or months in the past. When a client then warp syncs, it can be tricked to consider this alternative block N' as the finalized one. However, in practice, to mitigate Long-Range Attacks, the starting point of the warp syncing is not too far in the past. How far exactly depends on the logic of the runtime of the chain. For example, in Polkadot, the starting block for the sync should be at max 28 days old, to be within the purview of the slashing period for misbehaving nodes. Hence, even though in theory warp sync can start from Genesis Block, it is not advised to implement the same in practice.   

We outline the warp sync process, abstracting out details of verifying the finality and how the full node to sync with is selected.

****
.Querying-State-Light-Clients
[pseudocode#warp-sync]
++++
\INPUT BlockHeader startblock, the initial block to start the sync. May not be the Genesis Block. 
\OUTPUT CommitmentRootHash $root$, State Tries Root hash of the latest finalized Block. 

\STATE \textsc{fullnode} $\leftarrow$ SelectFullNode  
\STATE \textsc{latestBlockHeader, grandpaJustifications} $\leftarrow$ SyncWithNode(\textsc{fullnode})
\STATE \textsc{isVerified} $\leftarrow$ verifyAuthoritySetChange(\textsc{grandpaJustifications}) $\land$ verifyFinality(\textsc{latestBlockHeader})

\IF{\textsc{isVerified}}
    \STATE $return$ $SOME$ getCommitmentRootHash(\textsc{latestBlockHeader})
\ENDIF
\STATE {$throw$ $ERROR$}

++++
Abstraction of Warp Sync and verification of latest block's finality. 
SelectFullNode: determines the full node that the light client syncs with. 
SyncSithNode: Returns the header of latest finalized block and a list of Grandpa Justifications by the full node.
verifyAuthoritySetChange: verification algorithm which checks the authenticity of the header only at the end of an era where the authority set changes iteratively until reaching the latest era.
verifyFinalty: verifies the finalty of the latest block using the Grandpa Jusitfication messages.
****


The warp syncing process is closely coupled with the state querying procedure used the light client. We outline the process of querying the state by a light client and validating the response.  
****
.Querying-State-Light-Clients
[pseudocode#algo-light-clients-query-state]
++++
\INPUT Query q, BlockHeight h, CommitmentRootHash $root$
\OUTPUT Maybe Result $res$

\STATE ($res$, $\pi$) $\leftarrow QueryFullNode (q, h)$

\IF{$validityCheck_{root}(res, \pi)$}
    \STATE $return$ $SOME$ $res$
\ENDIF
\STATE {$throw$ $ERROR$}

++++

Querying State Algorithm. 
latexmath:[QueryFullNode]: returns the response to the query requested from the Full Node for the query latexmath:[q] at block height latexmath:[h]. 
latexmath:[validityCheck_{root}]: predicate that checks the validity of response latexmath:[res] and associated merkle proof latexmath:[\pi] by matching it against the Commit Root Hash latexmath:[root] obtained as a result of warp sync.  

****