[#chap-overview]
= Overview
The Polkadot Protocol differentiates between different classes of Polkadot Hosts. Each class differs in their trust roots and how active or passively they interact with the network.

[#sect-client-light]
== Light Client

The light client is a mostly passive participant in the protocol. Light clients are designed to work in resource constrained environments like browsers, mobile devices or even on-chain. Its main objective is to follow the chain, make queries to the full node on specific information on recent state of the blockchain, and to add extrinsics (transactions). It does not maintain the full state, rather queries the full node on the latest finalised state and verifies the authenticity of the responses trustlessly. Details of specifications for Light Clients 

[#sect-node-full]
== Full Node

While the full node is still a mostly passive participant of the protocol, they follow the chain by receiving and verifying every block in the chain. It maintains full state of the blockchain by executing the extrinsics in blocks. They role in consesus mechanism is limited to following the chain and not producing the next blocks.
// Do we change the 

* *Functional Requirements:* 
 
. The node must populate the state storage with the official genesis state,
elaborated further in <<chapter-genesis>>.
. The node should maintain a set of around 50 active peers at any time. New
peers can be found using the discovery protocols (<<sect-discovery-mechanism>>)
. The node should open and maintain the various required streams
(<<sect-protocols-substreams>>) with each of its active peers.
. Furthermore, the node should send block requests (<<sect-msg-block-request>>)
to these peers to receive all blocks in the chain and execute each of them.
. The node should exchange neighbor packets (<<sect-grandpa-neighbor-msg>>).

[#sect-node-authoring]
== Authoring Node

The authoring node covers all the features of the full node but instead of just passivly following the protocol, it is an active participant, producing blocks and voting in Grandpa.

* *Functional Requirements:* 

. Verify that the Host’s session key is included in the current Epoch’s
authority set (<<sect-authority-set>>).
. Run the BABE lottery (<<sect-block-production>>) and wait for the next
assigned slot in order to produce a block.
. Gossip any produced blocks to all connected peers
(<<sect-msg-block-announce>>).
. Run the catch-up protocol (<<sect-grandpa-catchup>>) to make sure that the
node is participating in the current round and not a past round.
. Run the GRANDPA rounds protocol (<<sect-finality>>).

[#sect-node-relaying]
== Relaying Node

The relaying node covers all the features of the authoring node, but also participants in the availability and validity process to process new parachain blocks as described in <<chapter-anv>>.
