=== General Information

The Polkadot Host assumes that at least the constants and functions
described in this Chapter are implemented in the Runtime Wasm blob.

It should be noted that the API can change through the Runtime updates.
Therefore, a host should check the API versions of each module returned
in the `api` field by `Core_version` (<<defn-rt-core-version>>) after
every Runtime upgrade and warn if an updated API is encountered and that
this might require an update of the host.

[#sect-json-rpc-api]
==== JSON-RPC API for external services

Polkadot Host implementers are encouraged to implement an API in order
for external, third-party services to interact with the node. The
https://github.com/w3f/PSPs/blob/master/PSPs/drafts/psp-6.md[JSON-RPC
Interface for Polkadot Nodes] (PSP6) is a Polkadot Standard
Proposal for such an API and makes it easier to integrate the node with
existing tools available in the Polkadot ecosystem, such as
https://polkadot.js.org/[polkadot.js.org]. The Runtime API has a few
modules designed specifically for use in the official RPC API.
