+++
title = "Bridge Design"
date = "2019-02-28"
menu = "main"
weight = "5"
+++

[#sect-grandpa-beefy]
=== Bridge design (BEEFY)

WARNING: The BEEFY protocol is currently in early development and subject to
change. The specification has not been completed yet.

The BEEFY (Bridge Effiency Enabling Finality Yielder) is a secondary protocol to
GRANDPA to support efficient bridging between the Polkadot network (relay chain)
and remote, segregated blockchains, such as Ethereum, which were not built with
the Polkadot interchain operability in mind. The protocol allows participants of
the remote network to verify finality proofs created by the Polkadot relay chain
validators. In other words: clients in the Ethereum network should able to
verify that the Polkadot network is at a specific state.

Storing all the information necessary to verify the state of the remote chain,
such as the block headers, is too expensive. BEEFY stores the information in a
space-efficient way and clients can request additional information over the
protocol.

==== Preliminaries

[#defn-mmr]
===== Merkle Mountain Ranges
****
Merkle Mountain Ranges, *MMR*, are used
as an efficient way to send block headers and signatures to light clients.

NOTE: MMRs have not been defined yet.
****

[#defn-beefy-statement]
===== Statement
****
The *statement* is the same piece of information which every relay chain
validator is voting on. Namely, the MMR root of all the block header hashes
leading up to the latest, finalized block.
****

[#defn-beefy-witness-data]
===== Witness Data
****
*Witness data* contains the statement (<<defn-beefy-statement>>), an array
indicating which validator of the Polkadot network voted for the statement (but
not the signatures themselves) and a MMR root of the signatures. The indicators
of which validator voted for the statement are just claims and provide no
proofs. The network message is defined in
<<defn-grandpa-beefy-signed-commitment-witness>> and the relayer saves it on the
chain of the remote network.
****

[#defn-beefy-light-client]
===== Light Client
****
A *light client* is an abstract entity in a remote network such as Ethereum. It
can be a node or a smart contract with the intent of requesting finality proofs
from the Polkadot network. A light client reads the witness data
(<<defn-beefy-witness-data>> from the chain, then requests the signatures
directly from the relayer in order to verify those.

The light client is expected to know who the validators are and has
access to their public keys.
****

[#defn-beefy-relayer]
===== Relayer
****
A *relayer* (or "prover") is an abstract entity which takes finality proofs from
the Polkadot network and makes those available to the light clients. Inherently,
the relayer tries to convince the light clients that the finality proofs have
been voted for by the Polkadot relay chain validators. The relayer operates
offchain and can for example be a node or a collection of nodes.
****

==== Voting on Statements

The Polkadot Host signs a statement (<<defn-beefy-statement>>) and gossips it as
part of a vote (<<defn-msg-beefy-gossip>>) to its peers on every new, finalized
block. The Polkadot Host uses ECDSA for signing the statement, since Ethereum
has better compatibility for it compared to SR25519 or ED25519.

[#sect-beefy-committing-witnesses]
==== Committing Witnesses

The relayer (<<defn-beefy-relayer>>) participates in the Polkadot network by
collecting the gossiped votes (<<defn-msg-beefy-gossip>>). Those votes are
converted into the witness data structure (<<defn-beefy-witness-data>>).
The relayer saves the data on the chain of the remote network. The occurrence of
saving witnesses on remote networks is undefined.

==== Requesting Signed Commitments

A light client (<<defn-beefy-light-client>>) fetches the witness data
(<<defn-beefy-witness-data>>) from the chain. Once the light client knows which
validators apparently voted for the specified statement, it needs to request the
signatures from the relayer to verify whether the claims are actually true. This
is achieved by requesting signed commitments
(<<defn-grandpa-beefy-signed-commitment>>).

How those signed commitments are requested by the light client and delivered by
the relayer varies among networks or implementations. On Ethereum, for example,
the light client can request the signed commitments in form of a transaction,
which results in a response in form of a transaction.
