[#sect-child-storage-api]
=== Child Storage

Interface for accessing the child storage from within the runtime.

[#defn-child-storage-type]
.<<defn-child-storage-type, Child Storage>>
====
*Child storage* key is a unprefixed location of the child trie in the main trie.
====

==== `ext_default_child_storage_set`
Sets the value under a given key into the child storage.

===== Version 1 - Prototype
----
(func $ext_default_child_storage_set_version_1
	(param $child_storage_key i64) (param $key i64) (param $value i64))
----

Arguments::

* `child_storage_key` : a pointer-size (<<defn-runtime-pointer-size>>) to the
child storage key (<<defn-child-storage-type>>).
* `key`: a pointer-size (<<defn-runtime-pointer-size>>) to the key.
* `value`: a pointer-size (<<defn-runtime-pointer-size>>) to the value.

==== `ext_default_child_storage_get`
Retrieves the value associated with the given key from the child storage.

===== Version 1 - Prototype
----
(func $ext_default_child_storage_get_version_1
	(param $child_storage_key i64) (param $key i64) (result i64))
----

Arguments::

* `child_storage_key`: a pointer-size (<<defn-runtime-pointer-size>>) to the
child storage key (<<defn-child-storage-type>>).
* `key`: a pointer-size (<<defn-runtime-pointer-size>>) to the key. 
* `result`: a pointer-size (<<defn-runtime-pointer-size>>) to the SCALE
encoded _Option_ value (<<defn-option-type>>) containing the value.

==== `ext_default_child_storage_read`

Gets the given key from storage, placing the value into a buffer and returning
the number of bytes that the entry in storage has beyond the offset.

===== Version 1 - Prototype
----
(func $ext_default_child_storage_read_version_1
	(param $child_storage_key i64) (param $key i64) (param $value_out i64)
	(param $offset i32) (result i64))
----

Arguments::

* `child_storage_key`: a pointer-size (<<defn-runtime-pointer-size>>) to the
child storage key (<<defn-child-storage-type>>).
* `key`: a pointer-size (<<defn-runtime-pointer-size>>) to the key.
* `value_out`: a pointer-size (<<defn-runtime-pointer-size>>) to the buffer
to which the value will be written to. This function will never write more then
the length of the buffer, even if the value’s length is bigger.
* `offset`: an u32 integer (typed as i32 due to wasm types) containing the offset beyond the value should be read
from.
* `result`: a pointer-size (<<defn-runtime-pointer-size>>) to the SCALE
encoded _Option_ value (<<defn-option-type>>) containing the number of bytes
written into the *value_out* buffer. Returns if the entry does not exists.

==== `ext_default_child_storage_clear`

Clears the storage of the given key and its value from the child storage.
Nonexistent entries are silently ignored.

===== Version 1 - Prototype
----
(func $ext_default_child_storage_clear_version_1
	(param $child_storage_key i64) (param $key i64))
----

Arguments::

* `child_storage_key`: a pointer-size (<<defn-runtime-pointer-size>>) to the
child storage key (<<defn-child-storage-type>>).
* `key`: a pointer-size (<<defn-runtime-pointer-size>>) to the key.

==== `ext_default_child_storage_storage_kill`

Clears an entire child storage.

===== Version 1 - Prototype
----
(func $ext_default_child_storage_storage_kill_version_1
	(param $child_storage_key i64))
----

Arguments::

* `child_storage_key`: a pointer-size (<<defn-runtime-pointer-size>>) to the
child storage key (<<defn-child-storage-type>>).

===== Version 2 - Prototype

----
(func $ext_default_child_storage_storage_kill_version_2
	(param $child_storage_key i64) (param $limit i64)
	(return i32))
----

Arguments::

* `child_storage_key`: a pointer-size (<<defn-runtime-pointer-size>>) to the
child storage key (<<defn-child-storage-type>>).
* `limit`: a pointer-size (<<defn-runtime-pointer-size>>) to an _Option_ type
(<<defn-option-type>>) containing an unsigned 32-bit integer indicating the
limit on how many keys should be deleted. No limit is applied if this is _None_.
Any keys created during the current block execution do not count towards the
limit.
* `return`: a value equal to _1_ if all the keys of the child storage have been
deleted or a value equal to _0_ if there are remaining keys.

===== Version 3 - Prototype
----
(func $ext_default_child_storage_storage_kill_version_3
	(param $child_storage_key i64) (param $limit i64)
	(return i64))
----

Arguments::

* `child_storage_key`: a pointer-size (<<defn-runtime-pointer-size>>) to the
child storage key (<<defn-child-storage-type>>).
* `limit`: a pointer-size (<<defn-runtime-pointer-size>>) to an _Option_ type
(<<defn-option-type>>) containing an unsigned 32-bit integer indicating the
limit on how many keys should be deleted. No limit is applied if this is _None_.
Any keys created during the current block execution do not count towards the
limit.
* `return`: a pointer-size (<<defn-runtime-pointer-size>>) to the following variant, stem:[k]:
+
[stem]
++++
k = {(0,-> c),(1,-> c):}
++++
+
where _0_ indicates that all keys of the child storage have been removed,
followed by the number of removed keys, stem:[c]. The variant _1_ indicates that
there are remaining keys, followed by the number of removed keys.

==== `ext_default_child_storage_exists`

Checks whether the given key exists in the child storage.

===== Version 1 - Prototype
----
(func $ext_default_child_storage_exists_version_1
	(param $child_storage_key i64) (param $key i64) (return i32))
----

Arguments::

* `child_storage_key`: a pointer-size (<<defn-runtime-pointer-size>>) to the
child storage key (<<defn-child-storage-type>>).
* `key`: a pointer-size (<<defn-runtime-pointer-size>>) to the key.
* `return`: an i32 integer value equal to _1_ if the key exists or a value equal
to _0_ if otherwise.

==== `ext_default_child_storage_clear_prefix`

Clears the child storage of each key/value pair where the key starts with the
given prefix.

===== Version 1 - Prototype
----
(func $ext_default_child_storage_clear_prefix_version_1
	(param $child_storage_key i64) (param $prefix i64))
----

Arguments::

* `child_storage_key`: a pointer-size (<<defn-runtime-pointer-size>>) to the
child storage key (<<defn-child-storage-type>>).
* `prefix`: a pointer-size (<<defn-runtime-pointer-size>>) to the
prefix.

===== Version 2 - Prototype
----
(func $ext_default_child_storage_clear_prefix_version_2
	(param $child_storage_key i64) (param $prefix i64)
	(param $limit i64) (return i64))
----

Arguments::

* `child_storage_key`: a pointer-size (<<defn-runtime-pointer-size>>) to the
child storage key (<<defn-child-storage-type>>).
* `prefix`: a pointer-size (<<defn-runtime-pointer-size>>) to the
prefix.
* `limit`: a pointer-size (<<defn-runtime-pointer-size>>) to an _Option_ type
(<<defn-option-type>>) containing an unsigned 32-bit integer indicating the
limit on how many keys should be deleted. No limit is applied if this is _None_.
Any keys created during the current block execution do not count towards the
limit.
* `return`: a pointer-size (<<defn-runtime-pointer-size>>) to the following variant, stem:[k]:
+
[stem]
++++
k = {(0,-> c),(1,-> c):}
++++
+
where _0_ indicates that all keys of the child storage have been removed,
followed by the number of removed keys, stem:[c]. The variant _1_ indicates that
there are remaining keys, followed by the number of removed keys.

==== `ext_default_child_storage_root`

Commits all existing operations and computes the resulting child storage
root.

===== Version 1 - Prototype
----
(func $ext_default_child_storage_root_version_1
	(param $child_storage_key i64) (return i64))
----

Arguments::

* `child_storage_key`: a pointer-size (<<defn-runtime-pointer-size>>) to the
child storage key (<<defn-child-storage-type>>).
* `return`: a pointer-size (<<defn-runtime-pointer-size>>) to the
SCALE encoded storage root.

===== Version 2 - Prototype
----
(func $ext_default_child_storage_root_version_2
	(param $child_storage_key i64) (param $version i32)
	(return i32))
----

Arguments::

* `child_storage_key`: a pointer-size (<<defn-runtime-pointer-size>>) to the
child storage key (<<defn-child-storage-type>>).
* `version`: the state version (<<defn-state-version>>).
* `return`: a pointer (<<defn-runtime-pointer>>) to the buffer containing the 256-bit Blake2 storage
root.

==== `ext_default_child_storage_next_key`

Gets the next key in storage after the given one in lexicographic order
(<<defn-lexicographic-ordering>>).
The key provided to this function may or may not exist in storage.

===== Version 1 - Prototype
----
(func $ext_default_child_storage_next_key_version_1
	(param $child_storage_key i64) (param $key i64) (return i64))
----

Arguments::

* `child_storage_key`: a pointer-size (<<defn-runtime-pointer-size>>) to the
child storage key (<<defn-child-storage-type>>).
* `key`: a pointer-size (<<defn-runtime-pointer-size>>) to the key. 
* `return`: a pointer-size (<<defn-runtime-pointer-size>>) to the SCALE
encoded as defined in <<defn-option-type>>
containing the next key in lexicographic order. Returns if the entry cannot be
found.
