[#sect-hashing-api]
== Hashing

Interface that provides functions for hashing with different algorithms.

=== Functions

==== `ext_hashing_keccak_256`

Conducts a 256-bit Keccak hash.

===== Version 1 - Prototype
----
(func $ext_hashing_keccak_256_version_1
	(param $data i64) (return i32))
----

Arguments::

* `data`: a pointer-size (<<defn-runtime-pointer-size>>) indicating the data
to be hashed.
* `return`: a pointer (<<defn-runtime-pointer>>) to the buffer containing the 256-bit hash result.

==== `ext_hashing_keccak_512`

Conducts a 512-bit Keccak hash.

===== Version 1 - Prototype
----
(func $ext_hashing_keccak_512_version_1
	(param $data i64) (return i32))
----

Arguments::

* `data`: a pointer-size (<<defn-runtime-pointer-size>>) indicating the data
to be hashed.
* `return`: a pointer (<<defn-runtime-pointer>>) to the buffer containing the 512-bit hash result.

==== `ext_hashing_sha2_256`

Conducts a 256-bit Sha2 hash.

===== Version 1 - Prototype
----
(func $ext_hashing_sha2_256_version_1
	(param $data i64) (return i32))
----

Arguments::

* `data`: a pointer-size (<<defn-runtime-pointer-size>>) indicating the data
to be hashed.
* `return`: a pointer (<<defn-runtime-pointer>>) to the buffer containing the 256-bit hash result.

==== `ext_hashing_blake2_128`

Conducts a 128-bit Blake2 hash.

===== Version 1 - Prototype
----
(func $ext_hashing_blake2_128_version_1
	(param $data i64) (return i32))
----

Arguments::

* `data`: a pointer-size (<<defn-runtime-pointer-size>>) indicating the data
to be hashed.
* `return`: a pointer (<<defn-runtime-pointer>>) to the buffer containing the 128-bit hash result.

==== `ext_hashing_blake2_256`

Conducts a 256-bit Blake2 hash.

===== Version 1 - Prototype
----
(func $ext_hashing_blake2_256_version_1
	(param $data i64) (return i32))
----

Arguments::

* `data`: a pointer-size (<<defn-runtime-pointer-size>>) indicating the data
to be hashed.
* `return`: a pointer (<<defn-runtime-pointer>>) to the buffer containing the 256-bit hash result.

==== `ext_hashing_twox_64`

Conducts a 64-bit xxHash hash.

===== Version 1 - Prototype
----
(func $ext_hashing_twox_64_version_1
	(param $data i64) (return i32))
----

Arguments::

* `data`: a pointer-size (<<defn-runtime-pointer-size>>) indicating the data
to be hashed.
* `return`: a pointer (<<defn-runtime-pointer>>) to the buffer containing the 64-bit hash result.

==== `ext_hashing_twox_128`

Conducts a 128-bit xxHash hash.

===== Version 1 - Prototype
----
(func $ext_hashing_twox_128
	(param $data i64) (return i32))
----

Arguments::

* `data`: a pointer-size (<<defn-runtime-pointer-size>>) indicating the data
to be hashed.
* `return`: a pointer (<<defn-runtime-pointer>>) to the buffer containing the 128-bit hash result.

==== `ext_hashing_twox_256`

Conducts a 256-bit xxHash hash.

===== Version 1 - Prototype
----
(func $ext_hashing_twox_256
	(param $data i64) (return i32))
----

Arguments::

* `data`: a pointer-size (<<defn-runtime-pointer-size>>) indicating the data
to be hashed.
* `return`: a pointer (<<defn-runtime-pointer>>) to the buffer containing the 256-bit hash result.