[#sect-misc-api]
== Miscellaneous

Interface that provides miscellaneous functions for communicating between the
runtime and the node.

=== Functions

==== `ext_misc_print_num`

Print a number.

===== Version 1 - Prototype
----
(func $ext_misc_print_num_version_1 (param $value i64))
----

Arguments::

* `value`: the number to be printed.

==== `ext_misc_print_utf8`

Print a valid UTF8 encoded buffer.

===== Version 1 - Prototype
----
(func $ext_misc_print_utf8_version_1 (param $data i64))
----

*Arguments*:

* : a pointer-size (<<defn-runtime-pointer-size>>) indicating
the valid buffer to be printed.

==== `ext_misc_print_hex`

Print any buffer in hexadecimal representation.

===== Version 1 - Prototype
----
(func $ext_misc_print_hex_version_1 (param $data i64))
----

*Arguments*:

* `data`: a pointer-size (<<defn-runtime-pointer-size>>) indicating
the buffer to be printed.

==== `ext_misc_runtime_version`

Extract the Runtime version of the given Wasm blob by calling `Core_version`
(<<defn-rt-core-version>>). Returns the SCALE encoded runtime version or _None_
(<<defn-option-type>>) if the call fails. This function gets primarily used when
upgrading Runtimes.

WARNING: Calling this function is very expensive and should only be done very
occasionally. For getting the runtime version, it requires instantiating the
Wasm blob (<<sect-loading-runtime-code>>) and calling a function in this blob.

===== Version 1 - Prototype
----
(func $ext_misc_runtime_version_version_1 (param $data i64) (result i64))
----

Arguments::

* `data`: a pointer-size (<<defn-runtime-pointer-size>>) indicating the Wasm
blob.
* `result`: a pointer-size (<<defn-runtime-pointer-size>>) indicating the SCALE
encoded _Option_ value (<<defn-option-type>>) containing the Runtime version of
the given Wasm blob which is encoded as a byte array.
