[#sect-storage-api]
=== Storage

Interface for accessing the storage from within the runtime.

[#defn-state-version]
.<<defn-state-version, State Version>>
====
The state version, stem:[v], dictates how a merkle root should be constructed.
The datastructure is a varying type of the following format:

[stem]
++++
v = {(0, "full values"),(1, "node hashes"):}
++++

where stem:[0] indicates that the values of the keys should be inserted into the
trie directly and stem:[1] makes use of "node hashes" when calculating the
merkle proof (<<defn-hashed-subvalue>>).
====

[#sect-storage-set]
==== `ext_storage_set`
Sets the value under a given key into storage.

===== Version 1 - Prototype
----
(func $ext_storage_set_version_1
	(param $key i64) (param $value i64))
----

Arguments::
* `key`: a pointer-size (<<defn-runtime-pointer-size>>) containing the key.
* `value`: a pointer-size (<<defn-runtime-pointer-size>>) containing the
value.

==== `ext_storage_get`
Retrieves the value associated with the given key from storage.

===== Version 1 - Prototype
----
(func $ext_storage_get_version_1
	(param $key i64) (result i64))
----

Arguments::
* `key`: a pointer-size (<<defn-runtime-pointer-size>>) containing the key.
* `result`: a pointer-size (<<defn-runtime-pointer-size>>) returning the SCALE
encoded _Option_ value (<<defn-option-type>>) containing the value.

==== `ext_storage_read`

Gets the given key from storage, placing the value into a buffer and
returning the number of bytes that the entry in storage has beyond the
offset.

===== Version 1 - Prototype
----
(func $ext_storage_read_version_1
	(param $key i64) (param $value_out i64) (param $offset i32) (result i64))
----

Arguments::
* `key`: a pointer-size (<<defn-runtime-pointer-size>>) containing the key.
* `value_out`: a pointer-size (<<defn-runtime-pointer-size>>) containing the
buffer to which the value will be written to. This function will never write
more then the length of the buffer, even if the value’s length is bigger.
* `offset`: an u32 integer (typed as i32 due to wasm types) containing the offset beyond the value should be read
from.
* `result`: a pointer-size (<<defn-runtime-pointer-size>>) pointing to a SCALE
encoded _Option_ value (<<defn-option-type>>) containing an unsigned 32-bit
integer representing the number of bytes left at supplied `offset`. Returns
_None_ if the entry does not exists.

==== `ext_storage_clear`

Clears the storage of the given key and its value. Nonexistent entries are
silently ignored.

===== Version 1 - Prototype
----
(func $ext_storage_clear_version_1
	(param $key_data i64))
----

Arguments::
* `key`: a pointer-size (<<defn-runtime-pointer-size>>) containing the key.

==== `ext_storage_exists`

Checks whether the given key exists in storage.

===== Version 1 - Prototype
----
(func $ext_storage_exists_version_1
	(param $key_data i64) (return i32))
----

Arguments::
* `key`: a pointer-size (<<defn-runtime-pointer-size>>) containing the key.
* `return`: an i32 integer value equal to _1_ if the key exists or a value equal
to _0_ if otherwise.

==== `ext_storage_clear_prefix`

Clear the storage of each key/value pair where the key starts with the given
prefix.

===== Version 1 - Prototype
----
(func $ext_storage_clear_prefix_version_1
	(param $prefix i64))
----

Arguments::
* `prefix`: a pointer-size (<<defn-runtime-pointer-size>>) containing
the prefix.

===== Version 2 - Prototype
----
(func $ext_storage_clear_prefix_version_2
	(param $prefix i64) (param $limit i64)
	(return i64))
----

Arguments::
* `prefix`: a pointer-size (<<defn-runtime-pointer-size>>) containing
the prefix.
* `limit`: a pointer-size (<<defn-runtime-pointer-size>>) to an _Option_ type
(<<defn-option-type>>) containing an unsigned 32-bit integer indicating the
limit on how many keys should be deleted. No limit is applied if this is _None_.
Any keys created during the current block execution do not count towards the
limit.
* `return`: a pointer-size (<<defn-runtime-pointer-size>>) to the following variant, stem:[k]:
+
[stem]
++++
k = {(0,-> c),(1,-> c):}
++++
+
where _0_ indicates that all keys of the child storage have been removed,
followed by the number of removed keys, stem:[c]. The variant _1_ indicates that
there are remaining keys, followed by the number of removed keys.

==== `ext_storage_append`

Append the SCALE encoded value to a SCALE encoded sequence (<<defn-scale-list>>)
at the given key. This function assumes that the existing storage item is either
empty or a SCALE encoded sequence and that the value to append is also SCALE
encoded and of the same type as the items in the existing sequence.

To improve performance, this function is allowed to skip decoding the entire
SCALE encoded sequence and instead can just append the new item to the end of
the existing data and increment the length prefix stem:["Enc"_("SC")^("Len")].

WARNING: If the storage item does not exist or is not SCALE encoded, the storage
item will be set to the specified value, represented as a SCALE encoded byte
array.

===== Version 1 - Prototype
----
(func $ext_storage_append_version_1
	(param $key i64) (param $value i64))
----

Arguments::
* `key`: a pointer-size (<<defn-runtime-pointer-size>>) containing the key.
* `value`: a pointer-size (<<defn-runtime-pointer-size>>) containing the
value to be appended.

==== `ext_storage_root`

Compute the storage root.

[#sect-ext-storage-root-version-1]
===== Version 1 - Prototype
----
(func $ext_storage_root_version_1
	(return i64))
----

Arguments::
* `return`: a pointer-size (<<defn-runtime-pointer-size>>) to a buffer containing
the 256-bit Blake2 storage root.

[#sect-ext-storage-root-version-2]
===== Version 2 - Prototype
----
(func $ext_storage_root_version_2
	(param $version i32) (return i32))
----

Arguments::
* `version`: the state version (<<defn-state-version>>).
* `return`: a pointer (<<defn-runtime-pointer>>) to the buffer containing the 256-bit Blake2 storage
root.

[#sect-ext-storage-changes-root]
==== `ext_storage_changes_root`

NOTE: This function is not longer used and only exists for compatibility reasons.

===== Version 1 - Prototype
----
(func $ext_storage_changes_root_version_1
	(param $parent_hash i64) (return i64))
----

Arguments::
* `parent_hash`: a pointer-size (<<defn-runtime-pointer-size>>) to the
SCALE encoded block hash.
* `return`: a pointer-size (<<defn-runtime-pointer-size>>) to an _Option_ type
(<<defn-option-type>>) that's always _None_.

==== `ext_storage_next_key`

Get the next key in storage after the given one in lexicographic order
(<<defn-lexicographic-ordering>>). The key provided to this function may or may
not exist in storage.

===== Version 1 - Prototype
----
(func $ext_storage_next_key_version_1
	(param $key i64) (return i64))
----

Arguments::
* `key`: a pointer-size (<<defn-runtime-pointer-size>>) to the key.
* `return`: a pointer-size (<<defn-runtime-pointer-size>>) to the SCALE
encoded _Option_ value (<<defn-option-type>>) containing the next key in
lexicographic order.

[#sect-ext-storage-start-transaction]
==== `ext_storage_start_transaction`

Start a new nested transaction. This allows to either commit or roll back all
changes that are made after this call. For every transaction there must be a
matching call to either `ext_storage_rollback_transaction`
(<<sect-ext-storage-rollback-transaction>>) or `ext_storage_commit_transaction`
(<<sect-ext-storage-commit-transaction>>). This is also effective for all values
manipulated using the child storage API (<<sect-child-storage-api>>).

WARNING: This is a low level API that is potentially dangerous as it can easily
result in unbalanced transactions. Runtimes should use high level storage
abstractions.

===== Version 1 - Prototype
----
(func $ext_storage_start_transaction_version_1)
----

Arguments::
* None.

[#sect-ext-storage-rollback-transaction]
==== `ext_storage_rollback_transaction`

Rollback the last transaction started by `ext_storage_start_transaction`
(<<sect-ext-storage-start-transaction>>). Any changes made during that
transaction are discarded.

WARNING: Panics if `ext_storage_start_transaction`
(<<sect-ext-storage-start-transaction>>) was not called.

===== Version 1 - Prototype
----
(func $ext_storage_rollback_transaction_version_1)
----

Arguments::
* None.

[#sect-ext-storage-commit-transaction]
==== `ext_storage_commit_transaction`
Commit the last transaction started by `ext_storage_start_transaction`
(<<sect-ext-storage-start-transaction>>). Any changes made during that
transaction are committed to the main state.

WARNING: Panics if `ext_storage_start_transaction`
(<<sect-ext-storage-start-transaction>>) was not called.

===== Version 1 - Prototype
----
(func $ext_storage_commit_transaction_version_1)
----

Arguments::
* None.
