[#sect-trie-api]
=== Trie

Interface that provides trie related functionality.

==== `ext_trie_blake2_256_root`

Compute a 256-bit Blake2 trie root formed from the iterated items.

===== Version 1 - Prototype
----
(func $ext_trie_blake2_256_root_version_1
	(param $data i64) (result i32))
----

Arguments::

* `data`: a pointer-size (<<defn-runtime-pointer-size>>) to the
iterated items from which the trie root gets formed. The items consist of a
SCALE encoded array containing arbitrary key/value pairs (tuples).
* `result`: a pointer (<<defn-runtime-pointer>>) to the buffer containing the 256-bit trie root.

===== Version 2 - Prototype
----
(func $ext_trie_blake2_256_root_version_2
	(param $data i64) (param $version i32)
	(result i32))
----

Arguments::

* `data`: a pointer-size (<<defn-runtime-pointer-size>>) to the
iterated items from which the trie root gets formed. The items consist of a
SCALE encoded array containing arbitrary key/value pairs (tuples).
* `version`: the state version (<<defn-state-version>>).
* `result`: a pointer (<<defn-runtime-pointer>>) to the buffer containing the 256-bit trie root.

==== `ext_trie_blake2_256_ordered_root`

Compute a 256-bit Blake2 trie root formed from the enumerated items.

===== Version 1 - Prototype
----
(func $ext_trie_blake2_256_ordered_root_version_1
	(param $data i64) (result i32))
----

Arguments::

* `data`: a pointer-size (<<defn-runtime-pointer-size>>) to the enumerated
items from which the trie root gets formed. The items consist of a SCALE encoded
array containing only values, where the corresponding key of each value is the
index of the item in the array, starting at 0. The keys are compact encoded
integers (<<defn-sc-len-encoding>>).
* `result`: a pointer (<<defn-runtime-pointer>>) to the buffer containing the 256-bit trie root
result.

===== Version 2 - Prototype
----
(func $ext_trie_blake2_256_ordered_root_version_2
	(param $data i64) (param $version i32)
	(result i32))
----

Arguments::

* `data`: a pointer-size (<<defn-runtime-pointer-size>>) to the enumerated
items from which the trie root gets formed. The items consist of a SCALE encoded
array containing only values, where the corresponding key of each value is the
index of the item in the array, starting at 0. The keys are compact encoded
integers (<<defn-sc-len-encoding>>).
* `version`: the state version (<<defn-state-version>>).
* `result`: a pointer (<<defn-runtime-pointer>>) to the buffer containing the 256-bit trie root
result.

==== `ext_trie_keccak_256_root`

Compute a 256-bit Keccak trie root formed from the iterated items.

===== Version 1 - Prototype
----
(func $ext_trie_keccak_256_root_version_1
	(param $data i64) (result i32))
----

Arguments::

* `data`: a pointer-size (<<defn-runtime-pointer-size>>) to the
iterated items from which the trie root gets formed. The items consist of a
SCALE encoded array containing arbitrary key/value pairs.
* `result`: a pointer (<<defn-runtime-pointer>>) to the buffer containing the 256-bit trie root.

===== Version 2 - Prototype
----
(func $ext_trie_keccak_256_root_version_2
	(param $data i64) (param $version i32)
	(result i32))
----

Arguments::

* `data`: a pointer-size (<<defn-runtime-pointer-size>>) to the
iterated items from which the trie root gets formed. The items consist of a
SCALE encoded array containing arbitrary key/value pairs.
* `version`: the state version (<<defn-state-version>>).
* `result`: a pointer (<<defn-runtime-pointer>>) to the buffer containing the 256-bit trie root.

==== `ext_trie_keccak_256_ordered_root`

Compute a 256-bit Keccak trie root formed from the enumerated items.

===== Version 1 - Prototype
----
(func $ext_trie_keccak_256_ordered_root_version_1
	(param $data i64) (result i32))
----

Arguments::

* `data`: a pointer-size (<<defn-runtime-pointer-size>>) to the enumerated
items from which the trie root gets formed. The items consist of a SCALE encoded
array containing only values, where the corresponding key of each value is the
index of the item in the array, starting at 0. The keys are compact encoded
integers (<<defn-sc-len-encoding>>).
* `result`: a pointer (<<defn-runtime-pointer>>) to the buffer containing the 256-bit trie root
result.

===== Version 2 - Prototype
----
(func $ext_trie_keccak_256_ordered_root_version_2
	(param $data i64) (param $version i32)
	(result i32))
----

Arguments::

* `data`: a pointer-size (<<defn-runtime-pointer-size>>) to the enumerated
items from which the trie root gets formed. The items consist of a SCALE encoded
array containing only values, where the corresponding key of each value is the
index of the item in the array, starting at 0. The keys are compact encoded
integers (<<defn-sc-len-encoding>>).
* `version`: the state version (<<defn-state-version>>).
* `result`: a pointer (<<defn-runtime-pointer>>) to the buffer containing the 256-bit trie root
result.

==== `ext_trie_blake2_256_verify_proof`

Verifies a key/value pair against a Blake2 256-bit merkle root.

===== Version 1 - Prototype
----
(func $ext_trie_blake2_256_verify_proof_version_1
	(param $root i32) (param $proof i64)
	(param $key i64) (param $value i64)
	(result i32))
----

Arguments::
* `root`: a pointer to the 256-bit merkle root.
* `proof`: a pointer-size (<<defn-runtime-pointer-size>>) to an array containing
the node proofs.
* `key`: a pointer-size (<<defn-runtime-pointer-size>>) to the key.
* `value`: a pointer-size (<<defn-runtime-pointer-size>>) to the value.
* `return`: a value equal to _1_ if the proof could be successfully verified or a
value equal to _0_ if otherwise.

===== Version 2 - Prototype
----
(func $ext_trie_blake2_256_verify_proof_version_2
	(param $root i32) (param $proof i64)
	(param $key i64) (param $value i64)
	(param $version i32) (result i32))
----

Arguments::
* `root`: a pointer to the 256-bit merkle root.
* `proof`: a pointer-size (<<defn-runtime-pointer-size>>) to an array containing
the node proofs.
* `key`: a pointer-size (<<defn-runtime-pointer-size>>) to the key.
* `value`: a pointer-size (<<defn-runtime-pointer-size>>) to the value.
* `version`: the state version (<<defn-state-version>>).
* `return`: a value equal to _1_ if the proof could be successfully verified or a
value equal to _0_ if otherwise.

==== `ext_trie_keccak_256_verify_proof`

Verifies a key/value pair against a Keccak 256-bit merkle root.

===== Version 1 - Prototype
----
(func $ext_trie_keccak_256_verify_proof_version_1
	(param $root i32) (param $proof i64)
	(param $key i64) (param $value i64)
	(result i32))
----

Arguments::
* `root`: a pointer to the 256-bit merkle root.
* `proof`: a pointer-size (<<defn-runtime-pointer-size>>) to an array containing
the node proofs.
* `key`: a pointer-size (<<defn-runtime-pointer-size>>) to the key.
* `value`: a pointer-size (<<defn-runtime-pointer-size>>) to the value.
* `return`: a value equal to _1_ if the proof could be successfully verified or a
value equal to _0_ if otherwise.

===== Version 2 - Prototype
----
(func $ext_trie_keccak_256_verify_proof_version_2
	(param $root i32) (param $proof i64)
	(param $key i64) (param $value i64)
	(param $version i32) (result i32))
----

Arguments::
* `root`: a pointer to the 256-bit merkle root.
* `proof`: a pointer-size (<<defn-runtime-pointer-size>>) to an array containing
the node proofs.
* `key`: a pointer-size (<<defn-runtime-pointer-size>>) to the key.
* `value`: a pointer-size (<<defn-runtime-pointer-size>>) to the value.
* `version`: the state version (<<defn-state-version>>).
* `return`: a value equal to _1_ if the proof could be successfully verified or a
value equal to _0_ if otherwise.
