[#sect-trie-api]
== Trie

Interface that provides trie related functionality.

=== Functions

==== `ext_trie_blake2_256_root`

Compute a 256-bit Blake2 trie root formed from the iterated items.

===== Version 1 - Prototype
----
(func $ext_trie_blake2_256_root_version_1
	(param $data i64) (result i32))
----

Arguments::

* `data`: a pointer-size (<<defn-runtime-pointer-size>>) indicating the
iterated items from which the trie root gets formed. The items consist of a
SCALE encoded array containing arbitrary key/value pairs.
* `result`: a pointer (<<defn-runtime-pointer>>) to the buffer containing the 256-bit trie root.

==== `ext_trie_blake2_256_ordered_root`

Compute a 256-bit Blake2 trie root formed from the enumerated items.

===== Version 1 - Prototype
----
(func $ext_trie_blake2_256_ordered_root_version_1
	(param $data i64) (result i32))
----

Arguments::

* `data`: a pointer-size (<<defn-runtime-pointer-size>>) indicating the enumerated
items from which the trie root gets formed. The items consist of a SCALE encoded
array containing only values, where the corresponding key of each value is the
index of the item in the array, starting at 0. The keys are compact encoded
integers (<<defn-sc-len-encoding>>).
* `result`: a pointer (<<defn-runtime-pointer>>) to the buffer containing the 256-bit trie root
result.

==== `ext_trie_keccak_256_root`

Compute a 256-bit Keccak trie root formed from the iterated items.

===== Version 1 - Prototype
----
(func $ext_trie_keccak_256_root_version_1
	(param $data i64) (result i32))
----

Arguments::

* `data`: a pointer-size (<<defn-runtime-pointer-size>>) indicating the
iterated items from which the trie root gets formed. The items consist of a
SCALE encoded array containing arbitrary key/value pairs.
* `result`: a pointer (<<defn-runtime-pointer>>) to the buffer containing the 256-bit trie root.

==== `ext_trie_keccak_256_ordered_root`

Compute a 256-bit Keccak trie root formed from the enumerated items.

===== Version 1 - Prototype
----
(func $ext_trie_keccak_256_ordered_root_version_1
	(param $data i64) (result i32))
----

Arguments::

* `data`: a pointer-size (<<defn-runtime-pointer-size>>) indicating the enumerated
items from which the trie root gets formed. The items consist of a SCALE encoded
array containing only values, where the corresponding key of each value is the
index of the item in the array, starting at 0. The keys are compact encoded
integers (<<defn-sc-len-encoding>>).
* `result`: a pointer (<<defn-runtime-pointer>>) to the buffer containing the 256-bit trie root
result.
