[#sect-block-validation]
= Importing and Validating Block

Block validation is the process by which a node asserts that a block is fit to
be added to the blockchain. This means that the block is consistent with the
current state of the system and transitions to a new valid state.

New blocks can be received by the Polkadot Host via other peers
(<<sect-msg-block-request>>) or from the Host’s own consensus engine
(<<sect-block-production>>). Both the Runtime and the Polkadot Host then need to
work together to assure block validity. A block is deemed valid if the block
author had authorship rights for the slot in which the block was produce as well
as if the transactions in the block constitute a valid transition of states. The
former criterion is validated by the Polkadot Host according to the block
production consensus protocol. The latter can be verified by the Polkadot Host
invoking entry into the Runtime as (<<sect-rte-core-execute-block>>) as a part
of the validation process. Any state changes created by this function on
successful execution are persisted.

The Polkadot Host implements <<algo-import-and-validate-block>> to assure the
validity of the block.

****
.Import-and-Validate-Block
[pseudocode#algo-import-and-validate-block]
++++
\require $B, \text{Just}(B)$

\state \call{Set-Storage-State-At}{$P(B)$}

\if{$\text{Just}(B) \neq \emptyset$}

    \state \call{Verify-Block-Justification}{$B, \text{Just}(B)$}

    \if{$B~\textbf{is}~\text{Finalized}~\textbf{and}~P(B)~\textbf{is not}~\text{Finalized}$}

        \state \call{Mark-as-Final}{$P(B)$}

     \endif

\endif

\if{$H_p(B) \notin PBT$}

    \return

\endif

\state \call{Verify-Authorship-Right}{$\text{Head}(B)$}

\state $B \leftarrow$ \call{Remove-Seal}{$B$}

\state $R \leftarrow$ \call{Call-Runtime-Entry}{$\texttt{Core\_execute\_block}, B$}

\state $B \leftarrow$ \call{Add-Seal}{$B$}

\if{$R =$ \textsc{True}}

    \state \call{Persist-State}{}

\endif
++++

where::
* stem:["Remove-Seal"] removes the Seal digest from the block (<<defn-digest>>)
before submitting it to the Runtime.
* stem:["Add-Seal"] adds the Seal digest back to the block (<<defn-digest>>) for
later propagation.
* stem:["Persist-State"] implies the persistence of any state changes created by
stem:[tt "Core_execute_block"] (<<sect-rte-core-execute-block>>) on successful
execution.
* stem:["PBT"] is the pruned block tree (<<defn-block-tree>>).
* stem:["Verify-Authorship-Right"] is part of the block production consensus
protocol and is described in <<algo-verify-authorship-right>>.
* _Finalized block_ and _finality_ are defined in <<sect-finality>>.
****
