[#sect-network-messages]
=== Network Messages

The Polkadot Host must actively communicate with the network in order to
participate in the validation process or act as a full node.

NOTE: The Polkadot network originally only used SCALE encoding for all message
formats. Meanwhile, Protobuf has been adopted for certain messages. The encoding
of each message is explicitly mentioned in their corresponding definition.
Encoding and message formats are subject to change.

[#sect-msg-block-announce]
==== Announcing blocks

When the node creates or receives a new block, it must be announced to the
network. Other nodes within the network will track this announcement and can
request information about this block. The mechanism for tracking announcements
and requesting the required data is implementation-specific.

Block announcements, requests and responses are sent over the substream as
defined in Definition
link:#defn-block-announce-handshake[[defn-block-announce-handshake]].

[#defn-block-announce-handshake]
===== Definition: Block Announce Handshake
The `BlockAnnounceHandshake` initializes a substream to a remote peer. Once
established, all `BlockAnounce` messages, as defined in Definition
link:#defn-block-announce[[defn-block-announce]], and created by the node are
sent to the `/dot/block-announces/1` substream.

The `BlockAnnounceHandshake` is a SCALE-encoded structure of the following
format:

[stem]
++++
BA_h = "Enc"_(SC)(R,N_B,h_B,h_G)
++++

where:

[stem]
++++
R = {(1,"The node is a full node"),(2,"The node is a light client"),(4,"The node is a validator"):}\
N_B = "Best block number according to the node"\
h_B = "Best block hash according to the node"\
h_G = "Genesis block hash according to the node"
++++