Consensus in the Polkadot Host is achieved during the execution of two
different procedures. The first procedure is the block-production and
the second is finality. The Polkadot Host must run these procedures if
(and only if) it is running on a validator node.

=== Common Consensus Structures

[#sect-authority-set]
==== Consensus Authority Set

Because Polkadot is a proof-of-stake protocol, each of its consensus engines has
its own set of nodes represented by known public keys, which have the authority
to influence the protocol in pre-defined ways explained in this Section. To
verify the validity of each block, the Polkadot node must track the current list
of authorities (<<defn-authority-list>>) for that block.

[#defn-authority-list]
.<<defn-authority-list, Authority List>>
====
The *authority list* of block stem:[B] for consensus engine stem:[C] noted as
stem:["Auth"_C(B)] is an array that contains the following pair of types for
each of its authorities stem:[A in "Auth"_C(B)]:

[stem]
++++
(pk_A,w_A)
++++

stem:[pk_A] is the session public key (<<defn-session-key>>) of authority
stem:[A]. And stem:[w_A] is an unsigned 64-bit integer indicating the authority
weight. The value of stem:["Auth"_C(B)] is part of the Polkadot state. The value
for stem:["Auth"_C(B_0)] is set in the genesis state (<<chapter-genesis>>) and
can be retrieved using a runtime entry corresponding to consensus engine
stem:[C].

The authorities and their corresponding weights can be retrieved from the
Runtime (<<sect-rte-grandpa-auth>>).
====

[#sect-consensus-message-digest]
==== Runtime-to-Consensus Engine Message

The authority list (<<defn-authority-list>>) is part of the Polkadot state and
the Runtime has the authority to update this list in the course of any state
transitions. The Runtime informs the corresponding consensus engine about the
changes in the authority set by adding the appropriate consensus message
(<<defn-consensus-message-digest>>) in the form of a digest item
(<<defn-digest>>) to the block header of block stem:[B] which caused the
transition in the authority set.

The Polkadot Host must inspect the digest header of each block and delegate
consensus messages to their consensus engines. The BABE and GRANDPA consensus
engine must react based on the type of consensus messages it receives. The
active GRANDPA authorities can only vote for blocks that occurred after the
finalized block in which they were selected. Any votes for blocks before the
came into effect would get rejected.

[#defn-consensus-message-digest]
.<<defn-consensus-message-digest, Consensus Message>>
====
A *consensus message*, stem:["CM"], is a digest item (<<defn-digest>>) of type
_4_ and consists one of the following tuple pairs, where the first item is a
string which serves as an identifier.

[stem]
++++
"CM" = {(,("'BABE'", "CM"_b)),(,("'FRNK'", "CM"_g)),(,("'BEEF'", "CM"_y)):}
++++

where::
[horizontal]
asciimath:["CM"_b]:: is a consensus message for BABE defined in <<defn-consensus-message-babe>>.
asciimath:["CM"_g]:: is a consensus message for GRANDPA defined in <<defn-consensus-message-grandpa>>.
asciimath:["CM"_y]:: is a consensus message for BEEFY defined in <<defn-consensus-message-beefy>>.
====

[#defn-consensus-message-babe]
.<<defn-consensus-message-babe, BABE Consensus Message>>
====
stem:["CM"_b], the consensus message for BABE, is of the following format:

[stem]
++++
"CM"_b = {(1,("Auth"_C, r)),(2,A_i),(3,D):}
++++

where::
[horizontal]
1:: implies *next epoch data*: The Runtime issues this message on every first
block of an epoch. The supplied authority set (<<defn-authority-list>>),
stem:["Auth"_C], and randomness (<<defn-epoch-randomness>>), stem:[r], are used
in the next epoch stem:[cc E_n + 1].
2:: implies *on disabled*: A 32-bit integer, stem:[A_i], indicating the
individual authority in the current authority list that should be immediately
disabled until the next authority set changes. This message initial intension
was to cause an immediate suspension of all authority functionality with the
specified authority.
3:: implies *next epoch descriptor*: These messages are only issued on
configuration change and in the first block of an epoch. The supplied
configuration data are intended to be used from the next epoch onwards.
+
* stem:[D] is a varying datatype of the following format:
+
[stem]
++++
D = {(1, (c,2_("nd"))):}
++++
+
where stem:[c] is the probability that a slot will not be empty
(<<defn-babe-constant>>). It is encoded as a tuple of two unsigned 64-bit
integers stem:[(c_("nominator"),c_("denominator"))] which are used to compute
the rational stem:[c = c_("nominator")/c_("denominator")].

* stem:[2_("nd")] describes what secondary slot (<<defn-babe-secondary-slots>>),
if any, is to be used. It is encoded as one-byte varying datatype:
+
[stem]
++++
s_"2nd" = {
	(0,->,"no secondary slot"),
	(1,->,"plain secondary slot"),
	(2,->,"secondary slot with VRF output")
:}
++++
====

[#defn-consensus-message-grandpa]
.<<defn-consensus-message-babe, GRANDPA Consensus Message>>
====
stem:["CM"_g], the consensus message for GRANDPA, is of the following format:

[stem]
++++
"CM"_g = {(1,("Auth"_C,N_("delay"))),(2,(m,"Auth"_C,N_("delay"))),(3,"A"_i),(4,N_("delay")),(5,N_("delay")):}
++++

where::
[horizontal]
asciimath:[N_"delay"]:: is an unsigned 32-bit integer indicating how deep in the
chain the announcing block must be before the change is applied.
1:: implies *scheduled change*: Schedule an authority set change after the
given delay of stem:[N_("delay") := |"SubChain"(B,B')|] where stem:[B'] is the
block where the change is applied. The earliest digest of this type in a
single block will be respected, unless a force change is present, in which case
the force change takes precedence.
2:: implies *forced change*: Schedule a forced authority set change after the
given delay of stem:[N_("delay") := |"SubChain"(B,m + B')|] where stem:[B'] is
the block where the change is applied. The earliest digest
of this type in a block will be respected.
+
Forced changes are explained further in <<sect-finality-forced-changes>>.
3:: implies *on disabled*: An index to the individual authority in the current
authority list (<<defn-authority-list>>) that should be immediately disabled
until the next authority set changes. When an authority gets disabled, the node
should stop performing any authority functionality from that authority,
including authoring blocks and casting GRANDPA votes for finalization.
Similarly, other nodes should ignore all messages from the indicated authority
which pertain to their authority role.
4:: implies *pause*: A signal to pause the current authority set after the
given delay of stem:[N_("delay") := |"SubChain"(B,B')|] where stem:[B'] is a
block where the change is applied. Once applied, the authorities should stop
voting.
5:: implies *resume*: A signal to resume the current authority set after the
given delay of stem:[N_("delay") := |"SubChain"(B,B')|] where stem:[B'] is the
block where the change is applied. Once applied, the authorities should resume
voting.
====

[#defn-consensus-message-beefy]
.<<defn-consensus-message-beefy, BEEFY Consensus Message>>
====
IMPORTANT: The BEEFY protocol is still under construction. The following part will be
updated in the future and certain information will be clarified.

stem:["CM"_y], the consensus message for BEEFY (<<sect-grandpa-beefy>>), is of
the following format:

[stem]
++++
"CM"_y = {(1,(V_B,V_i)),(2,A_i),(3,R):}
++++

where::
[horizontal]
1:: implies that the remote **authorities have changed**. stem:[V_B] is the
array of the new BEEFY authorities's public keys and stem:[V_i] is the
identifier of the remote validator set.
2:: implies **on disabled**: an index to the individual authorty in stem:[V_B]
that should be immediately disabled until the next authority change.
3:: implies **MMR root**: a 32-byte array containing the MMR root.
====
