[#sect-block-finalization]
=== Block Finalization

[#defn-finalized-block]
.<<defn-finalized-block, Finalized>>
====
A Polkadot relay chain node stem:[n] should consider block stem:[B] as
*finalized* if any of the following criteria hold for stem:[B' >= B]:

* stem:[V_("obs"(n))^(r,"pc")(B') > 2/3|bbb V_(B')|].
* It receives a stem:[M_v^(r,"Fin")(B')] message in which stem:[J^r(B)]
justifies the finalization (<<defn-grandpa-justification>>).
* It receives a block data message for stem:[B'] with stem:["Just"(B')]
(<<sect-justified-block-header>>) which justifies the finalization.

for:

* Any round stem:[r] if the node stem:[n] is _not_ a GRANDPA voter.
* Only for round stem:[r] for which the node stem:[n] has invoked Algorithm <<algo-grandpa-round>> and round stem:[r+1] if stem:[n] is a GRANDPA voter and has already caught up to its peers according to the process described in Section <<sect-grandpa-catchup>>.

Note that all Polkadot relay chain nodes are supposed to process GRANDPA commit
messages regardless of their GRANDPA voter status.
====

[#sect-grandpa-catchup]
==== Catching up

When a Polkadot node (re)joins the network during the process described in
<<chapter-bootstrapping>>, it requests the history of state transitions in the form of blocks, which it is missing.

Nonetheless, the process is different for a GRANDPA voter node. When a voter node joins the network, it needs to gather the justification (<<defn-grandpa-justification>>) of the rounds it has missed. Through this process, they can safely join the voting process of the current round, on which the voting is taking place.

[#sect-sending-catchup-request]
===== Sending the catch-up requests
When a Polkadot voter node has the same authority list as a peer voter node who is reporting
a higher number for the _finalized round_ field, it should send a catch-up
request message (<<defn-grandpa-catchup-request-msg>>) to the reporting peer. This will allow the node to
to catch up to the more advanced finalized round, provided that the
following criteria hold:

* The peer node is a GRANDPA voter, and:
* The last known finalized round for the Polkadot node is at least 2 rounds
behind the finalized round for the peer.

===== Processing the catch-up requests
Only GRANDPA voter nodes are required to respond to the catch-up requests. Additionally, it is only GRANDPA voters who are supposed to send catch-up requests. As such GRANDPA voters could safely ignore the catch-up requests from non-voter nodes. When a GRANDPA voter node receives a catch-up request message, it needs to execute the algorithm as defined in <<algo-process-catchup-request>>. Note: a voter node should not respond to catch-up requests for rounds that are actively being voted on, those are the rounds for which Algorithm <<algo-grandpa-round>> is not concluded.

****
.Process-Catchup-Request
[pseudocode#algo-process-catchup-request]
++++
\input $M_{i, v}^\text{Cat-q}(\text{id}_\mathbb{V}, r)$

\if{$M_{i, v}^\text{Cat-q}(\text{id}_\mathbb{V}, r).\text{id}_\mathbb{V} \neq \text{id}_\mathbb{V}$}

    \state \textbf{error} ``Catching up on different set''

\endif

\if{$i \notin \mathbb{P}$}

    \state \textbf{error} ``Requesting catching up from a non-peer''

\endif

\if{$r >$ \textsc{Last-Completed-Round}}

    \state \textbf{error} ``Catching up on a round in the future''

\endif

\state \textsc{Send}$\left(i, M_{v, i}^\text{Cat-s}(\text{id}_\mathbb{V}, r)\right)$
++++

where::
* stem:[M_(i,v)^("Cat"-q)("id"_(bbb V),r)] is the catch-up message received
from peer stem:[i] (<<defn-grandpa-catchup-request-msg>>).
* stem:["id"_(bbb V)] is the voter set id with which the serving node is
operating
* stem:[r] is the round number for which the catch-up is requested for.
* stem:[bbb P] is the set of immediate peers of node stem:[v].
* stem:[tt "Last-Completed-Round"] is initiated in the Algorithm as defined in
<<algo-initiate-grandpa>> and gets updated by the Algorithm as defined in
<<algo-grandpa-round>>.
* stem:[M_(v,i)^("Cat"-s)("id"_(bbb V),r)] is the catch-up response
(<<defn-grandpa-catchup-response-msg>>).
****

===== Processing catch-up responses

A Catch-up response message contains critical information for the requester node
to update their view on the active rounds which are being voted on by GRANDPA
voters. As such, the requester node should verify the content of the catch-up
response message and subsequently updates its view of the state of the finality
of the Relay chain according to Algorithm <<algo-process-catchup-response>>.

****
.Process-Catchup-Response
[pseudocode#algo-process-catchup-response]
++++
\input $M_{v,i}^\text{Cat-s}(\text{id}_{\mathbb{V}}, r)$

\state $M_{v,i}^\text{Cat-s}(\text{id}_{\mathbb{V}}, r).\text{id}_{\mathbb{V}}, r, J^{r, pv}(B), J^{r, pc}(B), H_h(B'), H_i(B') \leftarrow \text{Dec}_{SC}(M_{v, i}^{Cat-s}(\text{id}_{\mathbb{V}}, r)$

\if{$M_{v, i}^\text{Cat-s}(\text{id}_{\mathbb{V}}, r).\text{id}_{\mathbb{V}} \neq \text{id}_{\mathbb{V}}$}

    \state \textbf{error} ``Catching up on different set''

\endif

\if{$r \leqslant$ \textsc{Leading-Round}}

    \state \textbf{error} ``Catching up in to the past''

\endif

\if{$J^{r, pv}(B)$ \textbf{is not} valid}

    \state \textbf{error} ``Invalid pre-vote justification''

\endif

\if{$J^{r, pc}(B)$ \textbf{is not} valid}

    \state \textbf{error} ``Invalid pre-commit justification''

\endif

\state $G \leftarrow$ \textsc{GRANDPA-GHOST}$(J^{r, pv}(B))$

\if{$G = \phi$}

    \state \textbf{error} ``GHOST-less Catch-up''

\endif

\if{$r$ \textbf{is not} completable}

    \state \textbf{error} ``Catch-up round is not completable''

\endif

\if{$J^{r, pc}(B)$ justifies $B'$ finalization}

    \state \textbf{error} ``Unjustified Catch-up target finalization''

\endif

\state \textsc{Last-Completed-Round} $\leftarrow r$

\if{$i \in \mathbb{V}$}

    \state \textsc{Play-Grandpa-round}$(r + 1)$

\endif
++++

where stem:[M_(v,i)^("Cat"-s)("id"_(bbb V),r)] is the catch-up response
received from node stem:[v] (<<defn-grandpa-catchup-response-msg>>).
****
