= Introduction

The Polkadot Host uses GRANDPA Finality protocol to finalize blocks.
Finality is obtained by consecutive rounds of voting by the validator
nodes. Validators execute GRANDPA finality process in parallel to Block
Production as an independent service. In this section, we describe the
different functions that GRANDPA service performs to successfully
participate in the block-finalization process.

[#defn-grandpa-voter]
.<<defn-grandpa-voter, GRANDPA Voter>>
====
A *GRANDPA Voter*,
stem:[v], represented by a key pair
stem:[(K_v^("pr"),v_("id"))]
where stem:[k_v^("pr")] represents an
_ed25519_ private key, is a
node running a GRANDPA protocol and broadcasting votes to finalize
blocks in a Polkadot Host-based chain. The *set of all GRANDPA voters*
for a given block B is indicated by stem:[bbb V_B]. In that
regard, we have [To do: change function name, only call at genesis,
adjust V_B over the sections]

[stem]
++++
bbb V = tt "grandpa_authorities"(B)
++++

where stem:[tt "grandpa_authorities"] is a function entrypoint of the Runtime
described in <<sect-rte-grandpa-auth>>. We refer to stem:[bbb V_B] as
stem:[bbb V] when there is no chance of ambiguity.

Analogously we say that a Polkadot node is a *non-voter node* for block
stem:[B], if it does not own any of the key pairs in
stem:[bbb V_B].
====

[#defn-authority-set-id]
.<<defn-authority-set-id, Authority Set Id>>
====
The *authority set Id* (stem:["id"_(bbb V)]) is an incremental counter which
tracks the amount of authority list changes that occurred
(<<defn-consensus-message-digest>>). Starting with the value of zero at genesis,
the Polkadot Host increments this value by one every time a *Scheduled Change*
or a *Forced Change* occurs. The authority set Id is an unsigned 64-bit integer.
====

[#defn-grandpa-state]
.<<defn-grandpa-state, GRANDPA State>>
====
The *GRANDPA state*, stem:["GS"], is defined as:

[stem]
++++
"GS" := {bbb V, "id"_(bbb V),r}
++++

where::
* stem:[bbb V]: is the set of voters.
* stem:["id"_(bbb V)]: is the authority set ID (<<defn-authority-set-id>>).
* stem:[r]: is the voting round number.
====

[#defn-vote]
.<<defn-vote, GRANDPA Vote>>
====
A *GRANDPA vote* or simply a vote for block stem:[B] is an ordered pair defined
as

[stem]
++++
V(B) := (H_h(B),H_i(B))
++++

where stem:[H_h(B)] and stem:[H_i (B)] are the block hash
(<<defn-block-header-hash>>) and the block number (<<defn-block-header>>).
====

[#defn-voting-rounds]
.<<defn-voting-rounds, Voting Rounds>>
====
Voters engage in a maximum of two sub-rounds of voting for each round stem:[r].
The first sub-round is called *pre-vote* and the second sub-round is called
*pre-commit*.

By stem:[V_v^(r,"pv")] and stem:[V_v^(r,"pc")] we refer to the vote cast by
voter stem:[v] in round stem:[r] (for block stem:[B]) during the pre-vote and
the pre-commit sub-round respectively.

Voting is done by means of broadcasting voting messages (<<sect-msg-grandpa>>)
to the network. Validators inform their peers about the block finalized in round
stem:[r] by broadcasting a commit message (<<algo-grandpa-round>>).
====

[#defn-sign-round-vote]
.<<defn-sign-round-vote, Vote Signature>>
====
stem:["Sign"_(v_i)^(r,"stage")] refers to the signature of a voter for a specific
message in a round and is formally defined as:

[stem]
++++
"Sign"_(v_i)^(r,"stage") := "Sig"_("ed25519")("msg",r,"id"_(bbb V))
++++

where::
* stem:["msg"]: is an byte array containing the message to be signed
(<<defn-vote>>).
* stem:[r]: is an unsigned 64-bit integer is the round number.
* stem:["id"_(bbb V)]: is an unsigned 64-bit integer indicating the authority
set Id (<<defn-authority-list>>).
====

[#defn-grandpa-justification]
.<<defn-grandpa-justification, Justification>>
====
The *justification* for block stem:[B] in round stem:[r],
stem:[J^(r,"stage")(B)], is a vector of pairs of the type:

[stem]
++++
(V(B'),"Sign"_(v_i)^(r,"stage")(B'),v_("id"))
++++

in which either

[stem]
++++
B' >= B
++++

or stem:[V_(v_i)^(r,"pc")(B')] is an equivocatory vote.

In all cases, stem:["Sign"_(v_i)^(r,"stage")(B')] is the signature
(<<defn-sign-round-vote>>) of voter stem:[v_("id") in bbb V_B] broadcasted during
either the pre-vote (stage = pv) or the pre-commit (stage = pc) sub-round of
round r. A *valid justification* must only contain up-to-one valid vote from
each voter and must not contain more than two equivocatory votes from each
voter.
====

[#defn-finalizing-justification]
.<<defn-finalizing-justification, Finalizing Justification>>
====
We say stem:[J^(r,"pc")(B)] *justifies the finalization* of stem:[B' >= B] *for
a non-voter node* stem:[n] if the number of valid signatures in
stem:[J^(r,"pc")(B)] for stem:[B'] is greater than stem:[2/3|bbb V_B|].

Note that stem:[J^(r,"pc")(B)] can only be used by a non-voter node to finalize
a block. In contrast, a voter node can only be assured of the finality
(<<defn-finalized-block>>) of block stem:[B] by actively participating in the
voting process. That is by invoking <<algo-grandpa-round>>.

The GRANDPA protocol dictates how an honest voter should vote in each sub-round,
which is described by <<algo-grandpa-round>>. After
defining what constitutes a vote in GRANDPA, we define how GRANDPA counts votes.
====

[#defn-equivocation]
.<<defn-equivocation, Equivocation>>
====
Voter stem:[v] *equivocates* if they broadcast two or more valid votes to blocks
during one voting sub-round. In such a situation, we say that stem:[v] is an
*equivocator* and any vote stem:[V_v^(r,"stage")(B)] cast by stem:[v] in that
sub-round is an *equivocatory vote*, and

[stem]
++++
cc E^(r,"stage")
++++

represents the set of all equivocators voters in sub-round _stage_ of
round stem:[r]. When we want to refer to the number of equivocators whose
equivocation has been observed by voter stem:[v] we refer to it by:

[stem]
++++
cc E_("obs"(v))^(r,"stage")
++++

The Polkadot Host must detect equivocations committed by other validators and
submit those to the Runtime as described in
<<sect-grandpaapi_submit_report_equivocation_unsigned_extrinsic>>.

A vote stem:[V_v^(r,"stage") = V(B)] is *invalid* if

* stem:[H (B)] does not correspond to a valid block.
* stem:[B] is not an (eventual) descendant of a previously finalized block.
* stem:[M_v^(r,"stage")] does not bear a valid signature.
* stem:["id"_(bbb V)] does no match the current stem:[bbb V].
* stem:[V_v^(r,"stage")] is an equivocatory vote.
====

[#defn-observed-direct-votes]
.<<defn-observed-direct-votes, Set of Observed Direct Votes>>
====
For validator stem:[v], *the set of observed direct votes for Block stem:[B] in
round stem:[r]*, formally denoted by stem:["VD"_("obs"(v))^(r,"stage")(B)] is
equal to the union of:

* set of _valid_ votes stem:[V_(v_i)^(r,"stage")] cast in round stem:[r] and
received by stem:[v] such that stem:[V_(v_i)^(r,"stage") = V(B)].
====

[#defn-observed-votes]
.<<defn-observed-votes, Set of Total Observed Votes>>
====
We refer to *the set of total votes observed by voter stem:[v] in sub-round
_stage_ of round stem:[r]* by stem:[V_("obs"(v))^(r,"stage")].

The *set of all observed votes by stem:[v] in the sub-round stage of round
stem:[r] for block stem:[B]*, *stem:[V_("obs"(v))^(r,"stage")]* is equal to all
of the observed direct votes cast for block stem:[B] and all of the stem:[B]’s
descendants defined formally as:

[stem]
++++
V_("obs"(v))^(r,"stage")(B) := uuu_(v_i in bbb V, B < B') "VD"_("obs"(v))^(r,"stage")(B')
++++

The *total number of observed votes for Block stem:[B] in round stem:[r]* is
defined to be the size of that set plus the total number of equivocator voters:

[stem]
++++
#V_("obs"(v))^(r,"stage")(B) := |V_("obs"(v))^(r,"stage")(B)|+|cc E_("obs"(v))^(r,"stage")|
++++

Note that for genesis state we always have
stem:[#V_("obs"(v))^(r,"pv")(B) = |bbb V|].
====

[#defn-total-potential-votes]
.<<defn-total-potential-votes, Set of Total Potential Votes>>
====
Let stem:[V_("unobs"(v))^(r,"stage")] be the set of voters whose vote in the
given stage has not been received. We define the *total number of potential
votes for Block stem:[B] in round stem:[r]* to be:

[stem]
++++
#V_("obs"(v),"pot")^(r,"stage")(B) := |V_("obs"(v))^(r,"stage")(B)|+|V_("unobs"(v))^(r,"stage")|+"Min"(1/3|bbb V|,|bbb V|-|V_("obs"(v))^(r,"stage")(B)|-|V_("unobs"(v))^(r,"stage")|)
++++
====

[#defn-grandpa-ghost]
.<<defn-grandpa-ghost, Current Pre-Voted Block>>
====
The current *pre-voted* block stem:[B_v^(r,"pv")] also know as GRANDPA GHOST is
the block chosen by <<algo-grandpa-ghost>>:

[stem]
++++
B_v^(r,"pv") := "GRANDPA-GHOST"(r)
++++

Finally, we define when a voter stem:[v] sees a round as completable, that is
when they are confident that stem:[B_v^(r,"pv")] is an upper bound for what is
going to be finalized in this round.
====

[#defn-grandpa-completable]
.<<defn-grandpa-completable, Completable Round>>
====
We say that
round stem:[r] is *completable* if
stem:[|V_("obs"(v))^(r,"pc")|+ cc E_("obs"(v))^(r,"pc") > 2/3 bbb V]
and for all stem:[B' > B_v^(r,"pv")]:

[stem]
++++
|V_("obs"(v))^(r,"pc")|- cc E_("obs"(v))^(r,"pc") - |V_("obs"(v))^(r,"pc")(B')|> 2/3|bbb V|
++++

Note that in practice we only need to check the inequality for those stem:[B' >
B_v^(r,"pv")] where stem:[|V_("obs"(v))^(r,"pc")(B')| > 0].
====

[#defn-consensus-message-grandpa]
.<<defn-consensus-message-babe, GRANDPA Consensus Message>>
====
stem:["CM"_g], the consensus message for GRANDPA, is of the following format:

[stem]
++++
"CM"_g = {(1,("Auth"_C,N_("delay"))),(2,(m,"Auth"_C,N_("delay"))),(3,"A"_i),(4,N_("delay")),(5,N_("delay")):}
++++

where::
[horizontal]
asciimath:[N_"delay"]:: is an unsigned 32-bit integer indicating how deep in the
chain the announcing block must be before the change is applied.
1:: implies *scheduled change*: Schedule an authority set change after the
given delay of stem:[N_("delay") := |"SubChain"(B,B')|] where stem:[B'] is the
block where the change is applied. The earliest digest of this type in a
single block will be respected, unless a force change is present, in which case
the force change takes precedence.
2:: implies *forced change*: Schedule a forced authority set change after the
given delay of stem:[N_("delay") := |"SubChain"(B,m + B')|] where stem:[B'] is
the block where the change is applied. The earliest digest
of this type in a block will be respected.
+
Forced changes are explained further in <<sect-finality-forced-changes>>.
3:: implies *on disabled*: An index to the individual authority in the current
authority list (<<defn-authority-list>>) that should be immediately disabled
until the next authority set changes. When an authority gets disabled, the node
should stop performing any authority functionality from that authority,
including authoring blocks and casting GRANDPA votes for finalization.
Similarly, other nodes should ignore all messages from the indicated authority
which pertain to their authority role.
4:: implies *pause*: A signal to pause the current authority set after the
given delay of stem:[N_("delay") := |"SubChain"(B,B')|] where stem:[B'] is a
block where the change is applied. Once applied, the authorities should stop
voting.
5:: implies *resume*: A signal to resume the current authority set after the
given delay of stem:[N_("delay") := |"SubChain"(B,B')|] where stem:[B'] is the
block where the change is applied. Once applied, the authorities should resume
voting.
====

[#defn-consensus-message-beefy]
.<<defn-consensus-message-beefy, BEEFY Consensus Message>>
====
IMPORTANT: The BEEFY protocol is still under construction. The following part will be
updated in the future and certain information will be clarified.

stem:["CM"_y], the consensus message for BEEFY (<<sect-grandpa-beefy>>), is of
the following format:

[stem]
++++
"CM"_y = {(1,(V_B,V_i)),(2,A_i),(3,R):}
++++

where::
[horizontal]
1:: implies that the remote **authorities have changed**. stem:[V_B] is the
array of the new BEEFY authorities's public keys and stem:[V_i] is the
identifier of the remote validator set.
2:: implies **on disabled**: an index to the individual authorty in stem:[V_B]
that should be immediately disabled until the next authority change.
3:: implies **MMR root**: a 32-byte array containing the MMR root.
====
