= Voting Process in Round stem:[r]
For each round stem:[r], an honest voter stem:[v] must participate in the voting
process by following <<algo-grandpa-round>>.

****
.Play-Grandpa-Round
[pseudocode#algo-grandpa-round]
++++
\REQUIRE($r$)
\STATE $t_{r, v} \leftarrow$ Current local time
\STATE $\textrm{primary} \leftarrow$ \call{Derive-Primary}{$r$}
\IF{$v = \textrm{primary}$}
  \STATE \call{Broadcast}{$M_{v}^{r - 1, \textrm{Fin}}($\call{Best-Final-Candidate}{$r - 1$}$)$}
  \IF{\call{Best-Final-Candidate}{$r - 1$} $\geqslant$ \textsc{Last-Finalized-Block}}
    \STATE \call{Broadcast}{$M_{v}^{r - 1, \textrm{Prim}}($\call{Best-Final-Candidate}{$r - 1$}$)$}
  \ENDIF
\ENDIF
\STATE \call{Receive-Messages}{\textbf{until} Time $\geqslant t_{r_,v} + 2 \times T$ \or $r$ \textbf{is} completable}
\STATE $L \leftarrow$ \call{Best-Final-Candidate}{$r - 1$}
\STATE $N \leftarrow$ \call{Best-PreVote-Candidate}{$r$}
\STATE \call{Broadcast}{$M_v^{r, \textrm{pv}} (N)$}
\STATE \call{Receive-Messages}{\textbf{until} $B^{r,\textrm{pv}}_v \geqslant L$ \and $($ Time $\geqslant t_{r_,v} + 4 \times T$ \or $r$ \textbf{is} completable $)$}
\STATE \call{Broadcast}{$M_v^{r, \textrm{pc}}(B_v^{r, \textrm{pv}})$}

\REPEAT
  \STATE \call{Receive-Messages}{}
  \STATE \call{Attempt-To-Finalize-At-Round}{$r$}
\UNTIL{$r$ \textbf{is} completable \and \call{Finalizable}{$r$} \and \textsc{Last-Finalized-Block} $\geqslant$ \call{Best-Final-Candidate}{$r - 1$}}

\STATE \call{Play-Grandpa-round}{$r + 1$}

\REPEAT
  \STATE \call{Receive-Messages}{}
  \STATE \call{Attempt-To-Finalize-At-Round}{$r$}
\UNTIL{\textsc{Last-Finalized-Block} $\geqslant$ \call{Best-Final-Candidate}{$r$}}

\IF{\textsc{Last-Completed-Round} $ < r $}
  \STATE \textsc{Last-Completed-Round} $\leftarrow r$
\ENDIF
++++

where::
* stem:[T] is sampled from a log-normal distribution whose mean and standard
deviation are equal to the average network delay for a message to be sent and
received from one validator to another.
* stem:["Derive-Primary"] is described in <<algo-derive-primary>>.
* The condition of _completablitiy_ is defined in <<defn-grandpa-completable>>.
* stem:["Best-Final-Candidate"] function is explained in <<algo-grandpa-best-candidate>>.
* stem:["Attempt-To-Finalize-At-Round"(r)] is described in <<algo-attempt-to–finalize>>.
* stem:["Finalizable"] is defined in <<algo-finalizable>>.
****

****
.Derive-Primary
[pseudocode#algo-derive-primary]
++++
\input $r$

\return $r \bmod |\mathbb{V}|$
++++

where stem:[r] is the GRANDPA round whose primary is to be determined.
****

****
.Best-Final-Candidate
[pseudocode#algo-grandpa-best-candidate]
++++
\input $r$

\state $B_v^{r, pv} \leftarrow$ \call{GRANDPA-GHOST}{$r$}

\if{$r = 0$}

    \return $B_v^{r, pv}$

\else

    \state $\mathcal{C} \leftarrow \{ B' | B' \leqslant B_v^{r,pv} | \#V^{r, pc}_{\operatorname{obv}(v), pot}(B') > \frac{2}{3} |\mathbb{V}| \}$

    \if{$\mathcal{C} = \phi$}

        \return $B_v^{r, pv}$

    \else

        \return $E \in \mathcal{C} : H_n (E) = \operatorname{max}\left(H_n (B') | B' \in \mathcal{C}\right)$

    \endif

\endif
++++

where stem:[#V_("obv"(v),pot)^(r,pc)] is defined in <<defn-total-potential-votes>>.
****

****
.GRANDPA-GHOST
[pseudocode#algo-grandpa-ghost]
++++
\input $r$

\if{$r = 0$}

    \state $G \leftarrow B_{last}$

\else

    \state $L \leftarrow$ \call{Best-Final-Candidate}{$r - 1$}

    \state $\mathcal{G} = \{ \forall B > L | \#V_{\operatorname{obs}(v)}^{r, pv}(B) \geqslant \frac{2}{3} |\mathbb{V}| \}$

    \if{$\mathcal{G} = \phi$}

        \state $G \leftarrow L$

    \else

        \state $G \in \mathcal{G} | H_n(G) = \operatorname{max}\left( H_n (B) | \forall B \in \mathcal{G} \right)$

    \endif

\endif

\return $G$
++++

where::
* stem:[B_("last")] is the last block which has been finalized on the chain
(<<defn-finalized-block>>).
* stem:[#V_("obs"(v))^(r,pv)(B)] is defined in <<defn-observed-votes>>.
****

****
.Best-PreVote-Candidate
[pseudocode#algo-best-prevote-candidate]
++++
\input $r$

\state $B^{r, pv}_v \leftarrow$ \call{GRANDPA-GHOST}{$r$}

\if{\call{Received}{$M_{v_{primary}}^{r, prim}(B))$ \and $B^{r, pv}_v \geqslant B > L$}}

    \state $N \leftarrow B$

\else

    \state $N \leftarrow B^{r, pv}_v$

\endif
++++
****

****
.Attempt-To-Finalize-At-Round
[pseudocode#algo-attempt-to–finalize]
++++
\REQUIRE($r$)
\STATE $L \leftarrow$ \textsc{Last-Finalized-Block}
\STATE $E \leftarrow$ \call{Best-Final-Candidate}{$r$}
\IF{$E \geqslant L$ \and ${V^{r, \textrm{pc}}_{\textrm{obs}(v)}}(E) > 2 / 3 |\mathbb{V}|$}
  \STATE{\textsc{Last-Finalized-Block}$\leftarrow E$}
  \IF{$M_v^{r, \textrm{Fin}} (E) \notin $\textsc{Received-Messages}}
    \STATE \call{Broadcast}{$M_v^{r, \textrm{Fin}}(E)$}
    \RETURN
  \ENDIF
\ENDIF
++++
****

****
.Finalizable
[pseudocode#algo-finalizable]
++++
\REQUIRE($r$)
\IF{$r$ \textbf{is not} Completable}
  \RETURN \textbf{False}
\ENDIF
\STATE $G \leftarrow$ \call{GRANDPA-GHOST}{$J^{r, pv}(B)$}
\IF{$G = \phi$}
  \RETURN \textbf{False}
\ENDIF
\STATE $E_r \leftarrow$ \call{Best-Final-Candidate}{$r$}
\IF{$E_r \neq \phi$ \and \call{Best-Final-Candidate}{$r - 1$} $\leqslant E_r \leqslant G$}
  \RETURN \textbf{True}
\ELSE
  \RETURN \textbf{False}
\ENDIF
++++

where the condition for _completability_ is defined in <<defn-grandpa-completable>>.
****

Note that we might not always succeed in finalizing our best final candidate due to the possibility of equivocation. We might even not finalize anything in a round (although <<algo-grandpa-round>> prevents us from moving to the round stem:[r+1] before finalizing the best final candidate of round stem:[r-1]) The example in <<exmp-candid-unfinalized>> serves to demonstrate a situation where the best final candidate of a round cannot be finalized during its own round:

[#exmp-candid-unfinalized]
.Unfinalized Candidate
====
Let us assume
that we have 100 voters and there are two blocks in the chain
(stem:[B_1 < B_2]). At round 1, we get 67 pre-votes for
stem:[B_2] and at least one pre-vote for stem:[B_1] which
means that stem:["GRANDPA-GHOST"(1) = B_2].

Subsequently, potentially honest voters who could claim not seeing all the
pre-votes for stem:[B_2] but receiving the pre-votes for stem:[B_1] would
pre-commit to stem:[B_1]. In this way, we receive 66 pre-commits for stem:[B_1]
and 1 pre-commit for stem:[B_2]. Henceforth, we finalize stem:[B_1] since we
have a threshold commit (67 votes) for stem:[B_1].

At this point, though, we have
stem:[tt "Best-Final-Candidate"(r) = B_2] as
stem:[#V_("obs"(v),"pot")^(r,"stage")(B_2) = 67]
and stem:[2 > 1].

However, at this point, the round is already completable as we know that we have
stem:[tt "GRANDPA-GHOST"(1) = B_2] as an upper limit on what we can finalize and
nothing greater than stem:[B_2] can be finalized at stem:[r = 1]. Therefore, the
condition of <<algo-grandpa-round>> is satisfied and we must proceed to round 2.

Nonetheless, we must continue to attempt to finalize round _1_ in the background
as the condition of <<algo-attempt-to–finalize>> has not been fulfilled.

This prevents us from proceeding to round 3 until either:

* We finalize stem:[B_2] in round 2, or
* We receive an extra pre-commit vote for stem:[B_1] in round 1. This will make
it impossible to finalize stem:[B_2] in round 1, no matter to whom the remaining
pre-commits are going to be cast for (even with considering the possibility of
1/3 of voter equivocating) and therefore we have stem:[tt
"Best-Final-Candidate"(r) = B_1].

Both scenarios unblock <<algo-grandpa-round>>,
stem:[tt "Last-Finalized-Block" >= tt "Best-Final-Candidate"(r - 1)] albeit in
different ways: the former with increasing the stem:[tt "Last-Finalized-Block"]
and the latter with decreasing stem:[tt "Best-Final-Candidate"(r - 1)].
====
