Consensus in the Polkadot Host is achieved during the execution of two
different procedures. The first procedure is the block-production and
the second is finality. The Polkadot Host must run these procedures if
(and only if) it is running on a validator node.

=== Common Consensus Structures

[#sect-authority-set]
==== Consensus Authority Set

Because Polkadot is a proof-of-stake protocol, each of its consensus engines has
its own set of nodes represented by known public keys, which have the authority
to influence the protocol in pre-defined ways explained in this Section. To
verify the validity of each block, the Polkadot node must track the current list
of authorities for that block as formalized in Definition
link_defn-authority-list++defn-authority-list]]

[#defn-authority-list]
===== Authority List
****
The *authority list* of block stem:[B] for consensus engine stem:[C] noted as
stem:["Auth"_C(B)] is an array that contains the following pair of types for
each of its authorities stem:[A in "Auth"_C(B)]:

[stem]
++++
(pk_A,w_A)
++++

stem:[pk_A] is the session public key of authority A as defined in Definition
link_defn-session-key++defn-session-key]]. And stem:[w_A] is an unsigned 64-bit
integer indicating the authority weight. The value of stem:["Auth"_C(B)] is part
of the Polkadot state. The value for stem:["Auth"_C(B_0)] is set in the genesis
state (see Section link_sect-genesis-block[11]) and can be retrieved using a
runtime entry corresponding to consensus engine stem:[C].

In Polkadot, all authorities have the weight stem:[w_A = 1]. The weight
stem:[w_A] in Definition link_defn-authority-list++defn-authority-list]] exists
for potential improvements in the protocol and could have a use-case in the
future.
****

[#sect-consensus-message-digest]
==== Runtime-to-Consensus Engine Message

The authority list (see Definition
link_defn-authority-list++defn-authority-list]]) is part of the Polkadot state
and the Runtime has the authority to update this list in the course of any state
transitions. The Runtime informs the corresponding consensus engine about the
changes in the authority set by adding the appropriate consensus message as
defined in Definition
link_defn-consensus-message-digest++defn-consensus-message-digest]], in the
form of a digest item to the block header of block stem:[B] which caused the
transition in the authority set.

The Polkadot Host must inspect the digest header of each block and delegate
consensus messages to their consensus engines. The BABE and GRANDPA consensus
engine must react based on the type of consensus messages it receives. The
active GRANDPA authorities can only vote for blocks that occurred after the
finalized block in which they were selected. Any votes for blocks before the
came into effect would get rejected.

[#defn-consensus-message-digest]
===== Consensus Message
****
A *consensus message* is a digest item of type 4 as defined in Definition
link_defn-digest++defn-digest]] and consists of the pair:

[stem]
++++
(E_("id"), CM)
++++

where stem:[E_("id") in bbb "B"_4] is the consensus engine unique identifier
which can hold the following possible values

[stem]
++++
E_("id") = {("'BABE'"),("'FRNK'"):}
++++

where stem:["'BABE'"] is for messages related to the BABE protocol, referred to
as stem:[E_("id")("BABE")] and stem:["'FRNK"] is for messages related to the
GRANDPA protocol, referred to as stem:[E_("id")("FRNK")]. stem:[CM] is a varying
datatype (TODO: Reference) which can be one of the following values, appended by
additional data:

[stem]
++++
CM = {(1, ("Auth"_("BABE"),R)),(2,"Auth"_("id")),(3,(c,s_("2nd"))):}
++++

where

* stem:[CM]:
+
** _1_ implies *next epoch data*: The Runtime issues this message on every first
block of an epoch stem:[cc "E"_n]. The supplied authority set and randomness are
intended to be used in the next epoch stem:[cc "E"_n + 1].  
** _2_ implies *on disabled*: An index to the individual authority in the
current authority list that should be immediately disabled until the next
authority set changes. When an authority gets disabled, the node should stop
performing any authority functionality for that authority, including authoring
blocks. Similarly, other nodes should ignore all messages from the indicated
authority which pertain to their authority role.
** _3_ implies *next config data*: These messages are only issued on
configuration change and in the first block of an epoch. The supplied
configuration data are intended to be used from the next epoch onwards.
* stem:["Auth"_("BABE")] is the authority list for the next epoch, as defined in
definition link_defn-authority-list++defn-authority-list]].
* stem:[R] is the 32-byte randomness seed for the next epoch, as defined in
definition link_defn-epoch-randomness++defn-epoch-randomness]]
* stem:["Auth"_("id")] is an unsigned 64-bit integer pointing to an individual
authority in the current authority list.
* stem:[c] is the probability that a slot will not be empty, as defined in
definition link_defn-babe-constant++defn-babe-constant]]. It is encoded as a
tuple of two unsigned 64-bit integers stem:[(c_("nominator"),c_("denominator"))]
which are used to compute the rational stem:[c =
c_("nominator")/c_("denominator")].
* stem:[s_("2nd")] is a varying datatype followed by additional data indicating
the second slot configuration:
+
[stem]
++++
s_("2nd") = {(1,("Auth"_C,N_("delay"))),(2,("Auth"_C,N_("delay"))),(3,"Auth"_("id")),(4,N_("delay")),(5,N_("delay")):}
++++
+
where (TODO: Maybe add some references here?):
+
** stem:[Auth_C] is the authority list as defined in Definition (TODO).
** stem:[N_("delay")] is an unsigned 32-bit integer indicating how deep in the chain
the announcing block must be before the change is applied.
** _1_ implies *scheduled change*: Schedule an authority set change after the
given delay of stem:[N_("delay") := |"SubChain"(B,B')|] where stem:[B'] in the
definition of stem:[N_("delay")], is a block _finalized_ by the finality
consensus engine. The earliest digest of this type in a single block will be
respected. No change should be scheduled if one is already finalized and the
delay has not passed completely. If such an inconsistency occurs, the scheduled
change should be ignored.
** _2_ implies *forced change*: Force an authority set change after the given
delay of stem:[N_("delay") := |"SubChain"(B,B')|] where stem:[B'] in the
definition of stem:[N_("delay")], is an _imported_ block that has been validated
by the block production consensus engine. Hence, the authority changeset is
valid for every subchain containing _B_ and where the delay has been exceeded.
If one or more blocks gets finalized before the change takes effect, the
authority set change should be disregarded. The earliest digest of this type in
a single block will be respected. No change should be scheduled if one is
already finalized and the delay has not passed completely. If such an
inconsistency occurs, the scheduled change should be ignored.
** _3_ implies *on disabled*: An index to the individual authority in the
current authority list that should be immediately disabled until the next
authority set changes. When an authority gets disabled, the node should stop
performing any authority functionality from that authority, including authoring
blocks and casting GRANDPA votes for finalization. Similarly, other nodes should
ignore all messages from the indicated authority which pertain to their
authority role.
** _4_ implies *pause*: A signal to pause the current authority set after the
given delay of stem:[N_("delay") := |"SubChain"(B,B')|] where stem:[B'] in the
definition of stem:[N_("delay")], is a block _finalized_ by the finality
consensus engine. After finalizing block stem:[B'], the authorities should stop
voting.
** _5_ implies *resume*: A signal to resume the current authority set after the
given delay of stem:[N_("delay") := |"SubChain"(B,B')|] where stem:[B'] in the
definition of stem:[N_("delay")], is an _imported_ block and validated by the
block production consensus engine. After authoring block stem:[B'], the
authorities should resume voting.
****
