Consensus in the Polkadot Host is achieved during the execution of two
different procedures. The first procedure is the block-production and
the second is finality. The Polkadot Host must run these procedures if
(and only if) it is running on a validator node.

=== Common Consensus Structures

[#sect-authority-set]
==== Consensus Authority Set

Because Polkadot is a proof-of-stake protocol, each of its consensus engines has
its own set of nodes represented by known public keys, which have the authority
to influence the protocol in pre-defined ways explained in this Section. To
verify the validity of each block, the Polkadot node must track the current list
of authorities for that block as formalized in Definition
link:#defn-authority-list[[defn-authority-list]]

[#defn-authority-list]
===== Authority List
****
The *authority list* of block stem:[B] for consensus engine stem:[C] noted as
stem:["Auth"_C(B)] is an array that contains the following pair of types for
each of its authorities stem:[A in "Auth"_C(B)]:

[stem]
++++
(pk_A,w_A)
++++

stem:[pk_A] is the session public key of authority A as defined in Definition
link:#defn-session-key[[defn-session-key]]. And stem:[w_A] is an unsigned 64-bit
integer indicating the authority weight. The value of stem:["Auth"_C(B)] is part
of the Polkadot state. The value for stem:["Auth"_C(B_0)] is set in the genesis
state (see Section link:#sect-genesis-block[11]) and can be retrieved using a
runtime entry corresponding to consensus engine stem:[C].

In Polkadot, all authorities have the weight stem:[w_A = 1]. The weight
stem:[w_A] in Definition link:#defn-authority-list[[defn-authority-list]] exists
for potential improvements in the protocol and could have a use-case in the
future.
****
