[#sect-finality]
=== Finality

The Polkadot Host uses GRANDPA Finality protocol to finalize blocks.
Finality is obtained by consecutive rounds of voting by the validator
nodes. Validators execute GRANDPA finality process in parallel to Block
Production as an independent service. In this section, we describe the
different functions that GRANDPA service performs to successfully
participate in the block-finalization process.

==== Preliminaries

[#defn-grandpa-voter]
===== GRANDPA Voter
****
A *GRANDPA Voter*,
stem:[v], represented by a key pair
stem:[(K_v^("pr"),v_("id"))]
where stem:[k_v^("pr")] represents an
_ed25519_ private key, is a
node running a GRANDPA protocol and broadcasting votes to finalize
blocks in a Polkadot Host-based chain. The *set of all GRANDPA voters*
for a given block B is indicated by stem:[bbb "V"_B]. In that
regard, we have [To do: change function name, only call at genesis,
adjust V_B over the sections]

[stem]
++++
bbb "V" = tt "grandpa_authorities"(B)
++++

where stem:[tt "grandpa_authorities"] is the entry into the Runtime described in
Section link_sect-rte-grandpa-auth[13.3.7.1]. We refer to stem:[bbb "V"_B] as
stem:[bbb "V"] when there is no chance of ambiguity.

Analogously we say that a Polkadot node is a *non-voter node* for block
stem:[B], if it does not own any of the key pairs in
stem:[bbb "V"_B].
****

[#defn-authority-set-id]
===== Authority Set Id
****
The *authority set Id* (stem:["id"_(bbb "V")]) is an incremental counter which
tracks the amount of authority list changes that occurred (Definition
link_defn-consensus-message-digest++defn-consensus-message-digest]]). Starting
with the value of zero at genesis, the Polkadot Host increments this value by
one every time a *Scheduled Change* or a *Forced Change* occurs. The authority
set Id is an unsigned 64-bit integer.
****

===== GRANDPA State
****
TODO: verify V_id and id_V usage, unify

The *GRANDPA state*, stem:["GS"], is defined as:

[stem]
++++
"GS" := {bbb "V", "id"_(bbb "V"),r}
++++

where:

* stem:[bbb "V"]: is the set of voters.
* stem:["id"_(bbb "V")]: is the authority set ID as defined in Definition
link_defn-authority-set-id++defn-authority-set-id]].
* stem:[r]: is the voting round number.
****

[#defn-vote]
===== GRANDPA Vote
****
A *GRANDPA vote* or simply a vote for block stem:[B] is an ordered pair defined
as

[stem]
++++
V(B) := (H_h(B),H_i(B))
++++

where stem:[H_h(B)] and stem:[H_i (B)] are the block hash and the block number
defined in Definitions link_defn-block-header++defn-block-header]] and
link_defn-block-header-hash++defn-block-header-hash]] respectively.
****

===== Voting Rounds
****
Voters engage in a maximum of two sub-rounds of voting for each round stem:[r].
The first sub-round is called *pre-vote* and the second sub-round is called
*pre-commit*.

By stem:[V_v^(r,"pv")] and stem:[V_v^(r,"pc")] we refer to the vote cast by
voter stem:[v] in round stem:[r] (for block stem:[B]) during the pre-vote and
the pre-commit sub-round respectively.

Voting is done by means of broadcasting voting messages to the network. The
structure of these messages is described in Section
link_sect-msg-grandpa[4.8.4]. Validators inform their peers about the block
finalized in round stem:[r] by broadcasting a commit message (see Algorithm
link_algo-grandpa-round++algo-grandpa-round]] for more details).
****

[#defn-sign-round-vote]
===== Vote Signature
****
stem:["Sign"_(v_i)^(r,"stage")] refers to the signature of a voter for a specific
message in a round and is formally defined as:

[stem]
++++
"Sign"_(v_i)^(r,"stage") := "Sig"_("ed25519")("msg",r,"id"_(bbb "V"))
++++

where:

* stem:["msg"]: is an byte array containing the message to be signed (TODO: format of the message?).
* stem:[r]: is an unsigned 64-bit integer is the round number.
* stem:["id"_(bbb "V")]: is an unsigned 64-bit integer indicating the authority
set Id (TODO: Reference).
****

[#defn-grandpa-justification]
===== Justification
****
The *justification* for block stem:[B] in round stem:[r],
stem:[J^(r,"stage")(B)], is a vector of pairs of the type:

[stem]
++++
(V(B'),"Sign"_(v_i)^(r,"stage")(B'),v_("id"))
++++

in which either

[stem]
++++
B' >= B
++++

or stem:[V_(v_i)^(r,"pc")(B')] is an equivocatory vote.

In all cases, stem:["Sign"_(v_i)^(r,"stage")(B')], as defined in Definition
link_defn-sign-round-vote++defn-sign-round-vote]], is the signature of voter
stem:[v_i in bbb "V"_B] broadcasted during either the pre-vote (stage = pv) or
the pre-commit (stage = pc) sub-round of round r. A *valid justification* must
only contain up-to-one valid vote from each voter and must not contain more than
two equivocatory votes from each voter.
****

[#defn-finalizing-justification]
===== Finalizing Justification
****
We say stem:[J^(r,"pc")(B)] *justifies the finalization* of stem:[B' >= B] *for
a non-voter node* stem:[n] if the number of valid signatures in
stem:[J^(r,"pc")(B)] for stem:[B'] is greater than stem:[2/3|bbb "V"_B|].

Note that stem:[J^(r,"pc")(B)] can only be used by a non-voter node to finalize
a block. In contrast, a voter node can only be assured of the finality of block
stem:[B] by actively participating in the voting process. That is by invoking
Algorithm link_algo-grandpa-round++algo-grandpa-round]]. See Definition
link_defn-finalized-block++defn-finalized-block]] for more details.

The GRANDPA protocol dictates how an honest voter should vote in each
sub-round, which is described in Algorithm
link_algo-grandpa-round++algo-grandpa-round]]. After defining what
constitutes a vote in GRANDPA, we define how GRANDPA counts votes.
****

[#defn-equivocation]
===== Equivocation
****
Voter stem:[v] *equivocates* if they broadcast two or more valid votes to blocks
during one voting sub-round. In such a situation, we say that stem:[v] is an
*equivocator* and any vote stem:[V_v^(r,"stage")(B)] cast by stem:[v] in that
sub-round is an *equivocatory vote*, and

[stem]
++++
cc "E"^(r,"stage")
++++

represents the set of all equivocators voters in sub-round _stage_ of
round stem:[r]. When we want to refer to the number of equivocators whose
equivocation has been observed by voter stem:[v] we refer to it by:

[stem]
++++
cc "E"_("obs"(v))^(r,"stage")
++++

The Polkadot Host must detect equivocations committed by other validators and
submit those to the Runtime as described in Section
link_sect-grandpaapi_submit_report_equivocation_unsigned_extrinsic[13.3.7.2].

A vote stem:[V_v^(r,"stage") = V(B)] is *invalid* if

* stem:[H (B)] does not correspond to a valid block.
* stem:[B] is not an (eventual) descendant of a previously finalized block.
* stem:[M_v^(r,"stage")] does not bear a valid signature.
* stem:["id"_(bbb "V")] does no match the current stem:[bbb "V"].
* stem:[V_v^(r,"stage")] is an equivocatory vote.
****

===== Set of Observed Votes
****
For validator stem:[v], *the set of observed direct votes for Block stem:[B] in
round stem:[r]*, formally denoted by stem:["VD"_("obs"(v))^(r,"stage")(B)] is
equal to the union of:

* set of _valid_ votes stem:[V_(v_i)^(r,"stage")] cast in round stem:[r] and
received by stem:[v] such that stem:[V_(v_i)^(r,"stage") = V(B)].
****

[#defn-observed-votes]
===== Set of Total Observed Votes
****
We refer to *the set of total votes observed by voter stem:[v] in sub-round
_stage_ of round stem:[r]* by stem:[V_("obs"(v))^(r,"stage")].

The *set of all observed votes by stem:[v] in the sub-round stage of round
stem:[r] for block stem:[B]*, *stem:[V_("obs"(v))^(r,"stage")]* is equal to all
of the observed direct votes cast for block stem:[B] and all of the stem:[B]’s
descendants defined formally as:

[stem]
++++
V_("obs"(v))^(r,"stage")(B) := uuu_(v_i in bbb "V", B >= B') "VD"_("obs"(v))^(r,"stage")(B')
++++

The *total number of observed votes for Block stem:[B] in round stem:[r]* is
defined to be the size of that set plus the total number of equivocator voters:

[stem]
++++
#V_("obs"(v))^(r,"stage")(B) := |V_("obs"(v))^(r,"stage")(B)|+|cc "E"_("obs"(v))^(r,"stage")|
++++

Note that for genesis state we always have
stem:[#V_("obs"(v))^(r,"pv")(B) = |bbb "V"|].
****

[#defn-total-potential-votes]
===== Set of Total Potential Votes
****
Let stem:[V_("unobs"(v))^(r,"stage")] be the set of voters whose vote in the
given stage has not been received. We define the *total number of potential
votes for Block stem:[B] in round stem:[r]* to be:

[stem]
++++
#V_("obs"(v),"pot")^(r,"stage")(B) := |V_("obs"(v))^(r,"stage")(B)|+|V_("unobs"(v))^(r,"stage")|+"Min"(1/3|bbb "V"|,|bbb "V"|-|V_("obs"(v))^(r,"stage")(B)|-|V_("unobs"(v))^(r,"stage")|)
++++
****

===== Current Pre-Voted Block
****
The current *pre-voted* block stem:[B_v^(r,"pv")] also know as GRANDPA GHOST is
the block chosen by Algorithm link_algo-grandpa-ghost++algo-grandpa-ghost]]:

[stem]
++++
B_v^(r,"pv") := "GRANDPA-GHOST"(r)
++++

Finally, we define when a voter stem:[v] sees a round as completable, that is
when they are confident that stem:[B_v^(r,"pv")] is an upper bound for what is
going to be finalized in this round.
****

[#defn-grandpa-completable]
===== Completable Round
****
We say that
round stem:[r] is *completable* if
stem:[|V_("obs"(v))^(r,"pc")|+ cc "E"_("obs"(v))^(r,"pc") > 2/3 bbb "V"]
and for all stem:[B' > B_v^(r,"pv")]:

[stem]
++++
|V_("obs"(v))^(r,"pc")|- cc "E"_("obs"(v))^(r,"pc") - |V_("obs"(v))^(r,"pc")(B')|> 2/3|bbb "V"|
++++

Note that in practice we only need to check the inequality for those stem:[B' >
B_v^(r,"pv")] where stem:[|V_("obs"(v))^(r,"pc")(B')| > 0].
****

==== Initiating the GRANDPA State
In order to participate coherently in the voting process, a validator must
initiate its state and sync it with other active validators. In particular,
considering that voting is happening in different distinct rounds where each
round of voting is assigned a unique sequential round number stem:[r_v], it
needs to determine and set its round counter stem:[r] equal to the voting round
stem:[r_n] currently undergoing in the network. Algorithm
link_algo-initiate-grandpa++algo-initiate-grandpa]] mandates the initialization
procedure for GRANDPA protocol for a joining validator.

TODO: Algorithm

stem:[r_("last")] is equal to the latest round the voter has observed that other
voters are voting on. The voter obtains this information through various
gossiped messages including those mentioned in Definition
link_defn-finalized-block++defn-finalized-block]].

stem:[r_("last")] is set to _0_ if the GRANDPA node is initiating the GRANDPA
voting process as a part of a new authority set. This is because the GRANDPA
round number reset to _0_ for every authority set change.

===== Voter Set Changes

Voter set changes are signalled by Runtime via a consensus engine message as
described in Section link_sect-consensus-message-digest[6.1.2]. When
Authorities process such messages they must not vote on any block with a higher
number than the block at which the change is supposed to happen. The new
authority set should reinitiate GRANDPA protocol by executing Algorithm
link_algo-initiate-grandpa++algo-initiate-grandpa]].

TODO: Algorithms...

Note that we might not always succeed in finalizing our best final candidate due
to the possibility of equivocation. Example
link_exmp-candid-unfinalized++exmp-candid-unfinalized]] serves to demonstrate
such a situation:

TODO: Number example block

[#exmp-candid-unfinalized]
====
Let us assume
that we have 100 voters and there are two blocks in the chain
(stem:[B_1 < B_2]). At round 1, we get 67 pre-votes for
stem:[B_2] and at least one pre-vote for stem:[B_1] which
means that stem:["GRANDPA-GHOST"(1) = B_2].

Subsequently, potentially honest voters who could claim not seeing all the
pre-votes for stem:[B_2] but receiving the pre-votes for stem:[B_1] would
pre-commit to stem:[B_1]. In this way, we receive 66 pre-commits for stem:[B_1]
and 1 pre-commit for stem:[B_2]. Henceforth, we finalize stem:[B_1] since we
have a threshold commit (67 votes) for stem:[B_1].

At this point, though, we have
stem:[tt "Best-Final-Candidate"(r) = B_2] as
stem:[#V_("obs"(v),"pot")^(r,"stage")(B_2) = 67]
and stem:[2 > 1].

However, at this point, the round is already completable as we know that we have
stem:[tt "GRANDPA-GHOST"(1) = B_2] as an upper limit on what we can finalize and
nothing greater than stem:[B_2] can be finalized at stem:[r = 1]. Therefore, the
condition of Algorithm link_algo-grandpa-round++algo-grandpa-round]]:14 is
satisfied and we must proceed to round 2.

Nonetheless, we must continue to attempt to finalize round 1 in the background
as the condition of link_algo-attempt-tofinalize++algo-attempt-tofinalize]]:3
has not been fulfilled.

This prevents us from proceeding to round 3 until either:

* We finalize stem:[B_2] in round 2, or
* We receive an extra pre-commit vote for stem:[B_1] in round 1. This will make
it impossible to finalize stem:[B_2] in round 1, no matter to whom the remaining
pre-commits are going to be cast for (even with considering the possibility of
1/3 of voter equivocating) and therefore we have stem:[tt
"Best-Final-Candidate"(r) = B_1].

Both scenarios unblock the Algorithm
link_algo-grandpa-round++algo-grandpa-round]]:14 stem:[tt
"Last-Finalized-Block" >= tt "Best-Final-Candidate"(r - 1)] albeit in
different ways: the former with increasing the stem:[tt "Last-Finalized-Block"]
and the latter with decreasing stem:[tt "Best-Final-Candidate"(r - 1)].
====