[#chapter-crypto-algos]
=== Cryptographic Algorithms

[#sect-hash-functions]
==== Hash Functions

[#sect-blake2]
===== BLAKE2

BLAKE2 is a collection of cryptographic hash functions known for their high
speed. Their design closely resembles BLAKE which has been a finalist in the
SHA-3 competition.

Polkadot is using the Blake2b variant which is optimized for 64-bit platforms.
Unless otherwise specified, the Blake2b hash function with a 256-bit output is
used whenever Blake2b is invoked in this document. The detailed specification
and sample implementations of all variants of Blake2 hash functions can be found
in RFC 7693 cite:[saarinen_blake2_2015].

[#sect-randomness]
==== Randomness

NOTE: TBH

[#sect-vrf]
==== VRF

A Verifiable Random Function (VRF) is a mathematical operation that takes some
input and produces a random number using a secret key along with a proof of
authenticity that this random number was generated using the submitter's secret
key and the given input. The proof can be verified by any challenger to ensure
the random number generation is valid and has not been tampered with (for
example to the benfit of submitter).

In Polkadot, VRFs are used for the BABE block production lottery by
<<algo-block-production-lottery>>  and the parachain approval voting mechanism
(<<sect-approval-voting>>). The VRF uses mechanism similar to algorithms introduced
in the following papers:

* https://eprint.iacr.org/2017/099.pdf[Making NSEC5 Practical for DNSSEC] cite:[papadopoulos17]
* https://blog.cloudflare.com/privacy-pass-the-math/#dleqproofs[DLEQ Proofs]
* https://tools.ietf.org/id/draft-goldbe-vrf-01.html[Verifiable Random Functions (VRFs)] cite:[goldberg17]

It essentially generates a deterministic elliptic curve based Schnorr
signature as a verifiable random value. The elliptic curve group used in the VRF
function is the Ristretto group specified in:

* https://ristretto.group/

[#defn-vrf-proof]
.<<defn-vrf-proof, VRF Proof>>
====
The *VRF proof* proves the correctness for an associated VRF output. The VRF
proof, stem:[P], is a datastructure of the following format:

[stem]
++++
P = (C,S)\
S = (b_0, ... b_31)
++++

where stem:[C] is the challenge and stem:[S] is the 32-byte Schnorr poof. Both
are expressed as Curve25519 scalars as defined in Definition
<<defn-vrf-dleq-prove>>.
====

[#defn-vrf-dleq-prove]
.<<defn-vrf-dleq-prove, `DLEQ Prove`>>
====
The stem:["dleq_prove"(t, i)] function creates a proof for a given input, stem:[i],
based on the provided transcript, stem:[T].

First:

[stem]
++++
t_1 = "append"(t, "'proto-name'", "'DLEQProof'")\
t_2 = "append"(t_1, "'vrf:h'", i)
++++

Then the witness scalar is calculated, stem:[s_w], where stem:[w] is the
32-byte secret seed used for nonce generation in the context of sr25519.

[stem]
++++
t_3 = "meta-AD"(t_2, "'proving\\00'", "more=False")\
t_4 = "meta-AD"(t_3, w_l, "more=True")\
t_5 = "KEY"(t_4, w, "more=False")\
t_6 = "meta-AD"(t_5, "'rng'", "more=False")\
t_7 = "KEY"(t_6, r, "more=False")\
t_8 = "meta-AD"(t_7, e_(64), "more=False")\
(phi, s_w) = "PRF"(t_8, "more=False")
++++

where stem:[w_l] is length of the witness, encoded as a 32-bit little-endian
integer. stem:[r] is a 32-byte array containing the secret witness scalar.

[stem]
++++
l_1 = "append"(t_2, "'vrf:R=g^r'", s_w)\
l_2 = "append"(l_1, "'vrf:h^r'", s_i)\
l_3 = "append"(l_2, "'vrf:pk'", s_p)\
l_4 = "append"(l_3, "'vrf:h^sk'", "vrf"_o)
++++

where

* stem:[s_i] is the compressed Ristretto point of the scalar input.
* stem:[s_p] is the compressed Ristretto point of the public key.
* stem:[s_w] is the compressed Ristretto point of the wittness:

For the 64-byte challenge:

[stem]
++++
l_5 = "meta-AD"(l_4, "'prove'", "more=False")\
l_6 = "meta-AD"(l_5, e_(64), "more=True")\
C = "PRF"(l_6, "more=False")
++++

And the Schnorr proof:

[stem]
++++
S = s_w - (C * p)
++++

where stem:[p] is the secret key.
====

[#defn-vrf-dleq-verify]
.<<defn-vrf-dleq-verify, `DLEQ Verify`>>
====
The stem:["dleq_verify"(i, o, P, p_k)] function verifiers the VRF input,
stem:[i] against the output, stem:[o], with the associated proof
(<<defn-vrf-proof>>) and public key, stem:[p_k].

[stem]
++++
t_1 = "append"(t, "'proto-name'", "'DLEQProof'")\
t_2 = "append"(t_1, "'vrf:h'", s_i)\
t_3 = "append"(t_2, "'vrf:R=g^r'", R)\
t_4 = "append"(t_3, "'vrf:h^r'", H)\
t_5 = "append"(t_4, "'vrf:pk'", p_k)\
t_6 = "append"(t_5, "'vrf:h^sk'", o)
++++

where

* stem:[R] is calculated as:
+
[stem]
++++
R = C in P xx p_k + S in P + B
++++
+
where stem:[B] is the Ristretto basepoint.
* stem:[H] is calculated as:
+
[stem]
++++
H = C in P xx o + S in P xx i
++++

The challenge is valid if stem:[C in P] equals stem:[y]:

[stem]
++++
t_7 = "meta-AD"(t_6, "'prove'", "more=False")\
t_8 = "meta-AD"(t_7, e_(64), "more=True")\
y = "PRF"(t_8, "more=False")
++++
====

===== Transcript

A VRF transcript serves as a domain-specific separator of cryptographic
protocols and is represented as a mathematical object, as defined by Merlin,
which defines how that object is generated and encoded. The usage of the
transcript is implementation specific, such as for certain mechanisms in the
Availability & Validity chapter (<<chapter-anv>>), and is therefore described in
more detail in those protocols. The input value used to initiate the
transcript is referred to as a _context_ (<<defn-vrf-context>>).

[#defn-vrf-context]
.<<defn-vrf-context, VRF Contex>>
====
The *VRF context* is a constant byte array used to initiate VRF transcript. The VRF context is constant for all users of the VRF for the specific context for which the VRF function is used. Context prevents VRF values generated by the same nodes for other purposes to be reused for purposes not meant to. For example, the VRF context for BABE Production lottery defined in <<#sect-block-production-lottery>> is set to be "substrate-babe-vrf".
====

[#defn-vrf-transcript]
.<<defn-vrf-transcript, VRF Transcript>>
====
A *transcript*, or VRF transcript, is a STROBE object, stem:["obj"], as defined
in the STROBE documentation, respectively section
https://strobe.sourceforge.io/specs/#object["5. State of a STROBE object"].

[stem]
++++
"obj" = ("st","pos","pos"_("begin"),I_0)
++++

where:

* The duplex state, stem:["st"], is a 200-byte array created by the
https://keccak.team/keccak_specs_summary.html[keccak-f1600 sponge function] on
the https://strobe.sourceforge.io/specs/#object.initial[initial STROBE state].
Specifically, `R` is of value `166` and `X.Y.Z` is of value `1.0.2`.
* stem:["pos"] has the initial value of `0`.
* stem:["pos"_("begin")] has the initial value of `0`.
* stem:[I_0] has the initial value of `0`.

Then, the `meta-AD` operation (<<defn-strobe-operations>>) (where `more=False`) is
used to add the protocol label `Merlin v1.0` to stem:["obj"] followed by
_appending_ (<<sect-vrf-appending-messages>>) label `dom-step` and its
corresponding context, stem:[ctx], resulting in the final transcript, stem:[T].

[stem]
++++
t = "meta-AD"(obj, "'Merlin v1.0'", "False")\
T = "append"(t, "'dom-step'", "ctx")
++++

stem:["ctx"] serves as an arbitrary identifier/separator and its value is
defined by the protocol specification individually. This transcript is treated
just like a STROBE object, wherein any operations (<<defn-strobe-operations>>)
on it modify the values such as stem:["pos"] and stem:["pos"_("begin")].

Formally, when creating a transcript we refer to it as stem:["Transcript"(ctx)].
====

[#defn-strobe-operations]
.<<defn-strobe-operations, STROBE Operations>>
====
STROBE operations are described in the
https://strobe.sourceforge.io/specs/[STROBE specification], respectively section
https://strobe.sourceforge.io/specs/#ops["6. Strobe operations"]. Operations are
indicated by their corresponding bitfield, as described in section
https://strobe.sourceforge.io/specs/#ops.flags["6.2. Operations and flags"] and
implemented as described in section
https://strobe.sourceforge.io/specs/#ops.impl["7. Implementation of operations"]
====

[#sect-vrf-appending-messages]
====== Appending Messages

Appending messages, or "data", to the transcript (<<defn-vrf-transcript>>) first
requires `meta-AD` operations for a given label of the messages, including the
size of the message, followed by an `AD` operation on the message itself. The
size of the message is a 4-byte, little-endian encoded integer.

[stem]
++++
T_0 = "meta-AD"(T, l, "False")\
T_1 = "meta-AD"(T_0, m_l, "True")\
T_2 = "AD"(T_1, m, "False")
++++

where stem:[T] is the transcript (<<defn-vrf-transcript>>), stem:[l] is the
given label and stem:[m] the message, respectively stem:[m_l] representing its
size. stem:[T_2] is the resulting transcript with the appended data. STROBE
operations are described in <<defn-strobe-operations>>.

Formally, when appending a message we refer to it as stem:["append"(T, l, m)].

[#sect-cryptographic-keys]
==== Cryptographic Keys

Various types of keys are used in Polkadot to prove the identity of the actors
involved in the Polkadot Protocols. To improve the security of the users, each
key type has its own unique function and must be treated differently, as
described by this Section.

[#defn-account-key]
.<<defn-account-key, Account Key>>
====
*Account key stem:[(sk^a,pk^a)]* is a key pair of type of either of the schemes in the following
table:

.List of the public key scheme which can be used for an account key
|===
|Key Scheme| Description

|sr25519
|Schnorr signature on Ristretto compressed ed25519 points as implemented in TODO

|ed25519
|The ed25519 signature complies with cite:[josefsson_edwards-curve_2017] except for the verification process which adhere to Ed25519 Zebra variant specified in cite:[devalence-ed25519zebra_20]. In short, the signature point is not assumed to be on in the prime ordered subgroup group. As such, the verifier must explicitly clear the cofactor during the course of verifying the signature equation.

|secp256k1
|Only for outgoing transfer transactions.
|===

An account key can be used to sign transactions among other accounts and
balance-related functions. There are two prominent subcategories of account keys
namely "stash keys" and "controller keys", each being used for a different
function. Keys defined in <<defn-account-key>>, <<defn-stash-key>>
and <<defn-controller-key>> are created and managed by the user independent of
the Polkadot implementation. The user notifies the network about the used keys
by submitting a transaction, as defined in
<<sect-creating-controller-key>> and <<sect-certifying-keys>>
respectively.
====

[#defn-stash-key]
.<<defn-stash-key, Stash Key>>
====
The *Stash key* is a type of account key that holds funds bonded for staking
(described in <<sect-staking-funds>>) to a particular
controller key (defined in <<defn-controller-key>>). As a result, one may actively
participate with a stash key keeping the stash key offline in a secure location.
It can also be used to designate a Proxy account to vote in governance
proposals, as described in <<sect-creating-controller-key>>. The Stash
key holds the majority of the users’ funds and should neither be shared with
anyone, saved on an online device, nor used to submit extrinsics.
====

[#defn-controller-key]
.<<defn-controller-key, Controller Key>>
====
The *Controller key* is a type of account key that acts on behalf of the Stash
account. It signs transactions that make decisions regarding the nomination and
the validation of the other keys. It is a key that will be in direct control of
a user and should mostly be kept offline, used to submit manual extrinsics. It
sets preferences like payout account and commission, as described in
<<sect-controller-settings>>. If used for a validator, it certifies the
session keys, as described in <<sect-certifying-keys>>. It only needs
the required funds to pay transaction fees [TODO: key needing fund needs to be
defined].
====

[#defn-session-key]
.<<defn-session-key, Session Keys>>
====
*Session keys* are short-lived keys that are used to authenticate validator
operations. Session keys are generated by the Polkadot Host and should be
changed regularly due to security reasons. Nonetheless, no validity period is
enforced by the Polkadot protocol on session keys. Various types of keys used by
the Polkadot Host are presented in <<tabl-session-keys>>:

.List of key schemes which are used for session keys depending on the protocol
[#tabl-session-keys]
|===
|Protocol |Key scheme

|GRANDPA |ED25519
|BABE |SR25519
|I’m Online |SR25519
|Parachain |SR25519
|===

Session keys must be accessible by certain Polkadot Host APIs defined in
Appendix <<chap-host-api>>. Session keys are _not_ meant to control the
majority of the users’ funds and should only be used for their intended purpose.
[TODO: key managing fund need to be defined]
====

[#sect-staking-funds]
===== Holding and staking funds

NOTE: TBH

[#sect-creating-controller-key]
===== Creating a Controller key

NOTE: TBH

[#sect-designating-proxy]
===== Designating a proxy for voting

NOTE: TBH

[#sect-controller-settings]
===== Controller settings

NOTE: TBH

[#sect-certifying-keys]
===== Certifying keys

Due to security considerations and Runtime upgrades, the session keys are
supposed to  be changed regularly. As such, the new session keys need to be
certified by a controller key before putting them in use. The controller only
needs to create a certificate by signing a session public key and broadcasting
this certificate via an extrinsic. [TODO: spec the detail of the data structure
of the certificate etc.]
