[#sect-state-replication]
=== State Replication

Polkadot nodes replicate each other’s state by syncing the history of the
extrinsics. This, however, is only practical if a large set of transactions are
batched and synced at the time. The structure in which the transactions are
journaled and propagated is known as a block of extrinsics
(<<sect-block-format>>). Like any other replicated state machines, state
inconsistency can occure between Polkadot replicas.
<<sect-managing-multiple-states>> gives an overview of how a Polkadot Host
node manages multiple variants of the state.

[#sect-block-format]
==== Block Format
A Polkadot block consists a _block header_ (<<defn-block-header>>) and a _block
body_ (<<defn-block-body>>). The _block body_ in turn is made up out of
_extrinsics_ , which represent the generalization of the concept of
_transactions_. _Extrinsics_ can contain any set of external data the underlying
chain wishes to validate and track.

[#defn-block-header]
.<<defn-block-header,Block Header>>
====
The *header of block B*, stem:[H_h(B)], is a 5-tuple containing the following
elements:

* *parent_hash:* formally indicated as stem:[H_p], is the 32-byte Blake2b hash
(<<sect-blake2>>) of the SCALE encoded parent block header
(<<defn-block-header-hash>>).
* *number:* formally indicated as stem:[H_i], is an integer, which represents
the index of the current block in the chain. It is equal to the number of the
ancestor blocks. The genesis state has number 0.
* *state_root:* formally indicated as stem:[H_r], is the root of the Merkle trie,
whose leaves implement the storage for the system.
* *extrinsics_root:* is the field which is reserved for the Runtime to validate
the integrity of the extrinsics composing the block body. For example, it can
hold the root hash of the Merkle trie which stores an ordered list of the
extrinsics being validated in this block. The [.sans-serif]#extrinsics_root# is
set by the runtime and its value is opaque to the Polkadot Host. This element is
formally referred to as stem:[H_e].
* *digest:* this field is used to store any chain-specific auxiliary data, which
could help the light clients interact with the block without the need of
accessing the full storage as well as consensus-related data including the block
signature. This field is indicated as stem:[H_d] (<<defn-digest>>).
====

.Block Header
[kaitai#block_header]
++++
seq:
  - id: parent_hash
    size: 32
  - id: number
    type: b32
  - id: state_root
    size: 32
  - id: extrinsic_root
    size: 32
  - id: digest
    size: 32
++++

[#defn-digest]
.<<defn-digest,Header Digest>>
====
The header *digest* of block stem:[B] formally referred to by stem:[H_d (B)] is
an array of *digest items* stem:[H_d^i]’s, known as digest items of varying data
type (<<defn-varrying-data-type>>) such that:

[stem]
++++
H_d(B) := H_d^1, ..., H_d^n
++++

where each digest item can hold one of the following type identifiers:

[stem]
++++
H_d^i = {
	(0, to, (E_"id", m)),
	(4, to, (E_"id", "CM")),
	(5, to, (E_"id", S_B)),
	(6, to, (E_"id", P)),
	(8, to, (E_id))
:}
++++

[horizontal]
asciimath:[E_"id" = 0]:: *Non-System* digest, which is opaque to the native code. stem:[m] is an opaque byte array.
asciimath:[E_"id" = 4]:: *Consensus Message*, contains messages from the Runtime to the consensus engine stem:["CM"] (<<defn-consensus-message-digest>>).
asciimath:[E_"id" = 5]:: *Seal*, is produced by the consensus engine and proving
the authorship of the block producer. Respectively, stem:[S_B] is the
signature (<<defn-block-signature>>) of the block producer. In particular, the
Seal digest item must be the last item in the digest array and must be stripped
off by the Polkadot Host before the block is submitted to any Runtime function
including for validation. The Seal must be added back to the digest afterward.
asciimath:[E_"id" = 6]:: *Pre-Runtime* digest, contains the BABE Pre-Digest item
stem:[P] (<<defn-babe-header>>).
asciimath:[E_"id" = 8]:: *Runtime Environment Updated* digest, indicates that
changes regarding the Runtime code or heap pages (<<sect-memory-management>>)
occurred. No additional data is provided.
====

.Block Header
[kaitai#digest]
++++
seq:
  - id: digest_ty_id
    type: u1
    enum: digest_ty
  - id: digest_item
    type:
      switch-on: digest_ty_id
      cases:
        'digest_ty::non_system': u1
        'digest_ty::consensus_message': u1
        'digest_ty::seal': u1
        'digest_ty::pre_runtime': u1
        'digest_ty::runtime_env_updated': u1
enums:
    digest_ty:
        0: non_system
        4: consensus_message
        5: seal
        6: pre_runtime
        8: runtime_env_updated
++++

[#defn-block-header-hash]
.<<defn-block-header-hash,Header Hash>>
====
The *block header hash of block stem:[B]*, stem:[H_h(B)], is the hash of the
header of block stem:[B] encoded by simple codec:

[stem]
++++
H_h(B) := "Blake2b"("Enc"_(SC)("Head"(B)))
++++
====

[#sect-justified-block-header]
===== Justified Block Header

The Justified Block Header is provided by the consensus engine and
presented to the Polkadot Host, for the block to be appended to the
blockchain. It contains the following parts:

* *block_header* the complete block header (<<defn-block-header>>) and denoted
by stem:["Head"(B)].
* *justification*: as defined by the consensus specification indicated by
stem:["Just"(B)] as defined in <<defn-grandpa-justification>>.
* *authority Ids*: This is the list of the Ids of authorities, which have voted
for the block to be stored and is formally referred to as stem:[A(B)]. An
authority Id is 256-bit.

[#defn-block-body]
.<<defn-block-body,Block Body>>
====
The block body consists of an sequence of extrinsics, each encoded as a byte
array. The content of an extrinsic is completely opaque to the Polkadot Host. As
such, from the point of the Polkadot Host, and is simply a SCALE encoded array
of byte arrays. The *body of Block* stem:[B] represented as stem:["Body"(B)] is
defined to be:

[stem]
++++
"Body"(B) := "Enc"_(SC)(E_1,...,E_n)
++++

Where each stem:[E_i in bbb B] is a SCALE encoded extrinsic.
====

[#sect-block-validation]
==== Importing and Validating Block

Block validation is the process by which a node asserts that a block is fit to
be added to the blockchain. This means that the block is consistent with the
current state of the system and transitions to a new valid state.

New blocks can be received by the Polkadot Host via other peers
(<<sect-msg-block-request>>) or from the Host’s own consensus engine
(<<sect-block-production>>). Both the Runtime and the Polkadot Host then need to
work together to assure block validity. A block is deemed valid if the block
author had authorship rights for the slot in which the block was produce as well
as if the transactions in the block constitute a valid transition of states. The
former criterion is validated by the Polkadot Host according to the block
production consensus protocol. The latter can be verified by the Polkadot Host
invoking entry into the Runtime as (<<sect-rte-core-execute-block>>) as a part
of the validation process. Any state changes created by this function on
successful execution are persisted.

The Polkadot Host implements <<algo-import-and-validate-block>> to assure the
validity of the block.

****
.Import-and-Validate-Block
[pseudocode#algo-import-and-validate-block]
++++
\require $B, \text{Just}(B)$

\state \textsc{Set-Storage-State-At}$(P(B))$

\if{$\text{Just}(B) \neq \emptyset$}

    \state \textsc{Verify-Block-Justification}$(B, Just(B))$

    \if{$B~\textbf{is}~\text{Finalized}~\textbf{and}~P(B)~\textbf{is not}~\text{Finalized}$}

        \state \textsc{Mark-as-Final}$(P(B))$

     \endif

\endif

\if{$H_p(B) \notin PBT$}

    \return

\endif

\state \textsc{Verify-Authorship-Right}$(Head(B))$

\state $B \leftarrow$ \textsc{Remove-Seal}$(B)$

\state $R \leftarrow$ \textsc{Call-Runtime-Entry}$\left(\texttt{Core\_execute\_block}, B \right)$

\state $B \leftarrow$ \textsc{Add-Seal}$(B)$

\if{$R =$ \textsc{True}}

    \state \textsc{Persist-State}$()$

\endif
++++

where::
* stem:["Remove-Seal"] removes the Seal digest from the block (<<defn-digest>>)
before submitting it to the Runtime.
* stem:["Add-Seal"] adds the Seal digest back to the block (<<defn-digest>>) for
later propagation.
* stem:["Persist-State"] implies the persistence of any state changes created by
stem:[tt "Core_execute_block"] (<<sect-rte-core-execute-block>>) on successful
execution.
* stem:["PBT"] is the pruned block tree (<<defn-block-tree>>).
* stem:["Verify-Authorship-Right"] is part of the block production consensus
protocol and is described in <<algo-verify-authorship-right>>.
* _Finalized block_ and _finality_ are defined in <<sect-finality>>.
****

[#sect-managing-multiple-states]
==== Managaing Multiple Variants of State

Unless a node is committed to only update its state according to the finalized
block (<<defn-finalized-block>>), it is inevitable for the node to store
multiple variants of the state (one for each block). This is, for example,
necessary for nodes participating in the block production and finalization.

While the state trie structure (<<sect-state-storage-trie-structure>>)
facilitates and optimizes storing and switching between multiple variants of the
state storage, the Polkadot Host does not specify how a node is required to
accomplish this task. Instead, the Polkadot Host is required to implement
stem:["Set-State-At"] (<<defn-set-state-at>>):

[#defn-set-state-at]
.<<defn-set-state-at,Set State At Block>>
====
The function:

[stem]
++++
"Set-State-At"(B)
++++

in which stem:[B] is a block in the block tree (<<defn-block-tree>>), sets the
content of state storage equal to the resulting state of executing all
extrinsics contained in the branch of the block tree from genesis till block B
including those recorded in Block stem:[B].

For the definition of the state storage see <<sect-state-storage>>.
====
