+++
title = "Child Storage Trie"
date = "2019-02-28"
menu = "main"
weight = "2"
+++

[#sect-child-storages]
== Child Storage

As clarified in <<sect-state-storage>>, the Polkadot state storage implements a
hash table for inserting and reading key-value entries. The child storage works
the same way but is stored in a separate and isolated environment. Entries in
the child storage are not directly accessible via querying the main state
storage.

The Polkadot Host supports as many child storages as required by Runtime
and identifies each separate child storage by its unique identifying
key. Child storages are usually used in situations where Runtime deals
with multiple instances of a certain type of objects such as Parachains
or Smart Contracts. In such cases, the execution of the Runtime entry
might result in generating repeated keys across multiple instances of
certain objects. Even with repeated keys, all such instances of
key-value pairs must be able to be stored within the Polkadot state.

In these situations, the child storage can be used to provide the isolation
necessary to prevent any undesired interference between the state of separated
instances. The Polkadot Host makes no assumptions about how child storages are
used, but provides the functionality for it via the Host API
(<<sect-child-storage-api>>).

[#sect-child-trie-structure]
=== Child Tries

The child trie specification is the same as the one described in
<<sect-state-storage-trie-structure>>. Child tries have their own isolated
environment. Nonetheless, the main Polkadot state trie depends on them by
storing a node (stem:[K_N, V_N]) which corresponds to an individual child trie.
Here, stem:[K_N] is the child storage key associated to the child trie, and
stem:[V_N] is the Merkle value of its corresponding child trie computed
according to the procedure described in <<sect-merkl-proof>>.

The Polkadot Host API (<<sect-child-storage-api>>) allows the Runtime to provide
the key stem:[K_N] in order to identify the child trie, followed by a second key
in order to identify the value within that child trie. Every time a child trie
is modified, the Merkle proof stem:[V_N] of the child trie stored in the
Polkadot state must be updated first. After that, the final Merkle proof of the
Polkadot state can be computed. This mechanism provides a proof of the full
Polkadot state including all its child states.
