=== Storage

Interface for accessing the storage from within the runtime.

[[sect-storage-set]]
==== 

Sets the value under a given key into storage.

===== Version 1 - Prototype

*Arguments*:

* : a pointer-size as defined in Definition
link:#defn-runtime-pointer-size[[defn-runtime-pointer-size]] containing
the key.
* : a pointer-size as defined in Definition
link:#defn-runtime-pointer-size[[defn-runtime-pointer-size]] containing
the value.

[[section]]
==== 

Retrieves the value associated with the given key from storage.

===== Version 1 - Prototype

*Arguments*:

* : a pointer-size as defined in Definition
link:#defn-runtime-pointer-size[[defn-runtime-pointer-size]] containing
the key.
* : a pointer-size as defined in Definition
link:#defn-runtime-pointer-size[[defn-runtime-pointer-size]] returning
the SCALE encoded as defined in Definition
link:#defn-option-type[[defn-option-type]] containing the value.

[[section-1]]
==== 

Gets the given key from storage, placing the value into a buffer and
returning the number of bytes that the entry in storage has beyond the
offset.

===== Version 1 - Prototype

*Arguments*:

* : a pointer-size as defined in Definition
link:#defn-runtime-pointer-size[[defn-runtime-pointer-size]] containing
the key.
* : a pointer-size as defined in Definition
link:#defn-runtime-pointer-size[[defn-runtime-pointer-size]] containing
the buffer to which the value will be written to. This function will
never write more then the length of the buffer, even if the value’s
length is bigger.
* : an u32 integer containing the offset beyond the value should be read
from.
* : a pointer-size (Definition
link:#defn-runtime-pointer-size[[defn-runtime-pointer-size]]) pointing
to a SCALE encoded (Definition
link:#defn-option-type[[defn-option-type]]) containing an unsinged
32-bit interger representing the number of bytes left at supplied .
Returns if the entry does not exists.

[[section-2]]
==== 

Clears the storage of the given key and its value.

===== Version 1 - Prototype

*Arguments*:

* : a pointer-size as defined in Definition
link:#defn-runtime-pointer-size[[defn-runtime-pointer-size]] containing
the key.

[[section-3]]
==== 

Checks whether the given key exists in storage.

===== Version 1 - Prototype

*Arguments*:

* : a pointer-size as defined in Definition
link:#defn-runtime-pointer-size[[defn-runtime-pointer-size]] containing
the key.
* : an i32 integer value equal to if the key exists or a value equal to
if otherwise.

[[section-4]]
==== 

Clear the storage of each key/value pair where the key starts with the
given prefix.

===== Version 1 - Prototype

*Arguments*:

* : a pointer-size as defined in Definition
link:#defn-runtime-pointer-size[[defn-runtime-pointer-size]] containing
the prefix.

[[section-5]]
==== 

Append the SCALE encoded value to a SCALE encoded sequence (Definition
link:#defn-scale-list[[defn-scale-list]]) at the given key. This
function assumes that the existing storage item is either empty or a
SCALE encoded sequence and that the value to append is also SCALE
encoded and of the same type as the items in the existing sequence.

 

To improve performance, this function is allowed to skip decoding the
entire SCALE encoded sequence and instead can just append the new item
to the end of the existing data and increment the length prefix
latexmath:[$\ensuremath{\operatorname{Enc}}^{\ensuremath{\operatorname{Len}}}_{\ensuremath{\operatorname{SC}}}$].

 

*Warning*: If the storage item does not exist or is not SCALE encoded,
the storage item will be set to the specified value, represented as a
SCALE encoded byte array.

===== Version 1 - Prototype

*Arguments*:

* : a pointer-size as defined in Definition
link:#defn-runtime-pointer-size[[defn-runtime-pointer-size]] containing
the key.
* : a pointer-size as defined in Definition
link:#defn-runtime-pointer-size[[defn-runtime-pointer-size]] containing
the value to be appended.

[[section-6]]
==== 

Compute the storage root.

===== Version 1 - Prototype

*Arguments*:

* : a 32-bit pointer to the buffer containing the 256-bit Blake2 storage
root.

[[sect-ext-storage-changes-root]]
==== 

Compute the root of the Changes Trie as described in Section
link:#sect-changes-trie[3.3.4]. The parent hash is a SCALE encoded block
hash.

===== Version 1 - Prototype

*Arguments*:

* **: a pointer-size as defined in Definition
link:#defn-runtime-pointer-size[[defn-runtime-pointer-size]] indicating
the SCALE encoded block hash.
* : a 32-bit pointer to the buffer containing the 256-bit Blake2 changes
root.

[[section-7]]
==== 

Get the next key in storage after the given one in lexicographic order
(Definition
link:#defn-lexicographic-ordering[[defn-lexicographic-ordering]]). The
key provided to this function may or may not exist in storage.

===== Version 1 - Prototype

*Arguments*:

* **: a pointer-size as defined in Definition
link:#defn-runtime-pointer-size[[defn-runtime-pointer-size]] indicating
the key.
* : a pointer-size as defined in Definition
link:#defn-runtime-pointer-size[[defn-runtime-pointer-size]] indicating
the SCALE encoded as defined in Definition
link:#defn-option-type[[defn-option-type]] containing the next key in
lexicographic order.

[[sect-ext-storage-start-transaction]]
==== 

Start a new nested transaction. This allows to either commit or roll
back all changes that are made after this call. For every transaction
there must be a matching call to either
(link:#sect-ext-storage-rollback-transaction[12.1.12]) or
(link:#sect-ext-storage-commit-transaction[12.1.13]). This is also
effective for all values manipulated using the child storage API
(link:#sect-child-storage-api[12.2]).

 

*Warning*: This is a low level API that is potentially dangerous as it
can easily result in unbalanced transactions. Runtimes should use high
level storage abstractions.

===== Version 1 - Prototype

 

*Arguments*:

* None.

[[sect-ext-storage-rollback-transaction]]
==== 

Rollback the last transaction started by
(link:#sect-ext-storage-start-transaction[12.1.11]). Any changes made
during that transaction are discarded.

 

*Warning*: Panics if there is no open transaction (
(link:#sect-ext-storage-start-transaction[12.1.11]) was not called)

===== Version 1 - Prototype

 

*Arguments*:

* None.

[[sect-ext-storage-commit-transaction]]
==== 

Commit the last transaction started by
(link:#sect-ext-storage-start-transaction[12.1.11]). Any changes made
during that transaction are committed to the main state.

 

*Warning*: Panics if there is no open transaction (
(link:#sect-ext-storage-start-transaction[12.1.11]) was not called)

===== Version 1 - Prototype

 

*Arguments*:

* None.