[#sect-offchain-api]
=== Offchain

The Offchain Workers allow the execution of long-running and possibly
non-deterministic tasks (e.g. web requests, encryption/decryption and signing of
data, random number generation, CPU-intensive computations,
enumeration/aggregation of on-chain data, etc.) which could otherwise require
longer than the block execution time. Offchain Workers have their own execution
environment. This separation of concerns is to make sure that the block
production is not impacted by the long-running tasks.

All data and results generated by Offchain workers are unique per node and
nondeterministic. Information can be propagated to other nodes by submitting a
transaction that should be included in the next block. As Offchain workers runs
on their own execution environment they have access to their own separate
storage. There are two different types of storage available which are defined in
Definitions F.1 and F.2.

[#defn-offchain-persistent-storage]
==== Persisted Storage
****
*Persistent storage* is non-revertible and not fork-aware. It means that any value
set by the offchain worker is persisted even if that block (at which the worker
is called) is reverted as non-canonical (meaning that the block was surpassed by
a longer chain). The value is available for the worker that is re-run at the new
(different block with the same block number) and future blocks. This storage can
be used by offchain workers to handle forks and coordinate offchain workers
running on different forks.
****

[#defn-offchain-local-storage]
==== Local Storage
****
*Local storage* is revertible and fork-aware. It means that any value set by the
offchain worker triggered at a certain block is reverted if that block is
reverted as non-canonical. The value is NOT available for the worker that is
re-run at the next or any future blocks.
****

==== HTTP Status Code
****
*HTTP status codes* that can get returned by certain Offchain HTTP functions.

* `0`: the specified request identifier is invalid.
* `10`: the deadline for the started request was reached.
* `20`: an error has occurred during the request, e.g. a timeout or the remote
server has closed the connection. On returning this error code, the request is
considered destroyed and must be reconstructed again.
* `100`-`999`: the request has finished with the given HTTP status code.
****

==== HTTP Error
****
HTTP error, stem:[E], is a varying data type as defined in Definition ? and
specifies the error types of certain HTTP functions. Following values are
possible:

[stem]
++++
E = {(0,"The deadile was reached"),(1,"There was an IO error while processing the request"),(2,"The Id of the request is invalid"):}
++++
****

==== `ext_offchain_is_validator`

Check whether the local node is a potential validator. Even if this function
returns _1_, it does not mean that any keys are configured or that the validator
is registered in the chain.

===== Version 1 - Prototype
----
(func $ext_offchain_is_validator_version_1 (return i32))
----

Arguments::

* `return`: a i32 integer which is equal to _1_ if the local node is a potential
validator or a integer equal to _0_ if it is not.

[#sect-ext-offchain-submit-transaction]
==== `ext_offchain_submit_transaction`

Given a SCALE encoded extrinsic, this function submits the extrinsic to the
Host's transaction pool, ready to be propagated to remote peers. This process is
critical for issuing the ImOnline message [TODO: refer].

===== Version 1 - Prototype
----
(func $ext_offchain_submit_transaction_version_1
	(param $data i64) (return i64))
----

Arguments::

* `data`: a pointer-size as defined in Definition D.3 indicating the byte array
storing the encoded extrinsic.
* `return`: a pointer-size as defined in Definition D.3 indicating the SCALE
encoded Result as defined in Definition ?. Neither on success or failure is
there any additional data provided. The cause of a failure is implementation
specific.

==== `ext_offchain_network_state`

Returns the SCALE encoded, opaque information about the local node's network state.

[#defn-opaque-network-state]
===== Opaque Network State
****
The *Opaque network state structure, stem:[S], is a SCALE encoded blob holding
information about the the _libp2p PeerId_, stem:[P_("id")], of the local node
and a list of _libp2p Multiaddresses_, stem:[(M_0, ... M_n)], the node knows it
can be reached at:

[stem]
++++
S = (P_("id"),(M_0, ... M_n))
++++

where

[stem]
++++
P_("id") = (b_0,... b_n)
M = (b_0, ... b_n)
++++

The information contained in this structure is naturally opaque to the caller of
this function.
****

===== Version 1 - Prototype
----
(func $ext_offchain_network_state_version_1 (result i64))
----

Arguments::

* `result`: a pointer-size as defined in Definition D.3 indicating the SCALE
encoded `Result` as defined in Definition ?. On success it contains the
_Opaque network state_ structure as defined in Definition D.12. On failure, an
empty value is yielded where its cause is implementation specific.

==== `ext_offchain_timestamp`

Returns the current timestamp.

===== Version 1 - Prototype
----
(func $ext_offchain_timestamp_version_1 (result u64))
----

Arguments::

* `result`: an u64 integer indicating the current UNIX timestamp as defined in Definition ?.

==== `ext_offchain_sleep_until`

Pause the execution until the `deadline` is reached.

===== Version 1 - Prototype
----
(func $ext_offchain_sleep_until_version_1)
----

Arguments::

* `deadline`: an u64 integer specifying the UNIX timestamp as defined in
Definition ?.

==== `ext_offchain_random_seed`

Generates a random seed. This is a truly random non deterministic seed generated
by the host environment.

===== Version 1 - Prototype
----
(func $ext_offchain_random_seed_version_1 (result i32))
----

==== `ext_offchain_local_storage_set`

Sets a value in the local storage. This storage is not part of the consensus,
it's only accessible by the offchain worker tasks running on the same machine
and is persisted between runs.

===== Version 1 - Prototype
----
(func $ext_offchain_local_storage_set_version_1
	(param $kind i32) (param $key i64) (param $value i64))
----

Arguments::

* `kind`: an i32 integer indicating the storage kind. A value equal to _1_ is used
for a persistent storage as defined in Definition D.8 and a value equal to 2 for
local storage as defined in Definition D.9.
∗ `key`: a pointer-size as defined in Definition D.3 indicating the key.
∗ `value`: a pointer-size as defined in Definition D.3 indicating the value.

==== `ext_offchain_local_storage_clear`

Remove a value from the local storage.

===== Version 1 - Prototype
----
(func $ext_offchain_local_storage_clear_version_1
	(param $kind i32) (param $key i64))
----

Arguments::

∗ `kind`: an i32 integer indicating the storage kind. A value equal to _1_ is used
for a persistent storage as defined in Definition D.8 and a value equal to 2 for
local storage as defined in Definition D.9.
∗ `key`: a pointer-size as defined in Definition D.3 indicating the key.

==== `ext_offchain_local_storage_compare_and_set`

Sets a new value in the local storage if the condition matches the current value.

===== Version 1 - Prototype
----
(fund $ext_offchain_local_storage_compare_and_set_version_1
	(param $kind i32) (param $key i64) (param $old_value i64)
	(param $new_value i64) (result i32))
----

Arguments::

* `kind`: an i32 integer indicating the storage kind. A value equal to _1_ is used
for a persistent storage as defined in Definition D.8 and a value equal to 2 for
local storage as defined in Definition D.9.
∗ `key`: a pointer-size as defined in Definition D.3 indicating the key.
∗ `old_value`: a pointer-size as defined in Definition D.3 indicating the SCALE
encoded Option as defined in Definition ? containing the old key.
∗ `new_value`: a pointer-size as defined in Definition D.3 indicating the new value.
∗ `result`: an i32 integer equal to _1_ if the new value has been set or a value equal to _0_ if otherwise.

==== `ext_offchain_local_storage_get`

Gets a value from the local storage.

===== Version 1 - Prototype
----
(func $ext_offchain_local_storage_get_version_1
	(param $kind i32) (param $key i64) (result i64))
----

Arguments::

* `kind`: an i32 integer indicating the storage kind. A value equal to _1_ is used
for a persistent storage as defined in Definition D.8 and a value equal to 2 for
local storage as defined in Definition D.9.
∗ `key`: a pointer-size as defined in Definition D.3 indicating the key.
∗ `result`: a pointer-size as defined in Definition D.3 indicating the SCALE
encoded Option as defined in Definition ? containing the value or the
corresponding key.

==== `ext_offchain_http_request_start`

Initiates a HTTP request given by the HTTP method and the URL. Returns the Id of
a newly started request.

===== Version 1 - Prototype
----
(func $ext_offchain_http_request_start_version_1
  (param $method i64) (param $uri i64) (param $meta i64) (result i64))
----

Arguments::

∗ `method`: a pointer-size as defined in Definition D.3 indicating the HTTP
method. Possible values are “GET” and “POST”.
∗ `uri`: a pointer-size as defined in Definition D.3 indicating the URI.
∗ `meta`: a future-reserved field containing additional, SCALE encoded parameters. Currently, an empty array should be passed.
∗ `result`: a pointer-size as defined in Definition D.3 indicating the SCALE
encoded Result as defined in Definition ? containing the i16 ID of the newly
started request. On failure no additionally data is provided. The cause of
failure is implementation specific.

==== `ext_offchain_http_request_add_header`

Append header to the request. Returns an error if the request identifier is
invalid, `http_response_wait` has already been called on the specified request
identifier, the deadline is reached or an I/O error has happened (e.g. the
remote has closed the connection).

===== Version 1 - Prototype
----
(func $ext_offchain_http_request_add_header_version_1
	(param $request_id i32) (param $name i64) (param $value i64) (result i64))
----

Arguments::

• `request_id`: an i32 integer indicating the ID of the started request.
• `name`: a pointer-size as defined in Definition D.3 indicating the HTTP header name.
• `value`: a pointer-size as defined in Definition D.3 indicating the HTTP header value.
• `result`: a pointer-size as defined in Definition D.3 indicating the SCALE
encoded Result as defined in Definition ?. Neither on success or failure is
there any additional data provided. The cause of failure is implemenation
specific.

==== `ext_offchain_http_request_write_body`

Writes a chunk of the request body. Returns a non-zero value in case the
deadline is reached or the chunk could not be written.

===== Version 1 - Prototype
----
(func $ext_offchain_http_request_write_body_version_1
	(param $request_id i32) (param $chunk i64) (param $deadline i64) (result i64))
----

Arguments::

∗ `request_id`: an i32 integer indicating the ID of the started request.
∗ `chunk`: a pointer-size as defined in Definition D.3 indicating the chunk of
bytes. Writing an empty chunk finalizes the request.
∗ `deadline`: a pointer-size as defined in Definition D.3 indicating the SCALE
encoded Option as defined in Definition ? containing the UNIX timestamp as
defined in Definition ?. Passing None blocks indefinitely.
∗ `result`: a pointer-size as defined in Definition D.3 indicating the SCALE
encoded Result as defined Definition ?. On success, no additional data is
provided. On error it contains the HTTP error type as defined in Definition
D.11.

==== `ext_offchain_http_response_wait`

Returns an array of request statuses (the length is the same as IDs). Note that
if deadline is not provided the method will block indefinitely, otherwise
unready responses will produce DeadlineReached status.

===== Version 1 - Prototype
----
(func $ext_offchain_http_response_wait_version_1
	(param $ids i64) (param $deadline i64) (result i64))
----

Arguments::

∗ `ids`: a pointer-size as defined in Definition D.3 indicating the SCALE
encoded array of started request IDs.
∗ `deadline`: a pointer-size as defined in Definition D.3 indicating the SCALE
encoded Option as defined in Definition ? containing the UNIX timestamp as
defined in Definition 1.10. Passing None blocks indefinitely.
∗ `result`: a pointer-size as defined in Definition D.3 indicating the SCALE
encoded array of request statuses as defined in Definition D.10.

==== `ext_offchain_http_response_headers`

Read all HTTP response headers. Returns an array of key/value pairs. Response
headers must be read before the response body.

===== Version 1 - Prototype
----
(func $ext_offchain_http_response_headers_version_1
	(param $request_id i32) (result i64))
----

Arguments::

∗ `request_id`: an i32 integer indicating the ID of the started request.
∗ `result`: a pointer-size as defined in Definition D.3 indicating a SCALE encoded array of key/value pairs.

==== `ext_offchain_http_response_read_body`

Reads a chunk of body response to the given buffer. Returns the number of bytes
written or an error in case a deadline is reached or the server closed the
connection. If 0 is returned it means that the response has been fully consumed
and the request_id is now invalid. This implies that response headers must be
read before draining the body.

===== Version 1 - Prototype
----
(func $ext_offchain_http_response_read_body_version_1
	(param $request_id i32) (param $buffer i64) (param $deadline i64) (result i64))
----

Arguments::

∗ `request_id`: an i32 integer indicating the ID of the started request.
∗ buffer: a pointer-size as defined in Definition D.3 indicating the buffer
where the body gets written to.
∗ `deadline`: a pointer-size as defined in Definition D.3 indicating the SCALE
encoded Option as defined in Definition ? containing the UNIX timestamp as
defined in Definition ?. Passing None will block indefinitely.
∗ `result`: a pointer-size as defined in Definition D.3 indicating the SCALE
encoded Result as defined in Definition ?. On success it contains an i32 integer
specifying the number of bytes written or a HTTP error type as defined in
Definition D.11 on faiure.

==== `ext_offchain_set_authorized_nodes`

Set the authorized nodes which are allowed to connect to the local node. This
function is primarily used for private blockchains [TODO: shouldn't we give a context
of what private blockchain means] and is not necessarily required for the public
and open Polkadot protocol.

===== Version 1 - Prototype
----
(func $ext_offchain_set_authorized_nodes_version_1
	(param $nodes i64) (param $authorized_only i32)
----

Arguments::

∗ `nodes`: a pointer-size as defined in Definition D.3 indicating the buffer of the SCALE encoded array of libp2p PeerId's. Invalid PeerId's are silently ignored.
∗ `authorized_only`: If set to 1, then only the authorized nodes are allowed to connect to the local node (whitelist). All other nodes are rejected. If set to 0, then no such restriction is placed.
