[#sect-runtime-core-module]
==== Core Module (Version 3)

[#defn-rt-core-version]
===== `Core_version`

Returns the version identifiers of the Runtime. This function can be used by the Polkadot Host implementation when it seems appropriate, such as for the JSON-RPC API as described in <<sect-json-rpc-api>>.

Arguments::
* None

Return::
* A datastructure of the following format:
+
.Details of the version that the data type returns from the Runtime function.
[cols="<1,<1,<2",options="header"]
|===
|Name |Type |Description

| `spec_name` | String | Runtime identifier

| `impl_name` | String | Name of the implementation (e.g. C++)

| `authoring_version` | Unsigned 32-bit integer | Version of the authorship interface

| `spec_version` | Unsigned 32-bit integer | Version of the Runtime specification

| `impl_version` | Unsigned 32-bit integer | Version of the Runtime implementation

| `apis` | ApiVersions (<<defn-rt-apisvec>>) | List of supported APIs along with their version

| `transaction_version` | Unsigned 32-bit integer | Version of the transaction format
|===

.ApiVersions
[#defn-rt-apisvec]
====
*ApiVersions* is a specialized type for the (<<defn-rt-core-version>>) function entry. It represents an array of tuples, where the first value of the tuple is an array of 8-bytes containing the Blake2b hash of the API name. The second value of the tuple is the version number of the corresponding API.

[latexmath]
++++
\begin{aligned}
      \mathrm{ApiVersions} :=& (T_0, \ldots, T_n)\\
      T :=& ((b_0, \ldots, b_7), \mathrm{UINT32})
\end{aligned}
++++
====

Requires `Core_initialize_block` to be called beforehand.

[#sect-rte-core-execute-block]
===== `Core_execute_block`

This function executes a full block and all its extrinsics and updates the state accordingly. Additionally, some integrity checks are executed such as validating if the parent hash is correct and that the transaction root represents the transactions. Internally, this function performs an operation similar to the process described in <<algo-build-block>>, by calling `Core_initialize_block`,`BlockBuilder_apply_extrinsics` and `BlockBuilder_finalize_block`.

This function should be called when a fully complete block is available
that is not actively being built on, such as blocks received from other
peers. State changes resulted from calling this function are usually
meant to persist when the block is imported successfully.

Additionally, the seal digest in the block header, as described in  <<defn-digest>>, must be removed by the
Polkadot host before submitting the block.

Arguments::
* A block represented as a tuple consisting of a block header, as described in <<defn-block-header>>, and the block body, as described in <<defn-block-body>>.

Return::
* None.

[#sect-rte-core-initialize-block]
===== `Core_initialize_block`

Sets up the environment required for building a new block as described in <<algo-build-block>>.


Arguments::
* The header of the new block as defined in <<defn-block-header>>. The values latexmath:[H_r], latexmath:[H_e] and latexmath:[H_d] are left empty.

Return::
* None.
