[#sect-block-production]
=== Block Production

The Polkadot Host uses BABE protocol for block production. It is designed based
on Ouroboros praos . BABE execution happens in sequential non-overlapping phases
known as an *_epoch_*. Each epoch on its turn is divided into a predefined
number of slots. All slots in each epoch are sequentially indexed starting from
0. At the beginning of each epoch, the BABE node needs to run Algorithm as
defined in TODO xref:05_consensus/block_production.adoc#algo-block-production-lottery[Algo.] to find out in which slots it
should produce a block and gossip to the other block producers. In turn, the
block producer node should keep a copy of the block tree and grow it as it
receives valid blocks from other block producers. A block producer prunes the
tree in parallel by eliminating branches that do not include the most recent
finalized blocks (xref:01_background/definitions.adoc#defn-pruned-tree[Def.]).

==== Preliminaries

===== Block Producer
A *block producer*, noted by stem:[cc P_j], is a node running the Polkadot
Host which is authorized to keep a transaction queue and which it gets a turn in
producing blocks.

===== Block Authoring Session Key Pair
*Block authoring session key pair* stem:[(sk_j^s,pk_j^s)] is an SR25519 key pair
which the block producer stem:[cc P_j] signs by their account key
(xref:01_crypto-algos.adoc#defn-account-key[Def.]) and is used to sign the produced block as well as to
compute its lottery values in Algorithm as defined in TODO
xref:05_consensus/block_production.adoc#algo-block-production-lottery[Algo.].

[#defn-epoch-slot]
===== Epoch
****
A block production *epoch*, formally referred to as stem:[cc E], is a
period with a pre-known starting time and fixed-length during which the set of
block producers stays constant. Epochs are indexed sequentially, and we refer to
the stem:[n^(th)] epoch since genesis by stem:[cc E_n]. Each epoch is divided
into equal-length periods known as block production *slots*, sequentially
indexed in each epoch. The index of each slot is called a *slot number*. The
equal length duration of each slot is called the *slot duration* and indicated
by stem:[cc T]. Each slot is awarded to a subset of block producers during
which they are allowed to generate a block.

IMPORTANT: Substrate refers to an epoch as "session" in some places, however,
epoch should be the preferred and official name for these periods.
****

[#note-slot]
===== Slot duration
****
We refer to the number of slots in epoch stem:[cc E_n] by stem:[sc_n].
stem:[sc_n] is set to the `duration` field in the returned data from the call of
the Runtime entry `BabeApi_configuration` (xref:modules/babe.adoc#sect-rte-babeapi-epoch[Sect.]) at
genesis. For a given block stem:[B], we use the notation *latexmath:[$s_B$]* to
refer to the slot during which stem:[B] has been produced. Conversely, for slot
stem:[s], stem:[cc B_c] is the set of Blocks generated at slot stem:[s].

xref:05_consensus/block_production.adoc#defn-epoch-subchain[Def.] provides an iterator over the blocks produced during a
specific epoch.
****

[#defn-epoch-subchain]
===== Epoch Subchain
****
By stem:["SubChain"(cc E_n]) for epoch stem:[cc E_n], we refer to the path
graph of stem:[BT] containing all the blocks generated during the slots of epoch
stem:[cc E_n]. When there is more than one block generated at a slot, we
choose the one which is also on stem:["Longest-Chain"(BT)].
****

===== Equivocation
****
A block producer *equivocates* if they produce more than one block at the same
slot. The proof of equivocation are the given distinct headers that were signed
by the validator and which include the slot number.

The Polkadot Host must detect equivocations committed by other validators and
submit those to the Runtime as described in
xref:modules/babe.adoc#sect-babeapi_submit_report_equivocation_unsigned_extrinsic[Sect.].
****

==== Block Production Lottery

The babe constant (xref:05_consensus/block_production.adoc#defn-babe-constant[Def.]) is initialized at genesis to the
value returned by calling `BabeApi_configuration` (xref:modules/babe.adoc#sect-rte-babeapi-epoch[Sect.]).
For efficiency reasons, it is generally updated by the Runtime through the _next
config data_ consensus message (xref:05_consensus/common.adoc#defn-consensus-message-digest[Def.]) in the digest
of the first block of an epoch for the next epoch.

A block producer aiming to produce a block during stem:[cc E_n] should run
Algorithm as defined in TODO xref:05_consensus/block_production.adoc#algo-block-production-lottery[Algo.] to identify the slots
it is awarded. These are the slots during which the block producer is allowed to
build a block. The stem:[sk] is the block producer lottery secret key and
stem:[n] is the index of the epoch for whose slots the block producer is running
the lottery.

[#defn-babe-constant]
===== BABE Constant
****
The *BABE constant* stem:[c in (0,1)] is the probability that a slot will not be
empty and used in the winning threshold calculation
(xref:05_consensus/block_production.adoc#defn-winning-threshold[Def.]).
****

[#defn-winning-threshold]
===== Winning Threshold
****
The *Winning threshold* denoted by stem:[T_(cc E_n)] is the threshold that is
used alongside the result of Algorithm as defined in
xref:05_consensus/block_production.adoc#algo-block-production-lottery[Algo.] to decide if a block producer is the winner of
a specific slot. stem:[T_(cc E_n)] is calculated  as follows:

[stem]
++++
T_(E_n) := 1 - (1 - c)^(1/("AuthorityDirectory"^(E_n)))
++++

where the stem:["AuthorityDirectory"^(cc E_n)] is the set of BABE authorities
for epoch stem:[cc E_n] and stem:[c in (0, 1)] is the BABE constant
(xref:05_consensus/block_production.adoc#defn-babe-constant[Def.]).
****

[#algo-block-production-lottery]
===== Block Production Lottery
****
A block producer aiming to produce a block during stem:[cc E_n] should run
the Algorithm as defined in <<>> to identify the slots it is awarded. These are
the slots during which the block producer is allowed to build a block. The
session secret key, stem:[sk], is the block producer lottery secret key and
stem:[n] is the index of the epoch for whose slots the block producer is running
the lottery.

Algorithm: stem:["Block-Production-Lottery"(sk)]

. stem:[r larr "Epoch-Randomness"(n)]
. stem:["for " i := 1 " to " sc_n]
. stem:["    " (pi, d) larr "VRF"(r,i,sk)]
. stem:["    " A\[i\] larr (d, pi)]
. stem:["return " A]

For any slot stem:[i] in epoch stem:[n] where stem:[d < r], the block producer
is required to produce a block. For the definitions of _Epoch-Randomness_
(xref:05_consensus/block_production.adoc#defn-epoch-randomness[Def.]) and _VRF_ functions (xref:01_crypto-algos.adoc#sect-vrf[Sect.]).
****

[#sect-slot-number-calculation]
==== Slot Number Calculation

It is imperative for the security of the network that each block producer
correctly determines the current slot numbers at a given time by regularly
estimating the local clock offset in relation to the network
(xref:05_consensus/block_production.adoc#defn-relative-syncronization[Def.]).

****
NOTE: *The calculation described in this section is still to be implemented and
deployed*: For now, each block producer is required to synchronize its local
clock using NTP instead. The current slot stem:[s] is then calculated by stem:[s
= t_("unix")/cc T] where stem:[cc T] is defined in xref:05_consensus/block_production.adoc#defn-epoch-slot[Def.] and
stem:[t_("unix")] is defined in xref:01_background/definitions.adoc#defn-unix-time[Def.]. That also entails that slot
numbers are currently not reset at the beginning of each epoch.
****

Polkadot does this synchronization without relying on any external clock source
(e.g. through the or the ). To stay in synchronization, each producer is
therefore required to periodically estimate its local clock offset in relation
to the rest of the network.

This estimation depends on the two fixed parameters stem:[k]
(xref:05_consensus/block_production.adoc#defn-prunned-best[Def.]) and stem:[s_(cq)] (xref:05_consensus/block_production.adoc#defn-chain-quality[Def.]). These are
chosen based on the results of a formal security analysis, currently assuming a
stem:[1 s]clock drift per day and targeting a probability lower than stem:[0.5%]
for an adversary to break BABE in 3 years with resistance against a network
delay up to stem:[1 / 3] of the slot time and a Babe constant
(xref:05_consensus/block_production.adoc#defn-babe-constant[Def.]) of stem:[c = 0.38].

All validators are then required to run Algorithm as defined in
xref:05_consensus/block_production.adoc#algo-slot-time[Algo.] at the beginning of each sync period (xref:05_consensus/block_production.adoc#defn-sync-period[Def.])
to update their synchronization using all block arrival times of the previous
period. The algorithm should only be run once all the blocks in this period have
been finalized, even if only probabilistically (xref:05_consensus/block_production.adoc#defn-prunned-best[Def.]). The
target slot to which to synchronize should be the first slot in the new sync
period.

[#defn-slot-offset]
===== Slot Offset
****
Let stem:[s_i] and stem:[s_j] be two slots belonging to epochs stem:[cc E_k]
and stem:[cc E_l]. By *Slot-Offset*stem:[(s_i,s_j)] we refer to the function
whose value is equal to the number of slots between stem:[s_i] and stem:[s_j]
(counting stem:[s_j]) on the time continuum. As such, we have
*Slot-Offset*stem:[(s_i, s_i) = 0].

It is imperative for the security of the network that each block producer
correctly determines the current slot numbers at a given time by regularly
estimating the local clock offset in relation to the network
(xref:05_consensus/block_production.adoc#defn-relative-syncronization[Def.]).
****

[#defn-relative-syncronization]
===== Relative Time Synchronization
****
The *relative time synchronization* is a tuple of a slot number and a local
clock timestamp stem:[(s_("sync"),t_("sync"))] describing the last point at
which the slot numbers have been synchronized with the local clock.

TODO: Algorithm
****

[#algo-slot-offset]
===== Slot Offset
****
Algorithm: stem:["Slot-Time"(s)]

. stem:["return " t_("sync") + "Slot-Offset"(s_("sync"),s) xx cc T]

where stem:[s] is the slot number.
****

[#algo-slot-time]
===== Slot Time Median Algorithm
****
Algorithm: stem:["Median-Algorithm"(cc P, s_("sync"))]

. stem:[T_s larr {}]
. stem:["for " B_i in cc P]
. stem:["    " t_("est")^B larr T_(B_i) + "Slot-Offset"(S_(B_i), s_("sync")) xx cc T]
. stem:["    " T_s larr T_S	uu t_("est")^(B_i)]
. stem:["return Median"(T_s)]

where

* stem:[cc P] is the sync period used for the estimate.
* stem:[s_("sync")] is the slot time to estimate.
* stem:["Slot-Offset"] is defined in xref:05_consensus/block_production.adoc#algo-slot-offset[Algo.].
* stem:[cc T] is the slot duration defined in xref:05_consensus/block_production.adoc#defn-epoch-slot[Def.].
****

[#defn-prunned-best]
===== Pruned Best Chain
****
The *pruned best chain* stem:[C^(r^k)] is the longest selected chain
(xref:01_background/definitions.adoc#defn-longest-chain[Def.]) with the last stem:[k] Blocks pruned. We chose stem:[k
= 140]. The *last (probabilistic) finalized block* describes the last block in
this pruned best chain.
****

[#defn-chain-quality]
===== Chain Quality
****
The *chain quality* stem:[s_(cq)] represents the number of slots that are used
to estimate the local clock offset. Currently, it is set to stem:[s_(cq) =
3000].

The prerequisite for such a calculation is that each producer stores the arrival
time of each block (xref:05_consensus/block_production.adoc#defn-block-time[Def.]) measured by a clock that is otherwise
not adjusted by any external protocol.
****

[#defn-block-time]
===== Block Arrival Time
The *block arrival time* of block stem:[B] for node stem:[j] formally
represented by stem:[T_B^j] is the local time of node stem:[j] when node
stem:[j] has received block stem:[B] for the first time. If the node stem:[j]
itself is the producer of stem:[B], stem:[T_B^j] is set equal to the time that
the block is produced. The index stem:[j] in stem:[T_B^j] notation may be
dropped and B’s arrival time is referred to by stem:[T_B] when there is no
ambiguity about the underlying node.

WARNING: Currently it still lacks a clear definition of when block arrival times
are considered valid and how to differentiated imported block on initial sync
from ``fresh'' blocks that were just produced.

[#defn-sync-period]
===== Sync Period
A is an interval at which each validator (re-)evaluates its local clock offsets.
The first sync period stem:[fr E_1] starts just after the genesis block is
released. Consequently, each sync period stem:[fr E_i] starts after stem:[fr
E_(i - 1)]. The length of the sync period (xref:05_consensus/block_production.adoc#defn-chain-quality[Def.]) is equal to
stem:[s_(qc)]and expressed in the number of slots.

[#block-production]
==== Block Production
Throughout each epoch, each block producer should run Algorithm as defined in
xref:05_consensus/block_production.adoc#algo-block-production[Algo.] to produce blocks during the slots it has been awarded
during that epoch. The produced block needs to carry the _BABE header_
(xref:05_consensus/block_production.adoc#defn-babe-header[Def.]) as well as the _block signature_
(xref:05_consensus/block_production.adoc#defn-block-signature[Def.]) as Pre-Runtime and Seal digest items.

[#defn-babe-header]
===== BABE Header
****
The *BABE Header* of block stem:[B], referred to formally by
stem:[H_("BABE")(B)] is a tuple and consists of the following components:

[stem]
++++
(d,pi,j,s)
++++

where:

* stem:[pi, d] are the results of the block lottery for slot stem:[s].
* stem:[j] is the index of the block producer in the authority directory of the
current epoch.
* stem:[s] is the slot at which the block is produced.

stem:[H_("BABE")(B)] must be included as a digest item of Pre-Runtime type in
the header digest (xref:03_transition/state_replication.adoc#defn-digest[Def.]) stem:[H_d(B)].
****

[#algo-block-production]
===== Invoke Block Authoring
****
Algorithm: stem:["Invoke-Block-Authoring"(sk, pk, n, "BT")]

. stem:[A larr "Block-Production-Lottery"(sk, n)]
. stem:["for " s larr 1 " to " "sc"_n]
. stem:["    " "Wait"("until Slot-Time"(s))]
. stem:["    " (d, pi) larr A\[s\]]
. stem:["    " "if " d < r]
. stem:["    " "    " C_("Best") larr "Longest-Chain"("BT")]
. stem:["    " "    " B_s larr "Build-Block"(C_("Best"))]
. stem:["    " "    " "Add-Digest-Item"(B_s, "Pre-Runtime", E_("id")("BABE"),H_("BABE")(B_s))]
. stem:["    " "    " "Add-Digest-Item"(B_s, "Seal", S_B)]
. stem:["    " "    " "Broadcast-Block"(B_s)]

where stem:["BT"] is the current block tree, stem:["Block-Production-Lottery"]
is defined in xref:05_consensus/block_production.adoc#algo-block-production-lottery[Algo.] and stem:["Add-Digest-Item"]
appends a digest item to the end of the header digest stem:[H_d(B)]
(xref:03_transition/state_replication.adoc#defn-digest[Def.]).
****

[#defn-block-signature]
===== Block Signature
****
The *Block Signature* stem:[S_B] is a signature of the block header hash
(xref:03_transition/state_replication.adoc#defn-block-header-hash[Def.]) and defined as

[stem]
++++
"Sig"_("SR25519","sk"_j^s)(H_h(B))
++++

stem:[S_B] should be included in stem:[H_d(B)] as the Seal digest item
(xref:03_transition/state_replication.adoc#defn-digest[Def.]) of value:

[stem]
++++
(E_(id)("BABE"),S_B)
++++

in which, stem:[E_("id")("BABE")] is the BABE consensus engine unique identifier
(xref:05_consensus/common.adoc#defn-consensus-message-digest[Def.]). The Seal digest item is referred to as the
*BABE Seal*.
****

[#sect-epoch-randomness]
==== Epoch Randomness
At the beginning of each epoch, stem:[cc E_n] the host will receive the
randomness seed stem:[cc R_(cc E_(n+1))] (xref:05_consensus/block_production.adoc#defn-epoch-randomness[Def.])
necessary to participate in the block production lottery in the next epoch
stem:[cc E_(n+1)] from the Runtime, through the consensus message
(xref:05_consensus/common.adoc#defn-consensus-message-digest[Def.]) in the digest of the first block.

[#defn-epoch-randomness]
===== Randomness Seed
****
For epoch stem:[cc E], there is a 32-byte stem:[cc R_(cc E)] computed
based on the previous epochs VRF outputs. For stem:[cc E_0] and stem:[cc
E_1], the randomness seed is provided in the genesis state.
****

[#sect-verifying-authorship]
==== Verifying Authorship Right

When a Polkadot node receives a produced block, it needs to verify if the block
producer was entitled to produce the block in the given slot by running
Algorithm as defined in xref:05_consensus/block_production.adoc#algo-verify-authorship-right[Algo.]. The Algorithm as
defined in xref:05_consensus/block_production.adoc#algo-verify-slot-winner[Algo.] runs as part of the verification process,
when a node is importing a block.

[#algo-verify-authorship-right]
===== Verify Authorship Right
****
Algorithm: stem:[tt "Verify-Authorship-Right"("Head"_s(B))]

. stem:[s larr "Slot-Number-At-Given-Time"(T_B)]
. stem:[cc E_c larr "Current-Epoch"()]
. stem:[(D_1, ..., D_("length"(H_d(B)))) larr H_d(B)]
. stem:[D_s larr D_("length"(H_d(B)))]
. stem:[H_d(B) larr (D_1, ..., D_("length"(H_d(B))-1)) " // remove the seal from the digest"]
. stem:[("id","Sig"_B) larr "Dec"_("SC")(D_s)]
. stem:["if " "id" != "Seal-Id"]
. stem:["    " "error 'Seal missing'"]
. stem:["AuthorId" larr "AuthorityDirectory"^(cc E_c)\[H_("BABE")(B)."SignerIndex"\]]
. stem:["Verify-Signature"("AuthorId", H_h(B), "Sig"_B)]
. stem:["if " EE B' in "BT": H_h(B) != H_h(B) " and " s_B = s'_B " and " "SignerIndex"_B = "SignerIndex"_(B')]
. stem:["    " "error 'Block producer is equivocating'"]
. stem:["Verify-Slot-Winner"((d_B, pi_B),s,"AuthorId")]

where:

* stem:["Head"_s(B)] is the header of the block that's being verified.
* stem:[T_B] is stem:[B]’s arrival time (xref:05_consensus/block_production.adoc#defn-block-time[Def.]).
* stem:[H_d(B)] is the digest sub-component (xref:03_transition/state_replication.adoc#defn-digest[Def.]) of
stem:["Head"(B)] (xref:03_transition/state_replication.adoc#defn-block-header[Def.]).
* The Seal stem:[D_s] is the last element in the digest array stem:[H_d(B)] as
described in xref:03_transition/state_replication.adoc#defn-digest[Def.].
* stem:[Seal-Id] is the type index showing that a digest item (xref:03_transition/state_replication.adoc#defn-digest[Def.])
of varying type (xref:02_encoding.adoc#defn-scale-variable-type[Def.]) is of type _Seal_.
* stem:["AuthorityDirectory"^(cc E_c)] is the set of Authority ID for block
producers of epoch stem:[cc E_c].
. stem:["AuthorId"] is the public session key of the block producer.
* stem:[Verify-Slot-Winner] is defined in Algorithm as described in
xref:05_consensus/block_production.adoc#algo-verify-slot-winner[Algo.].
****

[#algo-verify-slot-winner]
===== Verify Slot Winner
****
Algorithm: stem:[tt "Verify-Slot-Winner"(B)]

. stem:[cc E_c larr "Current-Epoch"]
. stem:[p larr "Epoch-Randomness"(c)]
. stem:["Verify-VRF"(p, H_("BABE").(pi, d),H_("BABE")(B).s,c)]
. stem:["if"  d_B >= t]
. stem:["    " "error 'Block producer is not a winner of the slot'"]

where:

. stem:["Epoch-Randomness"] is defined in xref:05_consensus/block_production.adoc#defn-epoch-randomness[Def.].
. stem:[H_("BABE")(B)] is the BABE header defined in xref:05_consensus/block_production.adoc#defn-babe-header[Def.].
. stem:[(d_B,pi_B)] is the block lottery result for block stem:[B].
. stem:["Verify-VRF"] is described in TODO xref:01_crypto-algos.adoc#sect-vrf[Sect.].
. stem:[t] is the winning threshold as defined in xref:05_consensus/block_production.adoc#defn-winning-threshold[Def.].
****

[#sect-block-building] 
==== Block Building Process

The block building process is triggered by the Algorithm as defined in TODO
xref:05_consensus/block_production.adoc#algo-block-production[Algo.] of the consensus engine which runs the Algorithm as
defined in xref:05_consensus/block_production.adoc#algo-build-block[Algo.]

[#algo-build-block]
===== Build Block
****
Algorithm: stem:[tt "Build-Block"(C_("Best"), s)]

. stem:[P_B larr "Head"(C_("Best"))]
. stem:["Head"(B) larr (H_p larr H_h(P_B), H_i larr H_i(P_B)+1,H_r larr phi, H_e larr phi, H_d larr phi)]
. stem:["Call-Runtime-Entry"(tt "Core_initialize_block", "Head"(B))]
. stem:["I-D" larr "Call-Runtime-Entry"(tt "BlockBuilder_inherent_extrinsic", "Inherent-Data")]
. stem:["for " E " in " "I-D"]
. stem:["    " "Call-Runtime-Entry"(tt "BlockBuilder_apply_extrinsics", E)]
. stem:["while not End-of-Slot"(s)]
. stem:["    " E larr "Next-Ready-Extrinsic"()]
. stem:["    " R larr "Call-Runtime-Entry"(tt "BlockBuilder_apply_extrinsics", E)]
. stem:["    " "if Block-Is-Full"(R)]
. stem:["    " "    " "break"]
. stem:["    " "if Should-Drop"(R)]
. stem:["    " "    " "Drop"(E)]
. stem:["Head"(B) larr "Call-Runtime-Entry"(tt "BlockBuilder_finalize_block", B)]
. stem:[B larr "Add-Seal"(B)]

where:

* stem:[C_("Best")] is the chain head at which the block should be constructed
("parent").
* stem:[s] is the slot number.
* stem:["Head"(B)] is defined in xref:03_transition/state_replication.adoc#defn-block-header[Def.].
* stem:["Call-Runtime-Entry"] is defined in xref:03_transition/runtime_interaction.adoc#notat-call-into-runtime[Decl.].
* stem:["Inherent-Data"] is defined in xref:03_transition/extrinsics.adoc#defn-inherent-data[Def.].
* stem:["End-Of-Slot"] indicates the end of the BABE slot as defined TODO
xref:05_consensus/block_production.adoc#algo-slot-time[Algo.] respectively xref:05_consensus/block_production.adoc#defn-epoch-slot[Def.].
* stem:["Next-Ready-Extrinsic"] indicates picking an extrinsic from the
extrinsics queue (xref:03_transition/extrinsics.adoc#defn-transaction-queue[Def.]).
* stem:["Block-Is-Full"] indicates that the maximum block size is being used.
* stem:["Should-Drop"] determines based on the result stem:[R] whether the
extrinsic should be dropped or remain in the extrinsics queue and scheduled for
the next block. The _ApplyExtrinsicResult_ (xref:modules/blockbuilder.adoc#defn-rte-apply-extrinsic-result[Def.])
describes this behavior in more detail.
* stem:["Drop"] indicates removing the extrinsic from the extrinsic queue
(xref:03_transition/extrinsics.adoc#defn-transaction-queue[Def.]).
* stem:["Add-Seal"] adds the seal to the block (<<>>) before sending it to
peers. The seal is removed again before submitting it to the Runtime.
****
