The runtime metadata structure contains all the information necessary on how to
interact with the Polkadot runtime. Considering that Polkadot runtimes are
upgradable and therefor any interfaces are subject to change, the metadata
allows developers to structure any extrinsics or storage entries accordingly.

=== Structure

The Runtime Metadata is a datastructure of the following format:

[stem]
++++
(T, P, E, Y)\
T = (r_n, ...,r_(n+m))\
P = (p_n, ...,p_(n+m))
++++

where

* stem:[r] is a **PortableType**.
* stem:[p] is a **PalletMetadata**.

==== PortableType

[stem]
++++
r = (i_c, y)
++++

where

* stem:[i_c] is a compact integer.
* stem:[y] is a **Type**.

==== Type:

[stem]
++++
(p,t,d,c)
++++

where

* stem:[p] is the unique path to the type, which might be empty. It consists of:
+
[stem]
++++
(s_n, ..., s_(n+m))
++++
+
where stem:[s_n] is a UTF-8 encoded string.
* stem:[t] is the generic type parameters of the type in use. It's empty for
non-generic types. It consists of:
+
[stem]
++++
(t_n, ...,t_(n+m))\
t_n = (n, y)
++++
+
where stem:[n] is a UTF-8 encoded string representing the name of the generic
type parameter and stem:[y] is a _Option_ type containing a **Type**.
* stem:[d] is the actual **TypeDefinition**.
* stem:[c] is an array of varying length containing strings of documentation.

==== Type

32-bit unsigned integer representing the index to the type in the interner table
(TODO: Clarify)

==== TypeDefinition

The type definition indicates all the possible types of encodable values a type can have.

[stem]
++++
x = {
	(0,->,a,"composite type (e.g. structure or tuple)"),
	(1,->,b,"variant type"),
	(2,->,c,"sequence type varying length"),
	(3,->,d,"sequence with fixed length"),
	(4,->,e,"tuple type"),
	(5,->,f,"primitive type"),
	(6,->,g,"compact encoded type"),
	(7,->,h,"sequence of bits")
:}
++++

where

stem:[a] is:

[stem]
++++
(f_n, ..., f_(n+m))\
++++

where stem:[f] is a **Field**.

stem:[b] is:

[stem]
++++
(v_n, ..., f_(n+m))
++++

where stem:[v] is a **Variant**.

stem:[c] is a **Type**.

stem:[d] is:

[stem]
++++
(l, y)
++++

where stem:[l] is a unsigned 32-bit integer indicating the length and stem:[y]
is a **Type**.

stem:[e] is an array of varying length containing **Type** elements.

stem:[f] is a varying datatype of the following structure:

[stem]
++++
{
	(0,"boolean"),
	(1,"char"),
	(2,"string"),
	(3,"unsigned 8-bit integer"),
	(4,"unsigned 16-bit integer"),
	(5,"unsigned 32-bit integer"),
	(6,"unsigned 64-bit integer"),
	(7,"unsigned 128-bit integer"),
	(8,"unsigned 256-bit integer"),
	(9,"signed 8-bit integer"),
	(10,"signed 16-bit integer"),
	(11,"signed 32-bit integer"),
	(12,"signed 64-bit integer"),
	(13,"signed 128-bit integer"),
	(14,"signed 256-bit integer")
:}
++++

stem:[g] is a **Type**.

stem:[h] TODO

==== Field

[stem]
++++
(n, y, y_n, c)
++++

where

 * stem:[n] is a string representing the field name.
 * stem:[y] is a **Type**.
 * stem:[y_n] is a _Option_ type containg a string that indicates the name of the
type as it appears in the source code.
 * stem:[c] is an array of varying length containing strings of documentation.

=== Variant

[stem]
++++
(n,F,i,c))
++++

where

* stem:[n] is a string representing the name of the variant.
* stem:[F] is a possible empty array of varying length containing **Field** elements.
* stem:[i] is an unsigned 8-bit integer indicating the index of the variant (TODO: Clarify).

=== Pallet Metadata

[stem]
++++
(n, s, a, e, c, e, i)
++++

where

* stem:[n] is a string representing the pallet name.
* stem:[s] is an _Option_ type containing the pallet storage metadata (TODO).
* stem:[a] is an _Option_ type containing the calls metadata (TODO).
* stem:[e] is an _Option_ type containing the event metadata (TODO).
* stem:[c] is an array of varying length containing the constant metadata (TODO).
* stem:[e] is an _Option_ type containing the error metadata (TODO).
* stem:[i] is an unsigned 8-bit integers indicating the index of the pallet,
which is used for encoding pallet events and calls.
