The runtime metadata structure contains all the information necessary on how to
interact with the Polkadot runtime. Considering that Polkadot runtimes are
upgradable and therefor any interfaces are subject to change, the metadata
allows developers to structure any extrinsics or storage entries accordingly.

=== Structure

The Runtime Metadata is a datastructure of the following format:

[stem]
++++
(T, P, E, Y)\
T = (r_n, ...,r_(n+m))\
P = (p_n, ...,p_(n+m))
++++

where

* stem:[r] is a **PortableType**.
* stem:[p] is a **PalletMetadata**.

==== PortableType

[stem]
++++
r = (i_c, y)
++++

where

* stem:[i_c] is a compact integer.
* stem:[y] is a **Type**.

==== Type:

[stem]
++++
(p,t,d,c)
++++

where

* stem:[p] is the unique path to the type, which might be empty. It consists of:
+
[stem]
++++
(s_n, ..., s_(n+m))
++++
+
where stem:[s_n] is a UTF-8 encoded string.
* stem:[t] is the generic type parameters of the type in use. It's empty for
non-generic types. It consists of:
+
[stem]
++++
(t_n, ...,t_(n+m))\
t_n = (n, y)
++++
+
where stem:[n] is a UTF-8 encoded string representing the name of the generic
type parameter and stem:[y] is a _Option_ type containing a **Type**.
* stem:[d] is the actual **TypeDefinition**.
* stem:[c] is an array of varying length containing strings of documentation.

==== Type

32-bit unsigned integer representing the index to the type in the interner table
(TODO: Clarify)

==== TypeDefinition

The type definition indicates all the possible types of encodable values a type can have.

[stem]
++++
x = {
	(0,->,a,"composite type (e.g. structure or tuple)"),
	(1,->,b,"variant type"),
	(2,->,c,"sequence type varying length"),
	(3,->,d,"sequence with fixed length"),
	(4,->,e,"tuple type"),
	(5,->,f,"primitive type"),
	(6,->,g,"compact encoded type"),
	(7,->,h,"sequence of bits")
:}
++++

where

stem:[a] is:

[stem]
++++
(f_n, ..., f_(n+m))\
++++

where stem:[f] is a **Field**.

stem:[b] is:

[stem]
++++
(v_n, ..., f_(n+m))
++++

where stem:[v] is a **Variant**.

stem:[c] is a **Type**.

stem:[d] is:

[stem]
++++
(l, y)
++++

where stem:[l] is a unsigned 32-bit integer indicating the length and stem:[y]
is a **Type**.

stem:[e] is an array of varying length containing **Type** elements.

stem:[f] is a varying datatype of the following structure:

[stem]
++++
{
	(0,"boolean"),
	(1,"char"),
	(2,"string"),
	(3,"unsigned 8-bit integer"),
	(4,"unsigned 16-bit integer"),
	(5,"unsigned 32-bit integer"),
	(6,"unsigned 64-bit integer"),
	(7,"unsigned 128-bit integer"),
	(8,"unsigned 256-bit integer"),
	(9,"signed 8-bit integer"),
	(10,"signed 16-bit integer"),
	(11,"signed 32-bit integer"),
	(12,"signed 64-bit integer"),
	(13,"signed 128-bit integer"),
	(14,"signed 256-bit integer")
:}
++++

stem:[g] is a **Type**.

stem:[h] TODO

==== Field

[stem]
++++
(n, y, y_n, c)
++++

where

 * stem:[n] is a string representing the field name.
 * stem:[y] is a **Type**.
 * stem:[y_n] is a _Option_ type containg a string that indicates the name of the
type as it appears in the source code.
 * stem:[c] is an array of varying length containing strings of documentation.

=== Variant

[stem]
++++
(n,F,i,c))
++++

where

* stem:[n] is a string representing the name of the variant.
* stem:[F] is a possible empty array of varying length containing **Field** elements.
* stem:[i] is an unsigned 8-bit integer indicating the index of the variant (TODO: Clarify).

=== Pallet Metadata

[stem]
++++
(n, s, a, e, c, e, i)
++++

where

* stem:[n] is a string representing the pallet name.
* stem:[s] is an _Option_ type containing the **PalletStorageMetadata**.
* stem:[a] is an _Option_ type containing the **Type** to the pallet call.
* stem:[e] is an _Option_ type containing the **Type** to the event metadata.
* stem:[c] is an array of varying length containing the **PalletConstantMetadata**.
* stem:[e] is an _Option_ type containing the **Type** error metadata.
* stem:[i] is an unsigned 8-bit integers indicating the index of the pallet,
which is used for encoding pallet events and calls.

==== PalletStorageMetadata

[stem]
++++
(p,E)
++++

where

* stem:[p] is the string representing the common prefix used by all storage entries.
* stem:[E] is an array of varying length containing elements of **StorageEntryMetadata**.

==== StorageEntryMetadata

[stem]
++++
(n, m, y, D, C)
++++

where

* stem:[n] is the string representing the variable name of the storage entry.
* stem:[m] is an _Option_ type containing the modifier of that storage entry (**StorageEntryModifier**).
* stem:[y] is the type of the value stored in the entry (**StorageEntryType**).
* stem:[D] is an byte array containing the default value.
* stem:[C] is an array of varying length of strings containing the documentation.

==== StorageEntryModifier

[stem]
++++
{
	(0,"optional"),
	(1,"default")
:}
++++

where _0_ indicates that the entry returns an _Option_ type and _1_ indicates
that the entry returns the type stem:[y] with value stem:[D] of
**StorageEntryModifier**.

==== StorageEntryMetadata

[stem]
++++
{
	(0,->,t,"plain type"),
	(1,->,(H, k, v),"storage map")
:}
++++

where stem:[t], stem:[k] and stem:[v] are all **Type**. stem:[H] is an array of
varying length containg the **StorageHasher**.

==== StorageHasher

[stem]
++++
{
	(0,"128-bit Blake2 hash"),
	(1,"256-bit Blake2 hash"),
	(2,"Multiple 128-bit Blake2 hashes concatenated"),
	(3,"128-bit XX hash"),
	(4,"256-bit XX hash"),
	(5,"Multiple 64-bit XX hashes concatenated"),
	(6,"Identity hashing")
:}
++++

==== PalletConstantMetadata

[stem]
++++
(n, y, V, C)
++++

where

* stem:[n] is a string representing the name of the pallet constant.
* stem:[y] is the **Type** of the pallet constant.
* stem:[V] is a byte array containing the value of the constant.
* stem:[C] is an array of varying length containg string with the documentation.

=== Extrinsic Metadata

[stem]
++++
(y, v, S)
++++

where

* stem:[y] is a **Type** of the extrinsic.
* stem:[v] is a unsigned 8-bit integer indicating the extrinsic version.
* stem:[S] is an array of varying length containing the **SignedExtensionMetadata**.

==== SignedExtensionMetadata

[stem]
++++
(i, y, a)
++++

where

* stem:[i] is a string representing the unique signed extension identifier,
which may be different from the type name.
* stem:[y] is a **Type** of the signed extension, with the data to be included
in the extrinsic.
* stem:[a] is a **Type** of the additional signed data, with the data to be
included in the signed payload.
