== Extrinsics

=== Introduction

An extrinsic is a SCALE encoded array consisting of a version number,
signature, and varying data types indicating the resulting Runtime
function to be called, including the parameters required for that
function to be executed.

=== Preliminaries

.Extrinsic
[#defn-extrinsic]
====
An extrinsic , latexmath:[tx], is a tuple consisting of the extrinsic
version, latexmath:[T_v] (<<defn-extrinsic-version>>), and the body of
the extrinsic, latexmath:[T_b].

[latexmath]
++++
tx := (T_v, T_b)
++++

The value of latexmath:[T_b] varies for each version. The current
version 4 is described in <<sect-version-four>>.
====

.Extrinsic Version
[#defn-extrinsic-version]
====
latexmath:[T_v] is a 8-bit bitfield and defines the extrinsic version. The
required format of an extrinsic body, latexmath:[T_b], is dictated by the
Runtime. Older or unsupported version are rejected.

The most significant bit of latexmath:[T_v] indicates whether the transaction is
*signed* (latexmath:[1]) or *unsigned* (latexmath:[0]). The
remaining 7-bits represent the version number. As an example, for
extrinsic format version 4, an signed extrinsic represents
latexmath:[T_v] as `132` while a unsigned extrinsic represents it as `4`.
====

=== Extrinsics Body

[#sect-version-four]
==== Version 4

Version 4 of the Polkadot extrinsic format is defined as follows:

[latexmath]
++++
T_b := (A_i, Sig, E, M_i, F_i(m))
++++

where::
* latexmath:[A_i]: the 32-byte address of the sender (<<defn-extrinsic-address>>).
* latexmath:[Sig]: the signature of the sender (<<defn-extrinsic-signature>>).
* latexmath:[E]: the extra data for the extrinsic (<<defn-extra-data>>).
* latexmath:[M_i]: the indicator of the Polkadot module (<<defn-module-indicator>>).
* latexmath:[F_i(m)]: the indicator of the function of the Polkadot module (<<defn-function-indicator>>).


.Extrinsic Address
[#defn-extrinsic-address]
====
Account Id, latexmath:[A_i], is the 32-byte address of the sender of the
extrinsic as described in the
https://github.com/paritytech/substrate/wiki/External-Address-Format-(SS58)[external
SS58 address format].
====


.Extrinsic Signature
[#defn-extrinsic-signature]
====
The signature, latexmath:[Sig], is a varying data type indicating the used
signature type, followed by the signature created by the extrinsic author.
The following types are supported:

[latexmath]
++++
Sig := \begin{cases}
         0, & \text{Ed25519, followed by: } (b_0, ...,b_{63}) \\
         1, & \text{Sr25519, followed by: } (b_0, ...,b_{63}) \\
         2, & \text{Ecdsa, followed by: } (b_0, ...,b_{64})
       \end{cases}
++++

Signature types vary in sizes, but each individual type is always
fixed-size and therefore does not contain a length prefix. `Ed25519` and
`Sr25519` signatures are 512-bit while `Ecdsa` is 520-bit, where the
last 8 bits are the recovery ID.

The signature is created by signing payload latexmath:[P].

[latexmath]
++++
\begin{aligned}
  P &:= \begin{cases}
          Raw, & \text{if } |Raw| \leq 256 \\
          Blake2(Raw), & \text{if } |Raw| > 256 \\
        \end{cases} \\
  Raw &:= (M_i, F_i(m), E, R_v, F_v, H_h(G), H_h(B)) \\
\end{aligned}
++++

where::
* latexmath:[M_i]: the module indicator (<<defn-module-indicator>>).
* latexmath:[F_i(m)]: the function indicator of the module (<<defn-function-indicator>>).
* latexmath:[E]: the extra data (<<defn-extra-data>>).
* latexmath:[R_v]: a UINT32 containing the specification version of `14`.
* latexmath:[F_v]: a UINT32 containing the format version of `2`.
* latexmath:[H_h(G)]: a 32-byte array containing the genesis hash.
* latexmath:[H_h(B)]: a 32-byte array containing the hash of the block
which starts the mortality period, as described in <<defn-extrinsic-mortality>>.
====


.Extra Data
[#defn-extra-data]
====
Extra data, latexmath:[E], is a tuple containing additional meta data about
the extrinsic and the system it is meant to be executed in.

[latexmath]
++++
E := (T_{mor}, N, P_t)
++++

where::
* latexmath:[T_{mor}]: contains the SCALE encoded mortality of the
extrinsic (<<defn-extrinsic-mortality>>).
* latexmath:[N]: a compact integer containing the nonce of the sender.
The nonce must be incremented by one for each extrinsic created,
otherwise the Polkadot network will reject the extrinsic.
* latexmath:[P_t]: a compact integer containing the transactor pay
including tip.
====


.Module Indicator
[#defn-module-indicator]
====
latexmath:[M_i] is an indicator for the Runtime to which Polkadot _module_,
latexmath:[m], the extrinsic should be forwarded to.

latexmath:[M_i] is a varying data type pointing to every module
exposed to the network.

[latexmath]
++++
M_i := \begin{cases}
  0, & \text{System} \\
  1, & \text{Utility} \\
  ... & \\
  7, & \text{Balances} \\
  ... &
\end{cases}
++++
====


.Function Indicator
[#defn-function-indicator]
====
latexmath:[F_i(m)] is a tuple which contains an indicator,
latexmath:[m_i], for the Runtime to which _function_ within the
Polkadot _module_, latexmath:[m], the extrinsic should be forwarded
to. This indicator is followed by the concatenated and SCALE encoded
parameters of the corresponding function, latexmath:[params].

[latexmath]
++++
F_i(m) := (m_i, params)
++++

The value of latexmath:[m_i] varies for each Polkadot module, since
every module offers different functions. As an example, the `Balances`
module has the following functions:

[latexmath]
++++
Balances_i := \begin{cases}
  0, & \text{transfer} \\
  1, & \text{set_balance} \\
  2, & \text{force_transfer} \\
  3, & \text{transfer_keep_alive} \\
  ... &
\end{cases}
++++
====


==== Mortality

.Extrinsic Mortality
[#defn-extrinsic-mortality]
====
Extrinsic *mortality* is a mechanism which ensures that an extrinsic is only
valid within a certain period of the ongoing Polkadot lifetime. Extrinsics can
also be immortal, as clarified in <<sect-mortality-encoding>>.

The mortality mechanism works with two related values:

* latexmath:[M_{per}]: the period of validity in terms of block
numbers from the block hash specified as latexmath:[H_h(B)] in the
payload (<<defn-extrinsic-signature>>). The
requirement is latexmath:[M_{per} \geq 4] and latexmath:[M_{per}]
must be the power of two, such as `32`, `64`, `128`, etc.
* latexmath:[M_{pha}]: the phase in the period that this extrinsic’s
lifetime begins. This value is calculated with a formula and validators
can use this value in order to determine which block hash is included in
the payload. The requirement is latexmath:[M_{pha} < M_{per}].

In order to tie a transaction’s lifetime to a certain block
(latexmath:[H_i(B)]) after it was issued, without wasting precious
space for block hashes, block numbers are divided into regular periods
and the lifetime is instead expressed as a "phase"
(latexmath:[M_{pha}]) from these regular boundaries:

[latexmath]
++++
M_{pha} = H_i(B)\ mod\ M_{per}
++++

latexmath:[M_{per}] and latexmath:[M_{pha}] are then included in the
extrinsic, as clarified in <<defn-extra-data>>, in the SCALE encoded form of
latexmath:[T_{mor}] (<<sect-mortality-encoding>>). Polkadot validators can use
latexmath:[M_{pha}] to figure out the block hash included in the payload,
which will therefore result in a valid signature if the extrinsic is within the
specified period or an invalid signature if the extrinsic "died".
====


===== Example

The extrinsic author choses latexmath:[M_{per} = 256] at block
`10'000`, resulting with latexmath:[M_{pha} = 16]. The extrinsic is
then valid for blocks ranging from `10'000` to `10'256`.

[#sect-mortality-encoding]
===== Encoding

latexmath:[T_{mor}] refers to the SCALE encoded form of type
latexmath:[M_{per}] and latexmath:[M_{pha}]. latexmath:[T_{mor}]
is the size of two bytes if the extrinsic is considered mortal, or
simply one bytes with the value equal to zero if the extrinsic is
considered immortal.

[latexmath]
++++
T_{mor} := Enc_{SC}(M_{per}, M_{pha})
++++

The SCALE encoded representation of mortality latexmath:[T_{mor}]
deviates from most other types, as it’s specialized to be the smallest
possible value, as described in <<algo-mortality-encode>> and <<algo-mortality-decode>>.

If the extrinsic is immortal, specify a single byte with the value equal
to zero.

****
.Encode Mortality
[pseudocode#algo-mortality-encode]
++++
\Require{$M_{per}, M_{pha}$}
\Return $0 \enspace \textbf{if} \enspace \textit{extrinsic is immortal}$
\State \textbf{init} $factor =$ \textsc{Limit}$(M_{per} >> 12,\ 1,\ \phi)$
\State \textbf{init} $left =$ \textsc{Limit}$($\textsc{TZ}$(M_{per})-1,\ 1,\ 15)$
\State \textbf{init} $right = \frac{M_{pha}}{factor} << 4$
\Return $left|right$
++++

.Decode Mortality
[pseudocode#algo-mortality-decode]
++++
\Require{$T_{mor}$}
\Return $\textit{Immortal} \enspace \textbf{if} \enspace T^{b0}_{mor} = 0$
\State \textbf{init} $enc = T^{b0}_{mor} + (T^{b1}_{mor} << 8)$
\State \textbf{init} $M_{per} = 2 << (enc\ mod\ (1 << 4))$
\State \textbf{init} $factor =$ \textsc{Limit}$(M_{per} >> 12, 1, \phi)$
\State \textbf{init} $M_{pha} = (enc >> 4) * factor$
\Return $(M_{per}, M_{pha})$
++++

where::
* latexmath:[T^{b0}_{mor}]: the first byte of latexmath:[T_{mor}].
* latexmath:[T^{b1}_{mor}]: the second byte of latexmath:[T_{mor}].
* Limit(latexmath:[num], latexmath:[min], latexmath:[max]):
Ensures that latexmath:[num] is between latexmath:[min] and
latexmath:[max]. If latexmath:[min] or latexmath:[max] is defined
as latexmath:[\phi], then there is no requirement for the specified
minimum/maximum.
* TZ(latexmath:[num]): returns the number of trailing zeros in the
binary representation of latexmath:[num]. For example, the binary
representation of `40` is `0010 1000`, which has three trailing zeros.
* latexmath:[>>]: performs a binary right shift operation.
* latexmath:[<<]: performs a binary left shift operation.
* latexmath:[|] : performs a bitwise OR operation.
****
