[#sect-metadata]
== Metadata
:kaitai-imports: scale

The runtime metadata structure contains all the information necessary on how to
interact with the Polkadot runtime. Considering that Polkadot runtimes are
upgradable and therefore any interfaces are subject to change, the metadata
allows developers to structure any extrinsics or storage entries accordingly.

The metadata of a runtime is provided by a call to `Metadata_metadata` (<<sect-rte-metadata-metadata>>)
and is returned as a scale encoded (<<sect-scale-codec>>) binary blob. How to interpret and decode this
data is described in this chapter.

[#sect-rtm-structure]
=== Structure

The Runtime Metadata is a datastructure of the following format:

[stem]
++++
(M, v_m, R, P, t_e, v_e, E, t_r) \
M = ("m", "e", "t", "a") \
R = (r_0, ...,r_n) \
P = (p_0, ...,p_n) \
E = (e_0, ...,e_n)
++++

where::
 * stem:[M] are the first four constant bytes, spelling "meta" in ASCII
 * stem:[v_m] is the format version of the metadata (one unsigned byte, currently `14`)

 * stem:[R] is a sequence (<<defn-scale-list>>) of type definitions stem:[r_i] (<<defn-rtm-registry-entry>>).

 * stem:[P] is a sequence (<<defn-scale-list>>) of pallet metadata stem:[p_i] (<<sect-rtm-pallet-metadata>>).

 * stem:[t_e] is the type Id (<<defn-rtm-type-id>>) of the extrinsics.
 * stem:[v_e] is the format version of the extrinsics
 * stem:[E] is a sequence (<<defn-scale-list>>) of extrinsics metadata stem:[e_i] (<<defn-rtm-signed-extension-metadata>>).
 * stem:[t_r] is the type Id (<<defn-rtm-type-id>>) of the runtime.

.Polkadot Runtime Metadata
[kaitai#metadata,kaitai-dependencies="metadata_type,metadata_pallet,metadata_extrinsic"]
++++
seq:
  - id: magic
    contents: meta
  - id: metadata_version
    type: u1

  - id: num_types
    type: scale::compact_int
  - id: types
    type: metadata_type
    repeat: expr
    repeat-expr: num_types.value

  - id: num_pallets
    type: scale::compact_int
  - id: pallets
    type: metadata_pallet
    repeat: expr
    repeat-expr: num_pallets.value

  - id: extrinsic_type
    type: scale::compact_int
  - id: extrinsic_version
    type: u1
  - id: num_extrinsics
    type: scale::compact_int
  - id: extrinsics
    type: metadata_extrinsic
    repeat: expr
    repeat-expr: num_extrinsics.value

  - id: runtime_type
    type: scale::compact_int
++++

.Runtime Registry Type Entry
[#defn-rtm-registry-entry]
====

A registry entry contains information about a type in its portable form for
serialization. The entry is a datastructure of the following format:

[stem]
++++
r_i = (i_t,p,T,D,c) \
T = (t_0, ...,t_n) \
t_i = (n, y)
++++

where::
* stem:[i_t] is a compact integer indicating the identifier of the type.
* stem:[p] is the path of the type, optional and based on source file location. Encoded a sequence (<<defn-scale-list>>) of strings.
* stem:[T] is a sequence (<<defn-scale-list>>) of generic parameters (empty for non-generic types).
** stem:[n] is the name string of the generic type parameter
** stem:[y] is a _Option_ type containing a type Id (<<defn-rtm-type-id>>).
* stem:[D] is the type definition (<<defn-rtm-type-definition>>).
* stem:[c] is the documentation as sequence (<<defn-scale-list>>) of strings.

.Runtime Metadata Type
[kaitai#metadata_type,kaitai-dependencies="metadata_type_definition"]
++++
seq:
  - id: id
    type: scale::compact_int

  - id: path
    type: scale::string_list

  - id: num_params
    type: scale::compact_int
  - id: params
    repeat: expr
    repeat-expr: num_params.value
    type: param

  - id: definition
    type: metadata_type_definition

  - id: docs
    type: scale::string_list
types:
  param:
    seq:
      - id: name
        type: scale::string
      - id: type
        type: scale::maybe_compact_int
++++
====

.Runtime Type Id
[#defn-rtm-type-id]
====
The runtime type Id is a compact integer representing the index to the
type in the type registry (<<defn-rtm-registry-entry>>).

====

.Type Variant
[#defn-rtm-type-definition]
====
The type definition stem:[D] indicates all the possible types of encodable
values a type can have.

[stem]
++++
D = {
	(0,->,C,"composite type (e.g. structure or tuple)"),
	(1,->,V,"variant type"),
	(2,->,s_v,"sequence type varying length"),
	(3,->,S,"sequence with fixed length"),
	(4,->,T,"tuple type"),
	(5,->,P,"primitive type"),
	(6,->,e,"compact encoded type"),
	(7,->,B,"sequence of bits")
:}
++++

where::
* stem:[C] is of the following format:
+
[stem]
++++
C = (f_0, ..., f_n)
++++
+
** stem:[f_i] is a field (<<defn-rtm-field>>).
* stem:[V] is of the following format:
+
[stem]
++++
V = (v_0, ..., v_n)
++++
+
** stem:[v_i] is a variant (<<defn-rtm-variant>>).
* stem:[s_v] is a type Id (<<defn-rtm-type-id>>).
* stem:[S] is of the following format:
+
[stem]
++++
S = (l, y)
++++
** stem:[l] is a unsigned 32-bit integer indicating the length
** stem:[y] is a type Id (<<defn-rtm-type-id>>).
* stem:[T] is a sequence (<<defn-scale-list>>) of type Ids (<<defn-rtm-type-id>>).
* stem:[P] is a varying datatype of the following structure:
+
[stem]
++++
P = {
	(0,"boolean"),
	(1,"char"),
	(2,"string"),
	(3,"unsigned 8-bit integer"),
	(4,"unsigned 16-bit integer"),
	(5,"unsigned 32-bit integer"),
	(6,"unsigned 64-bit integer"),
	(7,"unsigned 128-bit integer"),
	(8,"unsigned 256-bit integer"),
	(9,"signed 8-bit integer"),
	(10,"signed 16-bit integer"),
	(11,"signed 32-bit integer"),
	(12,"signed 64-bit integer"),
	(13,"signed 128-bit integer"),
	(14,"signed 256-bit integer")
:}
++++
* stem:[e] is a type Id (<<defn-rtm-type-id>>).
* stem:[B] is a datastructure of the following format:
+
[stem]
++++
B = (s, o)
++++
+
** stem:[s] is a type Id (<<defn-rtm-type-id>>) representing the bit store
type (https://docs.rs/bitvec/latest/bitvec/store/trait.BitStore.html[external
reference])
** stem:[o] is a type Id (<<defn-rtm-type-id>>) the bit order type
(https://docs.rs/bitvec/latest/bitvec/order/trait.BitOrder.html[external
reference]).

.Runtime Metadata Type Definition
[kaitai#metadata_type_definition,kaitai-dependencies="metadata_type_variants,metadata_type_fields"]
++++
seq:
  - id: type
    type: u1
    enum: type
  - id: details
    type:
      switch-on: type
      cases:
        "type::composite": metadata_type_fields
        "type::variant": metadata_type_variants
        "type::sequence": sequence
        "type::array": array
        "type::tuple": tuple
        "type::primitive": primitive
        "type::compact": compact
        "type::bits": bits
enums:
  type:
    0: composite
    1: variant
    2: sequence
    3: array
    4: tuple
    5: primitive
    6: compact
    7: bits
types:
  sequence:
    seq:
      - id: type
        type: scale::compact_int

  array:
    seq:
      - id: length
        type: u4
      - id: type
        type: scale::compact_int

  tuple:
    seq:
      - id: num_types
        type: scale::compact_int
      - id: types
        type: scale::compact_int
        repeat: expr
        repeat-expr: num_types.value

  primitive:
    seq:
      - id: id
        type: u1
        enum: pid
    enums:
      pid:
        0: bool
        1: char
        2: str
        3: uint8
        4: uint16
        5: uint32
        6: uint64
        7: uint128
        8: uint256
        9: int8
        10: int16
        11: int32
        12: int64
        13: int128
        14: int256

  compact:
    seq:
      - id: type
        type: scale::compact_int

  bits:
    seq:
      - id: type
        type: scale::compact_int
      - id: order
        type: scale::compact_int
++++
====

.Field
[#defn-rtm-field]
====
A field of a datastructure of the following format:

[stem]
++++
f_i = (n, y, y_n, c)
++++

where

 * stem:[n] is a string representing the field name.
 * stem:[y] is a type Id (<<defn-rtm-type-id>>).
 * stem:[y_n] is a _Option_ type containing a string that indicates the name of the
type as it appears in the source code.
 * stem:[c] is an array of varying length containing strings of documentation.

.Runtime Metadata Fields Type
[kaitai#metadata_type_fields]
++++
seq:
  - id: num_fields
    type: scale::compact_int
  - id: fields
    type: field
    repeat: expr
    repeat-expr: num_fields.value
types:
  field:
    seq:
      - id: name
        type: scale::maybe_string
      - id: type
        type: scale::compact_int
      - id: typename
        type: scale::maybe_string
      - id: docs
        type: scale::string_list
++++
====

.Variant
[#defn-rtm-variant]
====
A struct variant of the following format:

[stem]
++++
v_i = (n,F,k,c)
++++

where

* stem:[n] is a string representing the name of the variant.
* stem:[F] is a possible empty array of varying length containing field
(<<defn-rtm-field>>) elements.
* stem:[k] is an unsigned 8-bit integer indicating the index of the variant (TODO: Clarify).

.Runtime Metadata Variants Type
[kaitai#metadata_type_variants,kaitai-dependencies="metadata_type_fields"]
++++
seq:
  - id: num_variants
    type: scale::compact_int
  - id: variants
    type: variant
    repeat: expr
    repeat-expr: num_variants.value
types:
  variant:
    seq:
      - id: name
        type: scale::string
      - id: composite
        type: metadata_type_fields
      - id: index
        type: u1
      - id: docs
        type: scale::string_list
++++
====

[#sect-rtm-pallet-metadata]
=== Pallet Metadata
All the metadata about a pallet, part of the main structure
(<<sect-rtm-structure>>) and of the following format:

[stem]
++++
p_i = (n, S, a, e, C, e, i)
++++

where

* stem:[n] is a string representing the pallet name.
* stem:[S] is an _Option_ type containing the pallet storage metadata
(<<defn-rtm-pallet-storage-metadata>>).
* stem:[a] is an _Option_ type (<<defn-option-type>>) containing the type Id (<<defn-rtm-type-id>>) of pallet calls.
* stem:[e] is an _Option_ type (<<defn-option-type>>) containing the type Id (<<defn-rtm-type-id>>) of pallet events.
* stem:[C] is an _Sequence_ (<<defn-scale-list>>) of all pallet constant metadata
(<<defn-rtm-pallet-constants>>).
* stem:[e] is an _Option_ type (<<defn-option-type>>) containing the type Id (<<defn-rtm-type-id>>) of the pallet error.
* stem:[i] is an unsigned 8-bit integers indicating the index of the pallet, which is used for encoding pallet events and calls.

.Pallet Metadata
[kaitai#metadata_pallet,kaitai-dependencies="pallet_storage,pallet_constant"]
++++
seq:
  - id: name
    type: scale::string

  - id: has_storage
    type: u1
  - id: storage
    type: pallet_storage
    if: has_storage != 0

  - id: has_calls
    type: u1
  - id: calls
    type: calls
    if: has_calls != 0

  - id: has_events
    type: u1
  - id: events
    type: events
    if: has_events != 0

  - id: num_constants
    type: scale::compact_int
  - id: constants
    type: pallet_constant
    repeat: expr
    repeat-expr: num_constants.value

  - id: has_errors
    type: u1
  - id: errors
    type: errors
    if: has_errors != 0

  - id: index
    type: u1
types:
  calls:
    seq:
      - id: type
        type: scale::compact_int

  events:
    seq:
      - id: type
        type: scale::compact_int

  errors:
    seq:
      - id: type
        type: scale::compact_int
++++

.Pallet Storage Metadata
[#defn-rtm-pallet-storage-metadata]
====
The metadata about a pallets storage.

[stem]
++++
S = (p, E) \
E = ( e_0, ... , e_n )
++++

where

* stem:[p] is the string representing the common prefix used by all storage entries.
* stem:[E] is an array of varying length containing elements of storage entries
(<<defn-rtm-storage-entry-metadata>>).
====

.Storage Entry Metadata
[#defn-rtm-storage-entry-metadata]
====
The metadata about a pallets storage entry.

[stem]
++++
e_i = (n, m, y, d, C) \
C = ( c_0, ... , c_n )
++++

where

* stem:[n] is the string representing the variable name of the storage entry.
* stem:[m] is an enum type determining the storage entry modifier
(<<defn-rtm-storage-entry-modifier>>).
* stem:[y] is the type of the value stored in the entry
(<<defn-rtm-storage-entry-type>>).
* stem:[d] is an byte array containing the default value.
* stem:[C] is an array of varying length of strings containing the documentation.

.Pallet Storage Metadata
[kaitai#pallet_storage,kaitai-dependencies="storage_definition"]
++++
seq:
  - id: prefix
    type: scale::string

  - id: num_items
    type: scale::compact_int
  - id: items
    type: item
    repeat: expr
    repeat-expr: num_items.value
types:
  item:
    seq:
      - id: name
        type: scale::string

      - id: modifier
        type: u1
        enum: storage_modifier

      - id: definition
        type: storage_definition

      - id: fallback
        type: scale::bytes

      - id: docs
        type: scale::string_list
    enums:
      storage_modifier:
        0: optional
        1: default
++++
====

.Storage Entry Modifier
[#defn-rtm-storage-entry-modifier]
====

NOTE: This might be incorrect and has to be reviewed.

The storage entry modifier indicates how the storage entry is returned and how
it behaves if the entry is not present.

[stem]
++++
{
	(0,"optional"),
	(1,"default")
:}
++++

where _0_ indicates that the entry returns an _Option_ type and therefore _None_
if the storage entry is not present. _1_ indicates that the entry returns the
type stem:[y] with default value stem:[D] (in
<<defn-rtm-storage-entry-metadata>>) if the entry is not present.
====

.Storage Entry Type
[#defn-rtm-storage-entry-type]
====
The type of the storage value that indicates how the entry is stored.

[stem]
++++
{
	(0,->,t,"plain type"),
	(1,->,(H, k, v),"storage map")
:}
++++

where stem:[t], stem:[k] (key) and stem:[v] (value) are all of type Ids
(<<defn-rtm-type-id>>). stem:[H] is an array of varying length containing the
storage hasher (<<defn-rtm-storage-hasher>>).


.Runtime Pallet Storage Definition
[kaitai#storage_definition]
++++
seq:
  - id: type
    type: u1
    enum: storage_type
  - id: details
    type:
      switch-on: type
      cases:
        'storage_type::plain': plain
        'storage_type::map': map
enums:
  storage_type:
    0: plain
    1: map
types:
  plain:
    seq:
      - id: type
        type: scale::compact_int
  map:
    seq:
      - id: num_hasher
        type: scale::compact_int
      - id: hasher
        type: u1
        enum: hasher_type
        repeat: expr
        repeat-expr: num_hasher.value

      - id: key
        type: scale::compact_int
      - id: value
        type: scale::compact_int
    enums:
      hasher_type:
        0: blake2_128
        1: blake2_256
        2: blake2_128_128
        3: xxhash_128
        4: xxhash_256
        5: xxhahs_64_64
        6: idhash
++++
====

.Storage Hasher
[#defn-rtm-storage-hasher]
====
The hashing algorithm used by storage maps.

[stem]
++++
{
	(0,"128-bit Blake2 hash"),
	(1,"256-bit Blake2 hash"),
	(2,"Multiple 128-bit Blake2 hashes concatenated"),
	(3,"128-bit XX hash"),
	(4,"256-bit XX hash"),
	(5,"Multiple 64-bit XX hashes concatenated"),
	(6,"Identity hashing")
:}
++++
====

.Pallet Constants
[#defn-rtm-pallet-constants]
====
The metadata about the pallets constants.

[stem]
++++
c_i = (n, y, v, C)
++++

where::
* stem:[n] is a string representing the name of the pallet constant.
* stem:[y] is the type Id (<<defn-rtm-type-id>>) of the pallet constant.
* stem:[v] is a byte array containing the value of the constant.
* stem:[C] is an array of varying length containing string with the documentation.

.Pallet Constant Metadata
[kaitai#pallet_constant]
++++
seq:
  - id: name
    type: scale::string
  - id: type
    type: scale::compact_int
  - id: value
    type: scale::bytes
  - id: docs
    type: scale::string_list
++++

====

[#sect-rtm-extrinsic-metadata]
=== Extrinsic Metadata
The metadata about a pallets extrinsics, part of the main structure
(<<sect-rtm-structure>>) and of the following format:

.Signed Extension Metadata
[#defn-rtm-signed-extension-metadata]
====
The metadata about the additional, signed data required to execute an extrinsic.

[stem]
++++
e_i = (n, y, a)
++++

where::
* stem:[n] is a string representing the unique signed extension identifier,
which may be different from the type name.
* stem:[y] is a type Id (<<defn-rtm-type-id>>) of the signed extension, with the
data to be included in the extrinsic.
* stem:[a] is the type Id (<<defn-rtm-type-id>>) of the additional signed data,
with the data to be included in the signed payload.

.Runtime Extrinsic Metadata
[kaitai#metadata_extrinsic]
++++
seq:
  - id: name
    type: scale::string
  - id: type
    type: scale::compact_int
  - id: additional
    type: scale::compact_int
++++
====
