== Metadata
:kaitai-imports: scale

The runtime metadata structure contains all the information necessary on how to
interact with the Polkadot runtime. Considering that Polkadot runtimes are
upgradable and therefore any interfaces are subject to change, the metadata
allows developers to structure any extrinsics or storage entries accordingly.

[#sect-rtm-structure]
=== Structure

The Runtime Metadata is a datastructure of the following format:

[stem]
++++
(m,v, T, P, E, y)\
T = (r_n, ...,r_(n+m))\
P = (p_n, ...,p_(n+m))\
E = (e_n, ...,e_(n+m))
++++

where::
 * stem:[m] are the first four bytes spelling "meta"
 * stem:[v] is the format version of the metadata (currently `14`)
 * stem:[r] is a registry containing all type definitions
 (<<defn-rtm-registry-entry>>).
 * stem:[p] is a pallet metadata structure (<<sect-rtm-pallet-metadata>>).
 * stem:[e] is an extrinsic metadata structure (<<sect-rtm-extrinsic-metadata>>).
 * stem:[y] is the type Id (<<defn-rtm-type-id>>) of the runtime.

.Polkadot Runtime Metadata
[kaitai#metadata,kaitai-dependencies="lookup,pallet,extrinsic"]
++++
seq:
  - id: magic
    contents: meta
  - id: metadata_version
    type: u1

  - id: num_types
    type: scale::compact_int
  - id: lookup
    type: lookup
    repeat: expr
    repeat-expr: num_types.value

  - id: num_pallets
    type: scale::compact_int
  - id: pallets
    type: pallet
    repeat: expr
    repeat-expr: num_pallets.value

  - id: extrinsic_type
    type: scale::compact_int
  - id: extrinsic_version
    type: u1
  - id: num_extrinsics
    type: scale::compact_int
  - id: extrinsics
    type: extrinsic
    repeat: expr
    repeat-expr: num_extrinsics.value

  - id: runtime_type
    type: scale::compact_int
++++

.Runtime Registry Type Entry
[#defn-rtm-registry-entry]
====

A registry entry contains information about a type in its portable form for
serialization. The entry is a datastructure of the following format:

[stem]
++++
(i_c,P,T,d,C)
++++

where::
* stem:[i_c] is a compact integer indicating the identifier of the type.
* stem:[P] is the unique path to the type as according to the source code, which
might be empty. It's an array of varying length containing strings.
* stem:[T] is the generic type parameters of the type in use. It's empty for
non-generic types. It consists of:
+
[stem]
++++
(t_n, ...,t_(n+m))\
t_n = (n, y)
++++
+
where stem:[n] is a string representing the name of the generic
type parameter and stem:[y] is a _Option_ type containing a type Id
(<<defn-rtm-type-id>>).
* stem:[d] is the type variant (<<defn-rtm-type-variant>>).
* stem:[C] is an array of varying length containing strings of documentation.

.Runtime Registry Type Entry
[kaitai#lookup]
++++
seq:
  - id: id
    type: scale::compact_int

  - id: path
    type: scale::string_list

  - id: num_params
    type: scale::compact_int
  - id: params
    repeat: expr
    repeat-expr: num_params.value
    type: param

  - id: type
    type: u1
    enum: type
  - id: details
    type:
      switch-on: type
      cases:
        "type::composite": fields
        "type::variant": variants
        "type::sequence": sequence
        "type::array": array
        "type::tuple": tuple
        "type::primitive": primitive
        "type::compact": compact
        "type::bits": bits

  - id: docs
    type: scale::string_list
enums:
  type:
    0: composite
    1: variant
    2: sequence
    3: array
    4: tuple
    5: primitive
    6: compact
    7: bits
types:
  param:
    seq:
      - id: name
        type: scale::string
      - id: type
        type: scale::maybe_compact_int

  fields:
    seq:
      - id: num_fields
        type: scale::compact_int
      - id: fields
        type: field
        repeat: expr
        repeat-expr: num_fields.value
  field:
    seq:
      - id: name
        type: scale::maybe_string
      - id: type
        type: scale::compact_int
      - id: typename
        type: scale::maybe_string
      - id: docs
        type: scale::string_list

  variants:
    seq:
      - id: num_variants
        type: scale::compact_int
      - id: variants
        type: variant
        repeat: expr
        repeat-expr: num_variants.value
  variant:
    seq:
      - id: name
        type: scale::string
      - id: fields
        type: fields
      - id: index
        type: u1
      - id: docs
        type: scale::string_list

  sequence:
    seq:
      - id: type
        type: scale::compact_int

  array:
    seq:
      - id: length
        type: u4
      - id: type
        type: scale::compact_int

  tuple:
    seq:
      - id: num_types
        type: scale::compact_int
      - id: types
        type: scale::compact_int
        repeat: expr
        repeat-expr: num_types.value

  primitive:
    seq:
      - id: id
        type: u1
        enum: pid
    enums:
      pid:
        0: bool
        1: char
        2: str
        3: uint8
        4: uint16
        5: uint32
        6: uint64
        7: uint128
        8: uint256
        9: int8
        10: int16
        11: int32
        12: int64
        13: int128
        14: int256

  compact:
    seq:
      - id: type
        type: scale::compact_int

  bits:
      seq:
        - id: type
          type: scale::compact_int
        - id: order
          type: scale::compact_int
++++
====

.Runtime Type Id
[#defn-rtm-type-id]
====
The runtime type Id is a compact integer representing the index to the
type in the type registry (<<defn-rtm-registry-entry>>).

====

.Type Variant
[#defn-rtm-type-variant]
====
The type definition stem:[D] indicates all the possible types of encodable
values a type can have.

[stem]
++++
D = {
	(0,->,C,"composite type (e.g. structure or tuple)"),
	(1,->,V,"variant type"),
	(2,->,s_v,"sequence type varying length"),
	(3,->,S,"sequence with fixed length"),
	(4,->,T,"tuple type"),
	(5,->,P,"primitive type"),
	(6,->,e,"compact encoded type"),
	(7,->,B,"sequence of bits")
:}
++++

where

* stem:[C] is of the following format:
+
[stem]
++++
(f_n, ..., f_(n+m))\
++++
+
where stem:[f] is a field (<<defn-rtm-field>>).
* stem:[V] is of the following format:
+
[stem]
++++
(v_n, ..., v_(n+m))
++++
+
where stem:[v] is a variant (<<defn-rtm-variant>>).
* stem:[s_v] is a type Id (<<defn-rtm-type-id>>).
* stem:[S] is of the following format:
+
[stem]
++++
(l, y)
++++
+
where stem:[l] is a unsigned 32-bit integer indicating the length and stem:[y]
is a type Id (<<defn-rtm-type-id>>).
* stem:[T] is an array of varying length containing elements of type Ids (<<defn-rtm-type-id>>).
* stem:[P] is a varying datatype of the following structure:
+
[stem]
++++
P = {
	(0,"boolean"),
	(1,"char"),
	(2,"string"),
	(3,"unsigned 8-bit integer"),
	(4,"unsigned 16-bit integer"),
	(5,"unsigned 32-bit integer"),
	(6,"unsigned 64-bit integer"),
	(7,"unsigned 128-bit integer"),
	(8,"unsigned 256-bit integer"),
	(9,"signed 8-bit integer"),
	(10,"signed 16-bit integer"),
	(11,"signed 32-bit integer"),
	(12,"signed 64-bit integer"),
	(13,"signed 128-bit integer"),
	(14,"signed 256-bit integer")
:}
++++
* stem:[e] is a type Id (<<defn-rtm-type-id>>).
* stem:[B] is a datastructure of the following format:
+
[stem]
++++
(s, o)
++++
+
where stem:[s] is a type Id (<<defn-rtm-type-id>>) representing the bit store
type (https://docs.rs/bitvec/latest/bitvec/store/trait.BitStore.html[external
reference]) and stem:[o] is a type Id (<<defn-rtm-type-id>>) the bit order type
(https://docs.rs/bitvec/latest/bitvec/order/trait.BitOrder.html[external
reference]).
====

.Field
[#defn-rtm-field]
====
A field of a datastructure of the following format:

[stem]
++++
(n, y, y_n, c)
++++

where

 * stem:[n] is a string representing the field name.
 * stem:[y] is a type Id (<<defn-rtm-type-id>>).
 * stem:[y_n] is a _Option_ type containing a string that indicates the name of the
type as it appears in the source code.
 * stem:[c] is an array of varying length containing strings of documentation.
====

.Variant
[#defn-rtm-variant]
====
A struct variant of the following format:

[stem]
++++
(n,F,i,c))
++++

where

* stem:[n] is a string representing the name of the variant.
* stem:[F] is a possible empty array of varying length containing field
(<<defn-rtm-field>>) elements.
* stem:[i] is an unsigned 8-bit integer indicating the index of the variant (TODO: Clarify).
====

[#sect-rtm-pallet-metadata]
=== Pallet Metadata
All the metadata about a pallet, part of the main structure
(<<sect-rtm-structure>>) and of the following format:

[stem]
++++
(n, s, a, e, c, e, i)
++++

where

* stem:[n] is a string representing the pallet name.
* stem:[s] is an _Option_ type containing the pallet storage metadata
(<<defn-rtm-pallet-storage-metadata>>).
* stem:[a] is an _Option_ type containing the type Id (<<defn-rtm-type-id>>)
pallet call type.
* stem:[e] is an _Option_ type containing the type Id (<<defn-rtm-type-id>>) to the event type.
* stem:[c] is an array of varying length containing pallet constant metadata
(<<defn-rtm-pallet-constants>>).
* stem:[e] is an _Option_ type containing the type Id (<<defn-rtm-type-id>>) to the error type.
* stem:[i] is an unsigned 8-bit integers indicating the index of the pallet,
which is used for encoding pallet events and calls.

.Pallet Metadata
[kaitai#pallet,kaitai-dependencies=storage]
++++
seq:
  - id: name
    type: scale::string

  - id: has_storage
    type: u1
  - id: storage
    type: storage
    if: has_storage != 0

  - id: has_calls
    type: u1
  - id: calls
    type: calls
    if: has_calls != 0

  - id: has_events
    type: u1
  - id: events
    type: events
    if: has_events != 0

  - id: num_constants
    type: scale::compact_int
  - id: constants
    type: constant
    repeat: expr
    repeat-expr: num_constants.value

  - id: has_errors
    type: u1
  - id: errors
    type: errors
    if: has_errors != 0

  - id: index
    type: u1
types:
  calls:
    seq:
      - id: type
        type: scale::compact_int

  events:
    seq:
      - id: type
        type: scale::compact_int

  errors:
    seq:
      - id: type
        type: scale::compact_int

  constant:
    seq:
      - id: name
        type: scale::string
      - id: type
        type: scale::compact_int
      - id: value
        type: scale::bytes
      - id: docs
        type: scale::string_list
++++

.Pallet Storage Metadata
[#defn-rtm-pallet-storage-metadata]
====
The metadata about a pallets storage.

[stem]
++++
(p,E)
++++

where

* stem:[p] is the string representing the common prefix used by all storage entries.
* stem:[E] is an array of varying length containing elements of storage entries
(<<defn-rtm-storage-entry-metadata>>).
====

.Storage Entry Metadata
[#defn-rtm-storage-entry-metadata]
====
The metadata about a pallets storage entry.

[stem]
++++
(n, m, y, D, C)
++++

where

* stem:[n] is the string representing the variable name of the storage entry.
* stem:[m] is an _Option_ type containing the storage entry modifier
(<<defn-rtm-storage-entry-modifier>>).
* stem:[y] is the type of the value stored in the entry
(<<defn-rtm-storage-entry-type>>).
* stem:[D] is an byte array containing the default value.
* stem:[C] is an array of varying length of strings containing the documentation.
====

.Storage Entry Modifier
[#defn-rtm-storage-entry-modifier]
====
The storage entry modifier indicates how the storage entry is returned and how
it behaves if the entry is not present.

[stem]
++++
{
	(0,"optional"),
	(1,"default")
:}
++++

where _0_ indicates that the entry returns an _Option_ type and therefore _None_
if the storage entry is not present. _1_ indicates that the entry returns the
type stem:[y] with default value stem:[D] (in
<<defn-rtm-storage-entry-metadata>>) if the entry is not present.
====

.Storage Entry Type
[#defn-rtm-storage-entry-type]
====
The type of the storage value that indicates how the entry is stored.

[stem]
++++
{
	(0,->,t,"plain type"),
	(1,->,(H, k, v),"storage map")
:}
++++

where stem:[t], stem:[k] (key) and stem:[v] (value) are all of type Ids
(<<defn-rtm-type-id>>). stem:[H] is an array of varying length containing the
storage hasher (<<defn-rtm-storage-hasher>>).
====

.Storage Hasher
[#defn-rtm-storage-hasher]
====
The hashing algorithm used by storage maps.

[stem]
++++
{
	(0,"128-bit Blake2 hash"),
	(1,"256-bit Blake2 hash"),
	(2,"Multiple 128-bit Blake2 hashes concatenated"),
	(3,"128-bit XX hash"),
	(4,"256-bit XX hash"),
	(5,"Multiple 64-bit XX hashes concatenated"),
	(6,"Identity hashing")
:}
++++
====

.Pallet Storage Metadata
[kaitai#storage]
++++
seq:
  - id: prefix
    type: scale::string

  - id: num_items
    type: scale::compact_int
  - id: items
    type: item
    repeat: expr
    repeat-expr: num_items.value
types:
  item:
    seq:
      - id: name
        type: scale::string

      - id: modifier
        type: u1
        enum: storage_modifier

      - id: type
        type: u1
        enum: storage_type
      - id: details
        type:
          switch-on: type
          cases:
            'storage_type::plain': plain
            'storage_type::map': map

      - id: fallback
        type: scale::bytes

      - id: docs
        type: scale::string_list
    enums:
      storage_modifier:
        0: optional
        1: default
      storage_type:
        0: plain
        1: map

  plain:
    seq:
      - id: type
        type: scale::compact_int
  map:
    seq:
      - id: num_hasher
        type: scale::compact_int
      - id: hasher
        type: u1
        enum: hasher_type
        repeat: expr
        repeat-expr: num_hasher.value

      - id: key
        type: scale::compact_int
      - id: value
        type: scale::compact_int
    enums:
      hasher_type:
        0: blake2_128
        1: blake2_256
        2: blake2_128_128
        3: xxhash_128
        4: xxhash_256
        5: xxhahs_64_64
        6: idhash
++++

.Pallet Constants
[#defn-rtm-pallet-constants]
====
The metadata about the pallets constants.

[stem]
++++
(n, y, V, C)
++++

where

* stem:[n] is a string representing the name of the pallet constant.
* stem:[y] is the type Id (<<defn-rtm-type-id>>) of the pallet constant.
* stem:[V] is a byte array containing the value of the constant.
* stem:[C] is an array of varying length containing string with the documentation.
====

[#sect-rtm-extrinsic-metadata]
=== Extrinsic Metadata
The metadata about a pallets extrinsics, part of the main structure
(<<sect-rtm-structure>>) and of the following format:

[stem]
++++
(y, v, S)
++++

where

* stem:[y] is a type Id (<<defn-rtm-type-id>>) of the extrinsic.
* stem:[v] is a unsigned 8-bit integer indicating the extrinsic version.
* stem:[S] is an array of varying length containing the signed extension
metadata (<<defn-rtm-signed-extension-metadata>>).

.Signed Extension Metadata
[#defn-rtm-signed-extension-metadata]
====
The metadata about the additional, signed data required to execute an extrinsic.

[stem]
++++
(i, y, a)
++++

where

* stem:[i] is a string representing the unique signed extension identifier,
which may be different from the type name.
* stem:[y] is a type Id (<<defn-rtm-type-id>>) of the signed extension, with the
data to be included in the extrinsic.
* stem:[a] is the type Id (<<defn-rtm-type-id>>) of the additional signed data,
with the data to be included in the signed payload.

.Extrinsic Metadata
[kaitai#extrinsic]
++++
seq:
  - id: name
    type: scale::string
  - id: type
    type: scale::compact_int
  - id: additional
    type: scale::compact_int
++++
====
