= Introduction

[#defn-state-machine]
.<<defn-state-machine, Discrete State Machine (DSM)>>
====
A *Discrete State Machine (DSM)* is a state transition system that admits a
starting state and whose set of states and set of transitions are countable.
Formally, it is a tuple of

[stem]
++++
(\Sigma, S, s_0, \delta)
++++
where

* stem:[\Sigma] is the countable set of all possible inputs.
* stem:[S] is a countable set of all possible states.
* stem:[s_0 in S] is the initial state.
* stem:[\delta] is the state-transition function, known as *Runtime* in the
Polkadot vocabulary, such that

[stem]
++++
\delta : S \times \Sigma \rightarrow S
++++
====

[#defn-path-graph]
.<<defn-path-graph, Path Graph>>
====
A *path graph* or a *path* of stem:[n] nodes formally referred to as *stem:[P_n]*,
is a tree with two nodes of vertex degree 1 and the other n-2 nodes of vertex
degree 2. Therefore, stem:[P_n] can be represented by sequences of stem:[(v_1,
\ldots, v_n)] where stem:[e_i = (v_i, v_{i + 1})] for stem:[1 <= i <= n - 1] is
the edge which connect stem:[v_i] and stem:[v_{i + 1}].
====

[#defn-blockchain]
.<<defn-blockchain, Blockchain>>
====
A *blockchain* stem:[C] is a
https://en.wikipedia.org/wiki/Directed_graph[directed path graph]. Each node of
the graph is called *Block* and indicated by *stem:[B]*. The unique sink of
stem:[C] is called *Genesis Block*, and the source is called the stem:["Head"]
of stem:[C]. For any vertex stem:[(B_1, B_2)] where stem:[B_1 -> B_2] we say
stem:[B_2] is the *parent* of stem:[B_1], which is the *child* of stem:[B_2],
respectively. We indicate that by:

[stem]
++++
B_2 := P(B_1)
++++

The parent refers to the child by its hash value (<<defn-block-header>>), making
the path graph tamper proof since any modifications to the child would result in
its hash value being changed.

NOTE: The term "blockchain" can also be used as a way to refer to the network or
system that interacts or maintains the directed path graph.
====

== Block Tree

In the course of formation of a (distributed) blockchain, it is possible
that the chain forks into multiple subchains in various block positions.
We refer to this structure as a _block tree_:

[#defn-block-tree]
.<<defn-block-tree, Block >>
====
The *block tree* of a blockchain, denoted by stem:[BT] is the union of all
different versions of the blockchain observed by the Polkadot Host such that
every block is a node in the graph and stem:[B_1] is connected to stem:[B_2] if
stem:[B_1] is a parent of stem:[B_2].
====

When a block in the block tree gets finalized, there is an opportunity to prune
the block tree to free up resources into branches of blocks that do not contain
all of the finalized blocks or those that can never be finalized in the
blockchain (<<sect-finality>>).

[#defn-pruned-tree]
.<<defn-pruned-tree, Pruned Block Tree>>
====
By *Pruned Block Tree*, denoted by stem:["PBT"], we refer to a subtree of the block
tree obtained by eliminating all branches which do not contain the most recent
finalized blocks (<<defn-finalized-block>>). By *pruning*, we refer to the
procedure of stem:[BT larr "PBT"]. When there is no risk of ambiguity and is safe
to prune BT, we use stem:["BT"] to refer to stem:["PBT"].
====

<<defn-chain-subchain>> gives the means to highlight various branches of the
block tree.

[#defn-chain-subchain]
.<<defn-chain-subchain, Subchain>>
====
Let stem:[G] be the root of the block tree and stem:[B] be one of its nodes. By
stem:["Chain"(B)], we refer to the path graph from stem:[G] to stem:[B] in
stem:["BT"]. Conversely, for a chain stem:[C = "Chain"(B)], we define *the
head of stem:[C]* to be stem:[B], formally noted as stem:[B := bar C]. We define
stem:[|C|], the length of stem:[C] as a path graph.

If stem:[B'] is another node on stem:["Chain"(B)], then by stem:["SubChain"(B',
B)] we refer to the subgraph of stem:["Chain"(B)] path graph which contains
stem:[B] and ends at stem:[B'] and by stem:[|"SubChain"(B', B)|] we refer to its
length.

Accordingly, stem:[bbb C_(B')(BT)] is the set of all subchains of stem:[BT]
rooted at stem:[B']. The set of all chains of stem:[BT], stem:[bbb C_G(BT))] is
denoted by stem:[bbb C(BT)] or simply stem:[bbb C], for the sake of brevity.
====

[#defn-longest-chain]
.<<defn-longest-chain, Longest Chain>>
====
We define the following complete order over stem:[bbb C] as follows. For chains
stem:[C_1, C_2 in bbb C] we have that stem:[C_1 > C_2] if either stem:[|C_1| >
|C_2|] or stem:[|C_1| = |C_2|].

If stem:[|C_1| =| C_2|] we say stem:[C_1 > C_2] if and only if the block arrival
time (<<defn-block-time>>) of stem:[bar C_1] is less than the block arrival time
of stem:[bar C_2], from the _subjective perspective_ of the Host. We define the
stem:["Longest-Chain"(BT)] to be the maximum chain given by this order.
====

[#defn-longest-path]
.<<defn-longest-path, Longest Path>>
====
stem:["Longest-Path"(BT)] returns the path graph of stem:[BT] which is the
longest among all paths in stem:[BT] and has the earliest block arrival time
(<<defn-block-time>>). stem:["Deepest-Leaf"(BT)] returns the head of stem:["Longest-Path"(BT)] chain.
====

Because every block in the blockchain contains a reference to its parent, it is
easy to see that the block tree is de facto a tree. A block tree naturally
imposes partial order relationships on the blocks as follows:

[#defn-descendant-ancestor]
.<<defn-descendant-ancestor, Descendant and Ancestor>>
====
We say stem:[B] is *descendant* of stem:[B'], formally noted as stem:[B > B'],
if stem:[(|B| > |B'|) in C]. Respectively, we say that stem:[B'] is an
*ancestor* of stem:[B], formally noted as stem:[B < B'], if stem:[(|B| < |B'|)
in C].
====

[#sect-state-replication]
= State Replication

Polkadot nodes replicate each other’s state by syncing the history of the
extrinsics. This, however, is only practical if a large set of transactions are
batched and synced at the time. The structure in which the transactions are
journaled and propagated is known as a block of extrinsics
(<<sect-block-format>>). Like any other replicated state machines, state
inconsistency can occure between Polkadot replicas.
<<sect-managing-multiple-states>> gives an overview of how a Polkadot Host
node manages multiple variants of the state.

[#sect-block-format]
== Block Format
:kaitai-imports: scale

A Polkadot block consists a _block header_ (<<defn-block-header>>) and a _block
body_ (<<defn-block-body>>). The _block body_ in turn is made up out of
_extrinsics_ , which represent the generalization of the concept of
_transactions_. _Extrinsics_ can contain any set of external data the underlying
chain wishes to validate and track.

[kaitai#block,kaitai-dependencies="block_header,block_body"]
++++
seq:
  - id: header
    type: block_header
  - id: body
    type: block_body
++++

[#defn-block-header]
.<<defn-block-header,Block Header>>
====
The *header of block B*, stem:[H_h(B)], is a 5-tuple containing the following
elements:

* *parent_hash:* formally indicated as stem:[H_p], is the 32-byte Blake2b hash
(<<sect-blake2>>) of the SCALE encoded parent block header
(<<defn-block-header-hash>>).
* *number:* formally indicated as stem:[H_i], is an integer, which represents
the index of the current block in the chain. It is equal to the number of the
ancestor blocks. The genesis state has number 0.
* *state_root:* formally indicated as stem:[H_r], is the root of the Merkle trie,
whose leaves implement the storage for the system.
* *extrinsics_root:* is the field which is reserved for the Runtime to validate
the integrity of the extrinsics composing the block body. For example, it can
hold the root hash of the Merkle trie which stores an ordered list of the
extrinsics being validated in this block. The [.sans-serif]#extrinsics_root# is
set by the runtime and its value is opaque to the Polkadot Host. This element is
formally referred to as stem:[H_e].
* *digest:* this field is used to store any chain-specific auxiliary data, which
could help the light clients interact with the block without the need of
accessing the full storage as well as consensus-related data including the block
signature. This field is indicated as stem:[H_d] (<<defn-digest>>).
====

.Block Header
[kaitai#block_header,kaitai-dependencies=digest]
++++
seq:
  - id: parent_hash
    size: 32
  - id: number
    type: scale::compact_int
  - id: state_root
    size: 32
  - id: extrinsic_root
    size: 32
  - id: num_digests
    type: scale::compact_int
  - id: digests
    type: digest
    repeat: expr
    repeat-expr: num_digests.value
++++

[#defn-digest]
.<<defn-digest,Header Digest>>
====
The header *digest* of block stem:[B] formally referred to by stem:[H_d (B)] is
an array of *digest items* stem:[H_d^i]’s, known as digest items of varying data
type (<<defn-varrying-data-type>>) such that:

[stem]
++++
H_d(B) := H_d^1, ..., H_d^n
++++

where each digest item can hold one of the following type identifiers:

[stem]
++++
H_d^i = {
	(0, to, (E_"id", m)),
	(4, to, (E_"id", "CM")),
	(5, to, (E_"id", S_B)),
	(6, to, (E_"id", P)),
	(8, to, (E_id))
:}
++++

[horizontal]
asciimath:[E_"id" = 0]:: *Non-System* digest, which is opaque to the native code. stem:[m] is an opaque byte array.
asciimath:[E_"id" = 4]:: *Consensus Message*, contains messages from the Runtime to the consensus engine stem:["CM"] (<<defn-consensus-message-digest>>).
asciimath:[E_"id" = 5]:: *Seal*, is produced by the consensus engine and proving
the authorship of the block producer. Respectively, stem:[S_B] is the
signature (<<defn-block-signature>>) of the block producer. In particular, the
Seal digest item must be the last item in the digest array and must be stripped
off by the Polkadot Host before the block is submitted to any Runtime function
including for validation. The Seal must be added back to the digest afterward.
asciimath:[E_"id" = 6]:: *Pre-Runtime* digest, contains the BABE Pre-Digest item
stem:[P] (<<defn-babe-header>>).
asciimath:[E_"id" = 8]:: *Runtime Environment Updated* digest, indicates that
changes regarding the Runtime code or heap pages (<<sect-memory-management>>)
occurred. No additional data is provided.
====

.Block Header Digest
[kaitai#digest]
++++
seq:
  - id: type
    type: u1
    enum: type_id
  - id: value
    type:
      switch-on: type
      cases:
        'type_id::pre_runtime': pre_runtime
        'type_id::post_runtime': post_runtime
        'type_id::seal': seal
        'type_id::runtime_updated': empty
enums:
  type_id:
    4: post_runtime
    5: seal
    6: pre_runtime
    8: runtime_updated
types:
  pre_runtime:
    seq:
      - id: engine
        type: str
        encoding: ASCII
        size: 4
      - id: payload
        type: scale::bytes
  post_runtime:
    seq:
      - id: engine
        type: str
        encoding: ASCII
        size: 4
      - id: payload
        type: scale::bytes
  seal:
    seq:
      - id: engine
        type: str
        encoding: ASCII
        size: 4
      - id: payload
        type: scale::bytes
  empty: {}
++++

[#defn-block-header-hash]
.<<defn-block-header-hash,Header Hash>>
====
The *block header hash of block stem:[B]*, stem:[H_h(B)], is the hash of the
header of block stem:[B] encoded by simple codec:

[stem]
++++
H_h(B) := "Blake2b"("Enc"_(SC)("Head"(B)))
++++
====

[#defn-block-body]
.<<defn-block-body,Block Body>>
====
The block body consists of an sequence of extrinsics, each encoded as a byte
array. The content of an extrinsic is completely opaque to the Polkadot Host. As
such, from the point of the Polkadot Host, and is simply a SCALE encoded array
of byte arrays. The *body of Block* stem:[B] represented as stem:["Body"(B)] is
defined to be:

[stem]
++++
"Body"(B) := "Enc"_(SC)(E_1,...,E_n)
++++

Where each stem:[E_i in bbb B] is a SCALE encoded extrinsic.

[kaitai#block_body]
++++
seq:
  - id: num_transactions
    type: scale::compact_int
  - id: transactions
    type: transaction
    repeat: expr
    repeat-expr: num_transactions.value
types:
  transaction:
    seq:
      - id: len_data
        type: scale::compact_int
      - id: data
        size: len_data.value
++++

====
