[#sect-block-production-lottery]
= Block Production Lottery

The babe constant (<<defn-babe-constant>>) is initialized at genesis to the
value returned by calling `BabeApi_configuration` (<<sect-rte-babeapi-epoch>>).
For efficiency reasons, it is generally updated by the Runtime through the _next
config data_ consensus message (<<defn-consensus-message-digest>>) in the digest
of the first block of an epoch for the next epoch.

A block producer aiming to produce a block during stem:[cc E_n] should run
<algo-block-production-lottery>> to identify the slots it is awarded. These
are the slots during which the block producer is allowed to build a block. The
stem:[sk] is the block producer lottery secret key and stem:[n] is the index of
the epoch for whose slots the block producer is running the lottery.

In order to ensure consistent block production, BABE uses secondary slots in
case no authority won the (primary) block production lottery. Unlike the
lottery, secondary slot assignees are know upfront publically
(<<defn-babe-secondary-slots>>). The Runtime provides information on how
or if secondary slots are executed (<<sect-rte-babeapi-epoch>>), explained
further in <<defn-babe-secondary-slots>>.

[#defn-babe-constant]
.<<defn-babe-constant, BABE Constant>>
====
The *BABE constant* is the probability that a slot will not be empty and used in
the winning threshold calculation (<<defn-winning-threshold>>). It's expressed
as a rational, stem:[(x, y)], where stem:[x] is the numerator and stem:[y] is
the denominator.
====

[#defn-winning-threshold]
.<<defn-winning-threshold, Winning Threshold>>
====
The *Winning threshold* denoted by stem:[T_(cc E_n)] is the threshold that is
used alongside the result of <<algo-block-production-lottery>> to decide if a
block producer is the winner of a specific slot. stem:[T_(cc E_n)] is calculated
as follows:

[stem]
++++
A_w =sum_(n=1)^(|"Auth"_C(B)|)(w_A in "Auth"_C(B)_n) \
T_(cc E_n) := 1 - (1 - c)^(w_a/A_w)
++++

where stem:[A_w] is the total sum of all authority weights in the authority set
(<<defn-authority-list>>) for epoch stem:[cc E_n], stem:[w_a] is the weight of
the block author and stem:[c in (0, 1)] is the BABE constant
(<<defn-babe-constant>>).

The numbers should be treated as 64-bit rational numbers.
====

== Primary Block Production Lottery

A block producer aiming to produce a block during stem:[cc E_n] should run the
stem:["Block-Production-Lottery"] algorithm to identify the slots it is awarded.
These are the slots during which the block producer is allowed to build a block.
The session secret key, stem:[sk], is the block producer lottery secret key and
stem:[n] is the index of the epoch for whose slots the block producer is running
the lottery.

****
.Block-Production-Lottery
[pseudocode#algo-block-production-lottery]
++++
\require sk

\state $r \leftarrow$ \call{Epoch-Randomness}{$n$}

\for{$i := 1 ~\textbf{to}~ sc_n$}

    \state $(\pi, d) \leftarrow$ \call{VRF}{$r, i, sk$}

    \state $A[i] \leftarrow (d, \pi)$

\endfor

\return{A}
++++

where stem:["Epoch-Randomness"] is defined in (<<defn-epoch-randomness>>),
stem:[sc_n] is defined in <<defn-epoch-duration>> , stem:["VRF"] creates the
BABE VRF transcript (<<defn-babe-vrf-transcript>>) and stem:[e_i] is the epoch
index, retrieved from the Runtime (<<sect-rte-babeapi-epoch>>). stem:[s_k] and
stem:[p_k] is the secret key respectively the public key of the authority. For
any slot stem:[s] in epoch stem:[n] where stem:[o < T_(cc E_n)]
(<<defn-winning-threshold>>), the block producer is required to produce a block.
****

NOTE: the secondary slots (<<defn-babe-secondary-slots>>) are running
along side the primary block production lottery and mainly serve as a fallback
to in case no authority was selected in the primary lottery.

.<<defn-babe-secondary-slots, Secondary Slots>>
[#defn-babe-secondary-slots]
====
**Secondary slots** work along side primary slot to ensure consistent block
production, as described in <<sect-block-production-lottery>>. The secondary
assignee of a block is determined by calculating a specific value, stem:[i_d],
which indicates the index in the authority set (<<defn-authority-list>>). The
corresponding authority in that set has the right to author a secondary block.
This calculation is done for every slot in the epoch, stem:[s in sc_n]
(<<defn-epoch-duration>>).

[stem]
++++
p larr h("Enc"_"SC"(r,s))\
i_d larr p mod A_l
++++

where::
* stem:[r] is the Epoch randomness (<<defn-epoch-randomness>>).
* stem:[s] is the slot number (<<defn-epoch-slot>>).
* stem:["Enc"_"SC"(...)] encodes its inner value to the corresponding SCALE value.
* stem:[h(...)] creates a 256-bit Blake2 hash from its inner value.
* stem:[A_l] is the lengths of the authority list (<<defn-authority-list>>).

If stem:[i_d] points to the authority, that authority must claim the secondary
slot by creating a BABE VRF transcript (<<defn-babe-vrf-transcript>>). The
resulting values stem:[o] and stem:[p] are then used in the Pre-Digest item
(<<defn-babe-header>>). In case of secondary slots with plain outputs,
respectively the Pre-Digest being of value _2_, the transcript respectively the
VRF is skipped.
====

.<<defn-babe-vrf-transcript, BABE Slot VRF transcript>>
[#defn-babe-vrf-transcript]
====
The BABE block production lottery requires a specific transcript structure
(<<defn-vrf-transcript>>). That structure is used by both primary slots
(<<algo-block-production-lottery>>) and secondary slots
(<<defn-babe-secondary-slots>>).

[stem]
++++
t_1 larr "Transcript"("'BABE'")\
t_2 larr "append"(t_1, "'slot number'", s)\
t_3 larr "append"(t_2, "'current epoch'", e_i)\
t_4 larr "append"(t_3, "'chain randomness'", r)\
t_5 larr "append"(t_4, "'vrf-nm-pk'", p_k)\
t_6 larr "meta-ad"(t_5, "'VRFHash'", "False")\
t_7 larr "meta-ad"(t_6, 64_"le", "True")\
h larr "prf"(t_7, "False")\
o = s_k * h\
p larr "dleq_prove"(t_7, h)
++++

The operators are defined in <<defn-strobe-operations>>, stem:["dleq_prove"] in
<<defn-vrf-dleq-prove>>. The computed outputs, stem:[o] and stem:[p], are
included in the block Pre-Digest (<<defn-babe-header>>).
====
