[#sect-verifying-authorship]
= Verifying Authorship Right

When a Polkadot node receives a produced block, it needs to verify if the block
producer was entitled to produce the block in the given slot by running
<<algo-verify-authorship-right>>. <<algo-verify-slot-winner>> runs as part of the verification process,
when a node is importing a block.

****
.Verify-Authorship-Right
[pseudocode#algo-verify-authorship-right]
++++
\require $\text{Head}_{s(B)}$

\state $s \leftarrow$ \call{Slot-Number-At-Given-Time}{$T_B$}

\state $\mathcal{E}_c \leftarrow$ \call{Current-Epoch}{}

\state $(D_1, \ldots, D_{|H_d(B)|}) \leftarrow H_d(B)$

\state $D_s \leftarrow D_{|H_d(B)|}$

\state $H_d(B) \leftarrow \left(D_1, \ldots, D_{|H_d(B)| - 1}\right)$
    \comment{remove the seal from the digest}

\state $(id, \text{Sig}_B)\leftarrow \text{Dec}_{SC}(D_s)$

\if{$id \neq$ \textsc{Seal-Id}}

    \state \textbf{error} ``Seal missing''

\endif

\state $\text{AuthorID} \leftarrow \text{AuthorityDirectory}^{\mathcal{E}_c}[H_{BABE}(B).\text{SingerIndex}]$

\state \call{Verify-Signature}{$\text{AuthorID}, H_h(B),\text{Sig}_B$}

\if{$\exists B' \in BT : H_h(B) \neq H_h (B)$ \and $s_B = s_B'$ \and $\text{SignerIndex}_B = \text{SignerIndex}_{B'}$}

    \state \textbf{error} ``Block producer is equivocating''

\endif

\state \call{Verify-Slot-Winner}{$(d_B, \pi_B), s_B, \text{AuthorID}$}
++++

where::
* stem:["Head"_s(B)] is the header of the block that's being verified.
* stem:[T_B] is stem:[B]’s arrival time (<<defn-block-time>>).
* stem:[H_d(B)] is the digest sub-component (<<defn-digest>>) of
stem:["Head"(B)] (<<defn-block-header>>).
* The Seal stem:[D_s] is the last element in the digest array stem:[H_d(B)] as
described in <<defn-digest>>.
* stem:["Seal-Id"] is the type index showing that a digest item (<<defn-digest>>)
of varying type (<<defn-scale-variable-type>>) is of type _Seal_.
* stem:["AuthorityDirectory"^(cc E_c)] is the set of Authority ID for block
producers of epoch stem:[cc E_c].
. stem:["AuthorId"] is the public session key of the block producer.
* stem:["BT"] is the pruned block tree (<<defn-pruned-tree>>).
* stem:["Verify-Slot-Winner"] is defined in <<algo-verify-slot-winner>>.
****

****
.Verify-Slot-Winner
[pseudocode#algo-verify-slot-winner]
++++
\require $B$

\state $\mathcal{E}_c \leftarrow$ \textsc{Current-Epoch}

\state $\rho \leftarrow$ \call{Epoch-Randomness}{$c$}

\state \call{Verify-VRF}{$\rho, H_{BABE}(B).(d_B, \pi_B), H_{BABE}(B).s, c$}

\if{$d_B \geqslant \tau$}

    \state \textbf{error} ``Block producer is not a winner of the slot''

\endif
++++

where::
. stem:["Epoch-Randomness"] is defined in <<defn-epoch-randomness>>.
. stem:[H_"BABE"(B)] is the BABE header defined in <<defn-babe-header>>.
. stem:[(o,p)] is the block lottery result for block stem:[B]
(<<algo-block-production-lottery>>), respectively the VRF output
(<<defn-babe-vrf-transcript>>).
. stem:["Verify-VRF"] is described in <<sect-vrf>>.
. stem:[T_(cc E_n)] is the winning threshold as defined in <<defn-winning-threshold>>.
****
