[#sect-block-building] 
= Block Building Process

The block building process is triggered by <<algo-block-production>> of the
consensus engine which in turn runs <<algo-build-block>>.

****
.Build-Block
[pseudocode#algo-build-block]
++++

\state $P_B \leftarrow$ \textsc{Head}$(C_{Best})$

\state $\text{Head}(B) \leftarrow \left(H_p \leftarrow H_h(P_B), H_i \leftarrow H_i(P_B) + 1, H_r \leftarrow \phi, H_e \leftarrow \phi, H_d \leftarrow \phi \right)$

\state \textsc{Call-Runtime-Entry}$\left(\texttt{Core\_initialize\_block}, \text{Head}(B)\right)$

\state \textsc{I-D} $\leftarrow$ \textsc{Call-Runtime-Entry}$(\texttt{BlockBuilder\_inherent\_extrinsics},$ \textsc{Inherent-Data}$)$

\for{$E~\textbf{in}$ \textsc{I-D}}

    \state \textsc{Call-Runtime-Entry}$(\texttt{BlockBuilder\_apply\_extrinsics}, E)$

\endfor

\while{\not \textsc{End-Of-Slot}$(s)$}

    \state $E \leftarrow$ \textsc{Next-Ready-Extrinsic}$()$

    \state $R \leftarrow$ \textsc{Call-Runtime-Entry}$(\texttt{BlockBuilder\_apply\_extrinsics}, E)$

    \if{\textsc{Block-Is-Full}$(R)$}

        \break

    \endif

    \if{\textsc{Should-Drop}$(R)$}

        \state \textsc{Drop}$(E)$

    \endif

    \state $\text{Head}(B) \leftarrow$ \textsc{Call-Runtime-Entry}$(\texttt{BlockBuilder\_finalize\_block}, B)$

    \state $B \leftarrow$ \textsc{Add-Seal}$(B)$

\endwhile
++++

where::
* stem:[C_"Best"] is the chain head at which the block should be constructed
("parent").
* stem:[s] is the slot number.
* stem:["Head"(B)] is defined in <<defn-block-header>>.
* stem:["Call-Runtime-Entry"] is defined in <<defn-call-into-runtime>>.
* stem:["Inherent-Data"] is defined in <<defn-inherent-data>>.
* stem:["End-Of-Slot"] indicates the end of the BABE slot as defined
<<algo-slot-time>> respectively <<defn-epoch-slot>>.
* stem:["Next-Ready-Extrinsic"] indicates picking an extrinsic from the
extrinsics queue (<<defn-transaction-queue>>).
* stem:["Block-Is-Full"] indicates that the maximum block size is being used.
* stem:["Should-Drop"] determines based on the result stem:[R] whether the
extrinsic should be dropped or remain in the extrinsics queue and scheduled for
the next block. The _ApplyExtrinsicResult_ (<<defn-rte-apply-extrinsic-result>>)
describes this behavior in more detail.
* stem:["Drop"] indicates removing the extrinsic from the extrinsic queue
(<<defn-transaction-queue>>).
* stem:["Add-Seal"] adds the seal to the block (<<>>) before sending it to
peers. The seal is removed again before submitting it to the Runtime.
****
