[#sect-allocator-api]
=== Allocator

The Polkadot Runtime does not include a memory allocator and relies on the Host
API for all heap allocations. The beginning of this heap is marked by the
`__heap_base` symbol exported by the Polkadot Runtime. No memory should be
allocated below that address, to avoid clashes with the stack and data section.
The same allocator made accessible by this Host API should be used for any other
WASM memory allocations and deallocations outside the runtime e.g. when passing
the SCALE-encoded parameters to Runtime API calls.

==== `ext_allocator_malloc`

Allocates the given number of bytes and returns the pointer to that memory
location.

===== Version 1 - Prototype
----
(func $ext_allocator_malloc_version_1 (param $size i32) (result i32))
----

Arguments::

* `size`: the size of the buffer to be allocated.
* `result`: a 32-bit pointer to the allocated buffer.

==== `ext_allocator_free`

Free the given pointer.

===== Version 1 - Prototype
----
(func $ext_allocator_free_version_1 (param $ptr i32))
----

Arguments::

* `ptr`: a 32-bit pointer to the memory buffer to be freed.
