[#sect-child-storage-api]
=== Child Storage

Interface for accessing the child storage from within the runtime.

TODO: Is this correct?
[#defn-child-storage-type]
==== Child Storage
****
*Child storage* key is a unprefixed location of the child trie in the main trie.
****

==== `ext_default_child_storage_set`
Sets the value under a given key into the child storage.

===== Version 1 - Prototype
----
(func $ext_default_child_storage_set_version_1
	(param $child_storage_key i64) (param $key i64) (param $value i64))
----

Arguments::

* `child_storage_key` : a pointer-size (xref:intro.adoc#defn-runtime-pointer[Def.]) indicating the
child storage key (xref:child_storage.adoc#defn-child-storage-type[Def.]).
* `key`: a pointer-size (xref:intro.adoc#defn-runtime-pointer[Def.]) indicating the key.
* `value`: a pointer-size (xref:intro.adoc#defn-runtime-pointer[Def.]) indicating the value.

==== `ext_default_child_storage_get`
Retrieves the value associated with the given key from the child storage.

===== Version 1 - Prototype
----
(func $ext_default_child_storage_get_version_1
	(param $child_storage_key i64) (param $key i64) (result i64))
----

Arguments::

* `child_storage_key`: a pointer-size (xref:intro.adoc#defn-runtime-pointer[Def.]) indicating the
child storage key (xref:child_storage.adoc#defn-child-storage-type[Def.]).
* `key`: a pointer-size (xref:intro.adoc#defn-runtime-pointer[Def.]) indicating the key. 
* `result`: a pointer-size (xref:intro.adoc#defn-runtime-pointer[Def.]) indicating the SCALE
encoded _Option_ value (xref:02_encoding.adoc#defn-option-type[Def.]) containing the value.

==== `ext_default_child_storage_read`

Gets the given key from storage, placing the value into a buffer and returning
the number of bytes that the entry in storage has beyond the offset.

===== Version 1 - Prototype
----
(func $ext_default_child_storage_read_version_1
	(param $child_storage_key i64) (param $key i64) (param $value_out i64)
	(param $offset u32) (result i64))
----

Arguments::

* `child_storage_key`: a pointer-size (xref:intro.adoc#defn-runtime-pointer[Def.]) indicating the
child storage key (xref:child_storage.adoc#defn-child-storage-type[Def.]).
* `key`: a pointer-size (xref:intro.adoc#defn-runtime-pointer[Def.]) indicating the key.
* `value_out`: a pointer-size (xref:intro.adoc#defn-runtime-pointer[Def.]) indicating the buffer
to which the value will be written to. This function will never write more then
the length of the buffer, even if the value’s length is bigger.
* `offset`: an u32 integer containing the offset beyond the value should be read
from.
* `result`: a pointer-size (xref:intro.adoc#defn-runtime-pointer[Def.]) indicating the SCALE
encoded _Option_ value (xref:02_encoding.adoc#defn-option-type[Def.]) containing the number of bytes
written into the *value_out* buffer. Returns if the entry does not exists.

==== `ext_default_child_storage_clear`

Clears the storage of the given key and its value from the child storage.

===== Version 1 - Prototype
----
(func $ext_default_child_storage_clear_version_1
	(param $child_storage_key i64) (param $key i64))
----

Arguments::

* `child_storage_key`: a pointer-size (xref:intro.adoc#defn-runtime-pointer[Def.]) indicating the
child storage key (xref:child_storage.adoc#defn-child-storage-type[Def.]).
* `key`: a pointer-size (xref:intro.adoc#defn-runtime-pointer[Def.]) indicating the key.

==== `ext_default_child_storage_storage_kill`

Clears an entire child storage.

===== Version 1 - Prototype
----
(func $ext_default_child_storage_storage_kill_version_1
	(param $child_storage_key i64))
----

Arguments::

* `child_storage_key`: a pointer-size (xref:intro.adoc#defn-runtime-pointer[Def.]) indicating the
child storage key (xref:child_storage.adoc#defn-child-storage-type[Def.])..

==== `ext_default_child_storage_exists`

Checks whether the given key exists in the child storage.

===== Version 1 - Prototype
----
(func $ext_default_child_storage_exists_version_1
	(param $child_storage_key i64) (param $key i64) (return i32))
----

Arguments::

* `child_storage_key`: a pointer-size (xref:intro.adoc#defn-runtime-pointer[Def.]) indicating the
child storage key (xref:child_storage.adoc#defn-child-storage-type[Def.]).
* `key`: a pointer-size (xref:intro.adoc#defn-runtime-pointer[Def.]) indicating the key.
* `return`: an i32 integer value equal to _1_ if the key exists or a value equal
to _0_ if otherwise.

==== `ext_default_child_storage_clear_prefix`

Clears the child storage of each key/value pair where the key starts with the
given prefix.

===== Version 1 - Prototype
----
(func $ext_default_child_storage_clear_prefix_version_1
	(param $child_storage_key i64) (param $prefix i64))
----

Arguments::

* `child_storage_key`: a pointer-size (xref:intro.adoc#defn-runtime-pointer[Def.]) indicating the
child storage key (xref:child_storage.adoc#defn-child-storage-type[Def.]).
* `prefix`: a pointer-size (xref:intro.adoc#defn-runtime-pointer[Def.]) indicating the
prefix.

==== `ext_default_child_storage_root`

Commits all existing operations and computes the resulting child storage
root.

===== Version 1 - Prototype
----
(func $ext_default_child_storage_root_version_1
	(param $child_storage_key i64) (return i64))
----

Arguments::

* `child_storage_key`: a pointer-size (xref:intro.adoc#defn-runtime-pointer[Def.]) indicating the
child storage key (xref:child_storage.adoc#defn-child-storage-type[Def.]).
* `return`: a pointer-size (xref:intro.adoc#defn-runtime-pointer[Def.]) indicating the
SCALE encoded storage root.

==== `ext_default_child_storage_next_key`

Gets the next key in storage after the given one in lexicographic order
(xref:intro.adoc#defn-lexicographic-ordering[Def.]).
The key provided to this function may or may not exist in storage.

===== Version 1 - Prototype
----
(func $ext_default_child_storage_next_key_version_1
	(param $child_storage_key i64) (param $key i64) (return i64))
----

Arguments::

* `child_storage_key`: a pointer-size (xref:intro.adoc#defn-runtime-pointer[Def.]) indicating the
child storage key (xref:child_storage.adoc#defn-child-storage-type[Def.]).
* `key`: a pointer-size (xref:intro.adoc#defn-runtime-pointer[Def.]) indicating the key. 
* `return`: a pointer-size (xref:intro.adoc#defn-runtime-pointer[Def.]) indicating the SCALE
encoded as defined in xref:02_encoding.adoc#defn-option-type[Def.]
containing the next key in lexicographic order. Returns if the entry cannot be
found.
