[#sect-logging-api]
=== Logging

Interface that provides functions for logging from within the runtime.

[#defn-logging-log-level]
==== Log Level
****
The *Log Level*, stem:[L], is a varying data type (xref:02_encoding.adoc#defn-varrying-data-type[Def.])
and implies the emergency of the log. Possible log levels and the corresponding
identifier is as follows:

[stem]
++++
L = {(0,"Error = 1"),(1,"Warn = 2"),(2,"Info = 3"),(3, "Debug = 4"),(4,"Trace = 5"):}
++++
****

==== `ext_logging_log`

Request to print a log message on the host. Note that this will be only
displayed if the host is enabled to display log messages with given level and
target.

===== Version 1 - Prototype
----
(func $ext_logging_log_version_1
	(param $level i32) (param $target i64) (param $message i64))
----

Arguments::

* `level`: the log level (xref:logging.adoc#defn-logging-log-level[Def.]).
* `target`: a pointer-size (xref:intro.adoc#defn-runtime-pointer[Def.]) indicating the
string which contains the path, module or location from where the log was
executed.
* `message`: a pointer-size (xref:intro.adoc#defn-runtime-pointer[Def.]) indicating the log
message.
