[#sect-approval-voting]
=== Approval Voting

The approval voting process ensures that only valid parachain blocks are
finalized on the relay chain. After _backable_ parachain candidates were
submitted to the relay chain (<<sect-candidate-inclusion>>), which can be
retrieved via the Runtime API (<<sect-rt-api-availability-cores>>), validators
need to determine their assignments for each parachain and issue approvals for
valid candidates, respectively disputes for invalid candidates. Since it cannot
be expected that each validator verifies every single parachain candidate, this
mechanism ensures that enough honest validators are selected to verify parachain
candidates in order prevent the finalization of invalid blocks. If an honest
validator detects an invalid block which was approved by one or more validators,
the honest validator must issue a disputes which wil cause escalations,
resulting in consequences for all malicious parties, i.e. slashing. This
mechanism is described more in <<sect-availability-assignment-criteria>>.

[#sect-availability-assignment-criteria]
==== Assignment Criteria

Validators determine their assignment based on a VRF mechanism, similiar to the
BABE consensus mechanism. First, validators generate an availability core VRF
assignment (<<defn-availability-core-vrf-assignment>>), which indicates which
availability core a validator is assigned to. Then a delayed availability core
VRF assignment is generated which indicates at what point a validator should
start the approval process. The delays are based on “tranches”
(<<sect-tranches>>).

An assigned validator never broadcasts their assignment until relevant. Once the
assigned validator is ready to check a candidate, the validator broadcasts their
assignment by issuing an approval distribution message
(<<net-msg-approval-distribution>>), where stem:[M] is of variant _0_. Other
assigned validators that receive that network message must keep track of if,
expecting an approval vote following shortly after. Assigned validators can
retrieve the candidate by using the availability recovery
(<<sect-candidate-recovery>>) and then validate the candidate
(<<sect-candidate-validation>>).

The validator issues approval votes in form of a validator protocol message
(<<net-msg-validator-protocol-message>>) respectively disputes
(<<sect-disputes>>).

[#sect-tranches]
==== Tranches

Validators use a subjective, tick-based system to determine when the approval
process should start. A validator starts the tick-based system when a new
availability core candidates have been proposed, which can be retrieved via the
Runtime API (<<sect-rt-api-availability-cores>>) , and increments the tick every
_500 milliseconds_. Each tick/increment is referred to as a “tranche”,
represented as an integer, starting at _0_.

As described in <<sect-availability-assignment-criteria>>, the validator first
executes the VRF mechanism to determine which parachains (availability cores)
the validator is assigned to, then an additional VRF mechanism for each assigned
parachain to determine the _delayed assignment_. The delayed assignment
indicates the tranche at which the validator should start the approval process.
A tranche of value _0_ implies that the assignment should be started immediately,
while later assignees of later tranches wait until it's their term to issue
assignments, determined by their subjective, tick-based system.

Validators are required to track broadcasted assignments by other validators
assigned to the same parachain, including verifying the VRF output. Once a valid
assignment from a peer was received, the validator must wait for the following
approval vote within a certain period as described in
<<sect-rt-api-session-info>> by orienting itself on its local, tick-based
system. If the waiting time after a broadcasted assignment exceeds the specified
period, the validator interprets this behavior as a “no-show”, indicating that
more validators should commit on their tranche until enough approval votes have
been collected.

If enough approval votes have been collected as described in
<<sect-rt-api-session-info>>, then assignees of later tranches do not have to
start the approval process. Therefore, this tranche system serves as a mechanism
to ensure that enough candidate approvals from a random set of validators are
created without requiring all assigned validators to check the candidate.

[#defn-relay-vrf-story]
.<<defn-relay-vrf-story, Relay VRF Story>>
====
The relay VRF story is an array of random bytes derived from the VRF submitted
within the block by the block author. The relay VRF story, T, is used as input
to determine approval voting criteria and generated the following way:

[stem]
++++
T = sf "Transcript"(b_r,b_s,e_i,A)
++++

where

* stem:[sf "Transcript"] constructs a VRF transcript (<<defn-vrf-transcript>>).
* stem:[b_r] is the BABE randomness of the current epoch (<<defn-epoch-randomness>>).
* stem:[b_s] is the current BABE slot (<<defn-epoch-slot>>).
* stem:[e_i] is the current BABE epoch index (<<defn-epoch-slot>>).
* stem:[A] is the public key of the authority.
====

[#defn-availability-core-vrf-assignment]
.<<defn-availability-core-vrf-assignment, Availability Core VRF Assignment>>
====
An availability core VRF assignment is computed by a relay chain validator to
determine which availability core (<<defn-availability-core>>) a validator is
assigned to and should vote for approvals. Computing this assignement relies on
the VRF mechanism, transcripts and STROBE operations described further in
<<sect-vrf>>.

The Runtime dictates how many assignments should be conducted by a validator, as
specified in the session index which can be retrieved via the Runtime API
(<<sect-rt-api-session-info>>). The amount of assignments is referred to as
“samples”. For each iteration of the number of samples, the validator calculates
an individual assignment, stem:[T], where the little-endian encoded sample
number, stem:[S], is incremented by one. At the beginning of the iteration,
stem:[S] starts at value _0_.

The validator executes the following steps to retrieve a (possibly valid) core index:

[stem]
++++
t_1 larr "Transcript"("'A&V MOD'")\
t_2 larr "append"(t_1, "'RC-VRF'", R_s)\
t_3 larr "append"(t_2, "'sample'", S)\
t_4 larr "append"(t_3, "'vrf-nm-pk'", p_k)\
t_5 larr "meta-ad"(t_4, "'VRFHash'", "False")\
t_6 larr "meta-ad"(t_5, 64_("le"), "True")\
i larr "prf"(t_6, "False")\
o = s_k * i
++++

where stem:[s_k] is the secret key, stem:[p_k] is the public key and
stem:[64_("le")] is the integer _64_ encoded as little endian. stem:[R_s] is the
relay VRF story as defined in <<defn-relay-vrf-story>>. Following:

[stem]
++++
t_1 larr "Transcript"("'VRFResult'")\
t_2 larr "append"(t_1, "''", "'A&V CORE'")\
t_3 larr "append"(t_2, "'vrf-in'", i)\
t_4 larr "append"(t_3, "'vrf-out'", o)\
t_5 larr "meta-ad"(t_4, "''", "False")\
t_6 larr "meta-ad"(t_5, 4_("le"), "True")\
c larr "prf"(t_6, "False")\
r_c = c mod a_c
++++

where stem:[4_("le")] is the integer _4_ encoded as little endian, stem:[c] is the
4-byte challenge interpreted as a little endian encoded interger and stem:[a_c]
is the number of availability cores used during the active session, as defined
in the session info retrieved by the Runtime API (<<sect-rt-api-session-info>>).
The resulting integer, stem:[c_i], indicates the parachain Id
(<<defn-para-id>>). If the parachain Id doesn't exist, as can be retrieved by the Runtime
API (<<sect-rt-api-availability-cores>>), the validator discards that value and
continues with the next iteration. If the Id does exist, the validators
continues with the following steps:

[stem]
++++
t_1 larr "Transcript"("'A&V ASSIGNED'")\
t_2 larr "append"(t_1, "'core'", r_c)\
p larr "dleq_prove"(t_2, i)
++++

where stem:["dleq_prove"] is described in <<defn-vrf-dleq-prove>>.

TODO: Clarify usage of "AssignmentCert", deprecate the following:
====

[#delayed-availability-core-vrf-assignment]
.<<delayed-availability-core-vrf-assignment, Delayed Availability Core VRF Assignment>>
====
The *delayed availability core VRF assignments* determined at what point a
validator should start the approval process as described in <<sect-tranches>>.
Computing this assignement relies on the VRF mechanism, transcripts and STROBE
operations described further in <<sect-vrf>>.

The validator executes the following steps:

[stem]
++++
t_1 larr sf "Transcript"("'A&V DELAY'")\
t_2 larr sf "append"(t_1,"'RC-VRF'",R_s)\
t_3 larr sf "append"(t_2, "'core'",c_i)\
t_4 larr "append"(t_3, "'vrf-nm-pk'", p_k)\
t_5 larr "meta-ad"(t_4, "'VRFHash'", "False")\
t_6 larr "meta-ad"(t_5, 64_("le"), "True")\
i larr larr "prf"(t_6, "False")\
o = s_k * i\
(p,x) larr sf "dleq_prove"(t_6, i)
++++

The resulting values stem:[h] and stem:[p] are the VRF input/output pair
respectively the VRF proof (<<defn-vrf-proof>>). stem:["dleq_prove"] is
described in <<defn-vrf-dleq-prove>>.

The tranche, stem:[d], is determined as:

[stem]
++++
t_1 larr "Transcript"("'VRFResult'")\
t_2 larr "append"(t_1, "''", "'A&V TRANCHE'")\
t_3 larr "append"(t_2, "'vrf-in'", i)\
t_4 larr "append"(t_3, "'vrf-out'", o)\
t_5 larr "meta-ad"(t_4, "''", "False")\
t_6 larr "meta-ad"(t_5, 4_("le"), "True")\
c larr "prf"(t_6, "False")\
d = sf d mod (d_c+d_z) - d_z
++++

where

* stem:[d_c] is the number of delayed tranches by total as specified by the
session info, retrieved via the Runtime API (<<sect-rt-api-session-info>>).
* stem:[d_z] is the zeroth delay tranche width as specified by the session info,
retrieved via the Runtime API (<<sect-rt-api-session-info>>)..

The resulting tranche, stem:[n], cannot be less than stem:[0]. If the tranche is
less than stem:[0], then stem:[d=0].
====
