[#sect-anv-definitions]
=== Definitions

[#defn-collator]
==== Collator
A collator is a parachain node that sends parachain blocks, known as candidates
(<<defn-candidate>>), to the relay chain validators. The relay chain validators
are not concerned how the collator works or how it creates candidates.

[#defn-candidate]
==== Candidate
A candidate is a submitted parachain block (<<defn-para-block>>) to the relay
chain validators. A parachain block stops being referred to as a candidate as
soon it has been finalized.

[#defn-para-block]
==== Parachain Block
A parachain block or a Proof-of-Validity block (PoV block) contains the
necessary data to for parachain specific state transition logic. Relay chain
validators are not concerned with the inner structure of the block and treat it
as a byte array.

[#defn-head-data]
==== Head Data
The head data is contains information about a parachain block
(<<defn-para-block>>). The head data is returned by executing the parachain
Runtime and relay chain validators are not concerned with its inner structure
and treat it as a byte arrays.

[#defn-para-id]
==== Parachain Id
The Parachain Id is a unique, unsigned 32-bit integer which serves as an
identifier of a parachain, assigned by the Runtime.

[#defn-availability-core]
==== Availability Core
Availability cores are slots used to process parachains. The Runtime assigns
each parachain to a availability core and validators can fetch information about
the cores, such as parachain block candidates, by calling the appropriate
Runtime API (<<sect-rt-api-availability-cores>>). Validators are not concerned
with the internal workings from the Runtimes perspective.

[#defn-validator-groups]
==== Validator Groups
Validator groups indicate which validators are responsible for creating backable
candidates for parachains (<<sect-candidate-backing>>), and are assigned
by the Runtime. Validators are not concerned with the internal workings from the
Runtimes perspective. Collators can use this information for submitting blocks.

[#defn-upward-message]
==== Upward Message
An upward message is an opaque byte array sent from a parachain to a relay chain.

[#defn-downward-message]
==== Downward Message
A downward message is an opaque byte array received by the parachain from the
relay chain.

[#defn-outbound-hrmp-message]
==== Outbound HRMP Message
An outbound HRMP message (Horizontal Relay-routed Message Passing) is sent from
the perspective of a sender of a parachain to an other parachain by passing it
through the relay chain. It's a datastructure of the following format:

[stem]
++++
(I,M)
++++

where stem:[I] is the recipient Id (<<defn-para-id>>) and stem:[M] is an upward
message (<<defn-upward-message>>).

[#defn-inbound-hrmp-message]
==== Inbound HRMP Message
An inbound HRMP message (Horizontal Relay-routed Message Passing) is seen from
the perspective of a recipient parachain sent from an other parachain by passing
it through the relay chain. It's a datastructure of the following format:

[stem]
++++
(N,M)
++++

where stem:[N] is the unsigned 32-bit integer indicating the relay chain block
number at which the message was passed down to the recipient parachain and
stem:[M] is a downward message (<<defn-downward-message>>).

[#defn-bitfield-array]
==== Bitfield Array
A bitfield array contains single-bit values which indidate whether a candidate
is available. The number of items is equal of to the number of availability
cores (<<defn-availability-core>>) and each bit represents a vote on the
corresponding core in the given order. Respectively, if the single bit equals 1,
then the Polkadot validator claims that the availability core is occupied, there
exists a committed candidate receipt (<<defn-committed-candidate-receipt>>) and
that the validator has a stored chunk of the parachain block
(<<defn-para-block>>).
