=== Introduction

The Polkadot network is decentralized and does not rely on any central authority
or entity for achieving its fullest potential of provided functionality. The
networking protocol is based on a family of open protocols, including protocol
implemented _libp2p_ e.g. the distributed Kademlia hash table which is used for
peer discovery.

This chapter walks through the behavior of the networking implementation of the
Polkadot Host and defines the network messages. The implementation details of
the _libp2p_ protocols used are specified in external sources as described in
<<sect-networking-external-docs>>

[#sect-networking-external-docs]
=== External Documentation

Complete specification of the Polkadot networking protocol relies on the
following external protocols:

* https://github.com/libp2p/specs[libp2p] - _libp2p_ is a modular peer-to-peer
networking stack composed of many modules and different parts. includes the
multiplexing protocols and .
* https://docs.libp2p.io/concepts/addressing/[libp2p addressing] - The Polkadot
Host uses the _libp2p_ addressing system to identify and connect to peers.
* https://en.wikipedia.org/wiki/Kademlia[Kademlia] - _Kademlia_ is a distributed
hash table for decentralized peer-to-peer networks. The Polkadot Host uses
Kademlia for peer discovery.
* https://noiseprotocol.org/[Noise] - The _Noise_ protocol is a framework for
building cryptographic protocols. The Polkadot Host uses Noise to establish the
encryption layer to remote peers.
* https://docs.libp2p.io/concepts/stream-multiplexing/#mplex[mplex] - _mplex_ is
a multiplexing protocol developed by _libp2p_. The protocol allows dividing a
connection to a peer into multiple substreams, each substream serving a specific
purpose. Generally, Polkadot Host implementers are encouraged to prioritize
implementing , since it is the de-facto standard in Polkadot._mplex_ is only
required to communicate with https://github.com/libp2p/js-libp2p[js-lip2p].
* https://docs.libp2p.io/concepts/stream-multiplexing/#yamux[yamux] - _yamux_ is
a multiplexing protocol like _mplex_ and developed by HashiCorp. It is the
de-facto standard for the Polkadot Host. This protocol should be prioritized
over _mplex_. <<sect-protocols-substreams>> describes the subprotocol in more
detail.
* https://developers.google.com/protocol-buffers/docs/reference/proto3-spec[Protocol
Buffers] - Protocol Buffers is a language-neutral, platform-neutral mechanism
for serializing structured data and is developed by Google. The Polkadot Host
uses Protocol Buffers to serialize specific messages, as clarified in
<<sect-network-messages>>.

=== Node Identities

Each Polkadot Host node maintains an ED25519 key pair which is used to
identify the node. The public key is shared with the rest of the network
allowing the nodes to establish secure communication channels.

Each node must have its own unique ED25519 key pair. When two or more nodes use
the same key, the network will interpret those nodes as a single node, which
will result in undefined behavior and can result in equivocation. Furthermore,
the node’s _PeerId_ as defined in <<defn-peer-id>> is derived from its public
key. _PeerId_ is used to identify each node when they are discovered in the
course of the discovery mechanism described in <<sect-discovery-mechanism>>.

[#defn-peer-id]
.<<defn-peer-id,PeerId>>
====
The Polkadot node’s _PeerId_, formally referred to as stem:[P_(id)], is derived
from the ED25519 public key and is structured as defined in the
https://docs.libp2p.io/concepts/peer-id/[libp2p specification].
====

[#sect-discovery-mechanism]
=== Discovery mechanism

The Polkadot Host uses various mechanisms to find peers within the
network, to establish and maintain a list of peers and to share that
list with other peers from the network as follows:

* *Bootstrap nodes* are hard-coded node identities and addresses provided by the
genesis state (<<chapter-genesis>>).
* *mDNS* is a protocol that performs a broadcast to the local network. Nodes
that might be listening can respond to the broadcast.
https://github.com/libp2p/specs/blob/master/discovery/mdns.md[The libp2p mDNS
specification] defines this process in more detail. This protocol is an optional
implementation detail for Polkadot Host implementers and is not required to
participate in the Polkadot network.
* *Kademlia requests* invoking Kademlia requests, where nodes respond with their
list of available peers. Kademlia requests are performed on a specific substream
as described in <<sect-protocols-substreams>>.

[#sect-connection-establishment]
=== Connection establishment

Polkadot nodes connect to peers by establishing a TCP connection. Once
established, the node initiates a handshake with the remote peers on the
encryption layer. An additional layer on top of the encryption layer, known as
the multiplexing layer, allows a connection to be split into substreams, as
described by the
https://docs.libp2p.io/concepts/stream-multiplexing/#yamux[yamux specification],
either by the local or remote node.

The Polkadot node supports two types of substream protocols.
<<sect-protocols-substreams>> describes the usage of each type in more detail:

* *Request-Response substreams*: After the protocol is negotiated by the
multiplexing layer, the initiator sends a single message containing a request.
The responder then sends a response, after which the substream is then
immediately closed. The requests and responses are prefixed with their
https://en.wikipedia.org/wiki/LEB128[LEB128] encoded length.
* *Notification substreams*. After the protocol is negotiated, the initiator
sends a single handshake message. The responder can then either accept the
substream by sending its own handshake or reject it by closing the substream.
After the substream has been accepted, the initiator can send an unbound number
of individual messages. The responder keeps its sending side of the substream
open, despite not sending anything anymore, and can later close it in order to
signal to the initiator that it no longer wishes to communicate.
+
Handshakes and messages are prefixed with their
https://en.wikipedia.org/wiki/LEB128[LEB128] encoded lengths. A handshake can be
empty, in which case the length prefix would be _0_.

Connections are established by using the following protocols:

* `/noise` - a protocol that is announced when a connection to a peer is
established.
* `/multistream/1.0.0` - a protocol that is announced when negotiating an
encryption protocol or a substream.
* `/yamux/1.0.0` - a protocol used during the _mplex_ or _yamux_ negotiation.
See <<sect-protocols-substreams>> for more information.

The Polkadot Host can establish a connection with any peer of which it
knows the address. The Polkadot Host supports multiple networking
protocols:

* *TCP/IP* with addresses in the form of `/ip4/1.2.3.4/tcp/30333` to establish a TCP
connection and negotiate encryption and a multiplexing layer.
* *WebSocket* with addresses in the form of `/ip4/1.2.3.4/tcp/30333/ws` to establish a
TCP connection and negotiate the WebSocket protocol within the connection.
Additionally, encryption and multiplexing layer is negotiated within the
WebSocket connection.
* *DNS* addresses in form of `/dns/example.com/tcp/30333` and `/dns/example.com/tcp/30333/ws`.

The addressing system is described in the
https://docs.libp2p.io/concepts/addressing/[libp2p addressing] specification.
After a base-layer protocol is established, the Polkadot Host will apply the
Noise protocol to establish the encryption layer as described in
<<sect-encryption-layer>>.

[#sect-encryption-layer]
=== Encryption Layer

Polkadot protocol uses the _libp2p_ Noise framework to build an encryption
protocol. The Noise protocol is a framework for building encryption protocols.
_libp2p_ utilizes that protocol for establishing encrypted communication
channels. Refer to the https://github.com/libp2p/specs/tree/master/noise[libp2p
Secure Channel Handshake] specification for a detailed description.

Polkadot nodes use the https://noiseexplorer.com/patterns/XX/[XX handshake
pattern] to establish a connection between peers. The three following steps are
required to complete the handshake process:

. The initiator generates a keypair and sends the public key to the responder.
The https://github.com/libp2p/specs/tree/master/noise[Noise specification] and
the https://github.com/libp2p/specs/blob/master/peer-ids/peer-ids.md[libp2p
PeerId specification] describe keypairs in more detail.
. The responder generates its own key pair and sends its public key back to the
initiator. After that, the responder derives a shared secret and uses it to
encrypt all further communication. The responder now sends its static Noise
public key (which may change anytime and does not need to be persisted on disk),
its _libp2p_ public key and a signature of the static Noise public key signed
with the _libp2p_ public key.
. The initiator derives a shared secret and uses it to encrypt all further
communication. It also sends its static Noise public key, _libp2p_ public key
and signature to the responder.

After these three steps, both the initiator and responder derive a new shared
secret using the static and session-defined Noise keys, which are used to
encrypt all further communication.

[#sect-protocols-substreams]
=== Protocols and Substreams

After the node establishes a connection with a peer, the use of multiplexing
allows the Polkadot Host to open substreams. _libp2p_ uses the
https://docs.libp2p.io/concepts/stream-multiplexing/#mplex[_mplex protocol_] or
the https://docs.libp2p.io/concepts/stream-multiplexing/#yamux[_yamux protocol_]
to manage substreams and to allow the negotiation of _application-specific
protocols_, where each protocol serves a specific utility.

The Polkadot Host uses multiple substreams whose usage depends on a specific
purpose. Each substream is either a _Request-Response substream_ or a
_Notification substream_, as described in
<<sect-connection-establishment>>.

NOTE: The prefixes on those substreams are known as protocol identifiers and are
used to segregate communications to specific networks. This prevents any
interference with other networks. `dot` is used exclusively for Polkadot.
Kusama, for example, uses the protocol identifier `ksmcc3`.

* `/ipfs/ping/1.0.0` - Open a standardized substream _libp2p_ to a peer and
initialize a ping to verify if a connection is still alive. If the peer does not
respond, the connection is dropped. This is a _Request-Response substream_.
+
Further specification and reference implementation are available in the
https://docs.libp2p.io/concepts/protocols/#ping[libp2p documentation].
* `/ipfs/id/1.0.0` - Open a standardized _libp2p_ substream to a peer to ask for
information about that peer. This is a _Request-Response substream_.
+
Further specification and reference implementation are available in the
https://docs.libp2p.io/concepts/protocols/#ping[libp2p documentation].
* `/dot/kad` - Open a standardized substream for Kademlia `FIND_NODE` requests.
This is a _Request-Response substream_, as defined by the _libp2p_ standard.
+
Further specification and reference implementation are available on
https://en.wikipedia.org/wiki/Kademlia[Wikipedia] respectively the
https://github.com/libp2p/go-libp2p-kad-dht[golang Github repository].
* `/91b171bb158e2d3848fa23a9f1c25182fb8e20313b2c1eb49219da7a70ce90c3/light/2` - a request and response protocol that allows a light client to
request information about the state. This is a _Request-Response substream_.
+
The messages are specified in <<sect-light-msg>>.
+
NOTE: For backwards compatibility reasons, `/dot/light/2` is also a valid substream for those messages.
* `/91b171bb158e2d3848fa23a9f1c25182fb8e20313b2c1eb49219da7a70ce90c3/block-announces/1` - a substream/notification protocol which sends
blocks to connected peers. This is a _Notification substream_.
+
The messages are specified in <<sect-msg-block-announce>>.
+
NOTE: For backwards compatibility reasons, `/dot/block-announces/1` is also a valid substream for those messages.
* `/91b171bb158e2d3848fa23a9f1c25182fb8e20313b2c1eb49219da7a70ce90c3/sync/2` - a request and response protocol that allows the Polkadot Host
to request information about blocks. This is a _Request-Response substream_.
+
The messages are specified in <<sect-msg-block-request>>.
+
NOTE: For backwards compatibility reasons, `/dot/sync/2` is also a valid substream for those messages.
+
* `/91b171bb158e2d3848fa23a9f1c25182fb8e20313b2c1eb49219da7a70ce90c3/sync/warp` - a request and response protocol that allows the Polkadot Host
to perform a warp sync request. This is a _Request-Response substream_.
+
The messages are specified in <<sect-warp-sync>>.
+
NOTE: For backwards compatibility reasons, `/dot/sync/warp` is also a valid substream for those messages.
* `/91b171bb158e2d3848fa23a9f1c25182fb8e20313b2c1eb49219da7a70ce90c3/transactions/1` - a substream/notification protocol which sends
transactions to connected peers. This is a _Notification substream_.
+
The messages are specified in <<sect-msg-transactions>>.
+
NOTE: For backwards compatibility reasons, `/dot/transactions/1` is also a valid substream for those messages.
* `/91b171bb158e2d3848fa23a9f1c25182fb8e20313b2c1eb49219da7a70ce90c3/grandpa/1` - a substream/notification protocol that sends GRANDPA
votes to connected peers. This is a _Notification substream_.
+
The messages are specified in <<sect-msg-grandpa>>.
+
NOTE: For backwards compatibility reasons, `/paritytech/grandpa/1` is also a valid substream for those messages.
* `/91b171bb158e2d3848fa23a9f1c25182fb8e20313b2c1eb49219da7a70ce90c3/beefy/1` - a substream/notification protocol which sends signed
BEEFY statements, as described in <<sect-grandpa-beefy>>, to connected peers.
This is a _Notification_ substream.
+
The messages are specified in <<sect-msg-grandpa-beefy>>.
+
NOTE: For backwards compatibility reasons, `/paritytech/beefy/1` is also a valid substream for those messages.
