[#sect-network-messages]
=== Network Messages

The Polkadot Host must actively communicate with the network in order to
participate in the validation process or act as a full node.

NOTE: The Polkadot network originally only used SCALE encoding for all message
formats. Meanwhile, Protobuf has been adopted for certain messages. The encoding
of each listed message is always SCALE encoded unless Protobuf is explicitly
mentioned. Encoding and message formats are subject to change.

[#sect-msg-block-announce]
==== Announcing blocks

When the node creates or receives a new block, it must be announced to the
network. Other nodes within the network will track this announcement and can
request information about this block. The mechanism for tracking announcements
and requesting the required data is implementation-specific.

Block announcements, requests and responses are sent over the substream as
described in <<defn-block-announce-handshake>>.

[#defn-block-announce-handshake]
.<<defn-block-announce-handshake,Block Announce Handshake>>
====
The `BlockAnnounceHandshake` initializes a substream to a remote peer. Once
established, all `BlockAnounce` messages (<<defn-block-announce>>) created by
the node are sent to the `/dot/block-announces/1` substream.

The `BlockAnnounceHandshake` is a structure of the following
format:

[stem]
++++
BA_h = "Enc"_("SC")(R, N_B, h_B, h_G)
++++

where:

[stem]
++++
R = {(1,"The node is a full node"),(2,"The node is a light client"),(4,"The node is a validator"):}\
N_B = "Best block number according to the node"\
h_B = "Best block hash according to the node"\
h_G = "Genesis block hash according to the node"
++++
====

[#defn-block-announce]
.<<defn-block-announce,Block Announce>>
====
The `BlockAnnounce` message is sent to the specified substream and indicates to
remote peers that the node has either created or received a new block.

The message is a structure of the following format:

[stem]
++++
BA = "Enc"_("SC")("Head"(B),b)
++++

where:

[stem]
++++
"Head"(B) = "Header of the announced block"\
b = {(0,"Is not part of the best chain"),(1,"Is the best block according to the node"):}
++++
====

[#sect-msg-block-request]
==== Requesting Blocks
Block requests can be used to retrieve a range of blocks from peers. Those
messages are sent over the `/dot/sync/2` substream.

[#defn-msg-block-request]
.<<defn-msg-block-request,Block Request>>
====
The `BlockRequest` message is a Protobuf serialized structure of the following format:

[cols="2,1,4,1"]
|===
|Type |Id |Description |Value

|`uint32`
|1
|Bits of block data to request
|stem:[B_f]

|`oneof`
|
|Start from this block
|stem:[B_S]

|_Direction_
|5
|Sequence direction, interpreted as Id _0_ (ascending) if missing.
|

|`uint32`
|6
|Maximum amount (_optional_)
|stem:[B_m]
|===

where::
* stem:[B_f] indicates all the fields that should be included in the request.
its *big-endian* encoded bitmask that applies to all desired fields with bitwise
OR operations. For example, the stem:[B_f] value to request _Header_ and
_Justification_ is _0001 0001_ (17).
+
|===
|Field |Value

|Header
|0000 0001

|Body
|0000 0010

|Justification
|0001 0000
|===
* stem:[B_s] is a Protobuf structure indicating a varying data
type (enum) of the following values:
+
[cols="2,2,4"]
|===
|Type |Id |Description

|`bytes`
|2
|The block hash

|`bytes`
|3
|The block number
|===
* stem:[B_e] is either the block hash or block number depending
on the value of stem:[B_s]. an implementation-defined maximum is
used when unspecified.
* _Direction_ is a Protobuf structure indicating the sequence direction of the
requested blocks. The structure is a varying data type (enum) of the following
format:
+
[cols="1,4"]
|===
|Id |Description

|0
|Enumerate in ascending order (from child to parent)

|1
|Enumerate in descending order (from parent to canonical child)
|===
* stem:[B_m] is the number of blocks to be returned. An implementation defined
maximum is used when unspecified.
====

[#defn-msg-block-response]
.<<defn-msg-block-response,Block Response>>
====
The `BlockResponse` message is received after sending a `BlockRequest` message
to a peer. The message is a Protobuf serialized structure of the following
format:

[cols="3,1,5"]
|===
|Type |Id |Description

|Repeated _BlockData_
|1
|Block data for the requested sequence
|===

where _BlockData_ is a Protobuf structure containing the requested blocks. Do
note that the optional values are either present or absent depending on the
requested fields (bitmask value). The structure has the following format:

[cols="2,1,5,3"]
|===
|Type |Id |Description |Value

|`bytes`
|1
|Block header hash
|<<defn-block-header-hash>>

|`bytes`
|2
|Block header (optional)
|<<defn-block-header>>

|repeated `bytes`
|3
|Block body (optional)
|<<defn-block-body>>

|`bytes`
|4
|Block receipt (optional)
|

|`bytes`
|5
|Block message queue (optional)
|

|`bytes`
|6
|Justification (optional)
|<<defn-grandpa-justification>>

|`bool`
|7
|Indicates whether the justification is empty (i.e. should be ignored)
|
|===
====

[#sect-msg-state-request]
==== Requesting States

The Polkadot Host can request the state in form of a key/value list at a
specified block.

When receiving state entries from the state response messages
(<<defn-msg-state-response>>), the node can verify the entries with the entry
proof (id _1_ in _KeyValueStorage_) against the merkle root in the block header
(of the block specified in <<defn-msg-state-request>>). Once the state response
message claims that all entries have been sent (id _3_ in _KeyValueStorage_),
the node can use all collected entry proofs and validate it against the merkel
root to confirm that claim.

See the the synchronization section for more information (<<sect-network-sync>>).

[#defn-msg-state-request]
.<<defn-msg-state-request, State Request>>
====
A **state request** is sent to a peer to request the state at a specified block.
The message is a single 32-byte Blake2 hash which indicates the block from which
the sync should start.

Depending on what substream is used, he remote peer either sends back a state
response (<<defn-msg-state-response>>) on the `/dot/sync/2` substream or a warp
sync proof (<<defn-warp-sync-proof>>) on the `/dot/sync/warp`.
====

[#defn-msg-state-response]
.<<defn-msg-state-response, State Response>>
====
The **state response** is sent to the peer that initialized the state request
(<<defn-msg-state-request>>) and contains a list of key/value entries with an
associated proof. This response is sent continuously until all key/value pairs
have been submitted.

[cols="2,1,4"]
|===
|Type |Id |Description

|`repeated KeyValueStateEntry`
|1
|State entries

|`bytes`
|2
|State proof
|===

where _KeyValueStateEntry_ is of the following format:

[cols="2,1,4"]
|===
|Type |Id |Description

|`bytes`
|1
|Root of the entry, empty if top level

|`repeated StateEntry`
|2
|Collection of key/values

|`bool`
|3
|Equal 'true' if there are no more keys to return.
|===

and _StateEntry_:

[cols="2,1,4"]
|===
|Type |Id |Description

|`bytes`
|1
|The key of the entry

|`bytes`
|2
|The value of the entry
|===
====

[#sect-msg-warp-sync]
==== Warp Sync

The warp sync protocols allows nodes to retrieve blocks from remote peers where
authority set changes occurred. This can be used to speed up synchronization to
the latest state.

See the the synchronization section for more information (<<sect-network-sync>>).

[#defn-warp-sync-proof]
.<<defn-warp-sync-proof,Warp Sync Proof>>
====
The **warp sync proof** message, stem:[P], is sent to the peer that initialized
the state request (<<defn-msg-state-request>>) on the `/dot/sync/warp` substream
and contains accumulated proof of multiple authority set changes
(<<sect-consensus-message-digest>>). It's a datastructure of the following
format:

[stem]
++++
P = (f_x...f_y, c)
++++

stem:[f_x...f_y] is an array consisting of warp sync fragments of the following format:

[stem]
++++
f_x = (B_h, J^(r,"stage")(B))
++++

where stem:[B_h] is the last block header containing a digest item
(<<defn-digest>>) signaling an authority set change from which the next
authority set change can be fetched from. stem:[J^(r,"stage")(B)] is the GRANDPA
justification (<<defn-grandpa-justification>>) and stem:[c] is a boolean that
indicates whether the warp sync has been completed.
====

[#sect-msg-transactions]
==== Transactions

Transactions (<<sect-extrinsics>>) are sent directly to peers with which the
Polkadot Host has an open transaction substream (<<defn-transactions-message>>).
Polkadot Host implementers should implement a mechanism that only sends a
transaction once to each peer and avoids sending duplicates. Sending duplicate
transactions might result in undefined consequences such as being blocked for
bad behavior by peers.

The mechanism for managing transactions is further described in Section
<<sect-extrinsics>>.

[#defn-transactions-message]
.<<defn-transactions-message,Transaction Message>>
====
The *transactions message* is the structure of how the transactions are sent
over the network. It is represented by stem:[M_T] and is defined as follows:

[stem]
++++
M_T := "Enc"_("SC")(C_1,...,C_n)
++++

in which:

[stem]
++++
C_i := "Enc"_("SC")(E_i)
++++

Where each stem:[E_i] is a byte array and represents a separate
extrinsic. The Polkadot Host is agnostic about the content of an
extrinsic and treats it as a blob of data.

Transactions are sent over the `/dot/transactions/1` substream.
====

[#sect-msg-grandpa]
==== GRANDPA Messages

The exchange of GRANDPA messages is conducted on the substream. The process for
the creation and distributing these messages is described in <<sect-finality>>.
The underlying messages are specified in this section.

[#defn-gossip-message]
.<<defn-gossip-message,Grandpa Gossip Message>>
====
A *GRANDPA gossip message*, stem:[M], is a varying datatype
(<<defn-varrying-data-type>>) which identifies the message type that is cast by
a voter followed by the message itself.

[stem]
++++
M = {(0,"Vote message", V_m),(1,"Commit message", C_m),(2,"Neighbor message", N_m),(3,"Catch-up request message",R_m),(4,"Catch-up message",U_m):}
++++

where::
* stem:[V_m] is defined in <<defn-grandpa-vote-msg>>.
* stem:[C_m] is defined in <<defn-grandpa-commit-msg>>.
* stem:[N_m] is defined in <<defn-grandpa-neighbor-msg>>.
* stem:[R_m] is defined in <<defn-grandpa-catchup-request-msg>>.
* stem:[U_M] is defined in <<defn-grandpa-catchup-response-msg>>.
====

[#defn-grandpa-vote-msg]
.<<defn-grandpa-vote-msg,GRANDPA Vote Messages>>
====
A *GRANDPA vote message* by voter stem:[v], stem:[M_v^(r,"stage")], is gossip to
the network by voter stem:[v] with the following structure:

[stem]
++++
M_v^(r,"stage")(B) := "Enc"_("SC")(r,"id"_(bbb V),"SigMsg")\
"SigMsg" := ("msg","Sig"_(v_i)^(r,"stage"),v_("id"))\
"msg" := "Enc"_("SC")("stage",V_v^(r,"stage")(B))
++++

where::
* stem:[r] is an unsigned 64-bit integer indicating the Grandpa round number
(<<defn-voting-rounds>>).
* stem:["id"_(bbb V)] is an unsigned 64-bit integer indicating the authority Set Id (<<defn-authority-list>>).
* stem:["Sig"_(v_i)^(r,"stage")] is a 512-bit byte array containing the
signature of the authority (<<defn-sign-round-vote>>).
* stem:[v_(id)] is a 256-bit byte array containing the _ed25519_ public key of the authority.
* stem:["stage"] is a 8-bit integer of value _0_ if it's a pre-vote sub-round, _1_ if it's a pre-commit sub-round or _2_ if it's a primary proposal message.
* stem:[V_v^(r,"stage")(B)] is the GRANDPA vote for block stem:[B] (<<defn-voting-rounds>>).

This message is the sub-component of the GRANDPA gossip message
(<<defn-gossip-message>>) of type Id 0.
====

[#defn-grandpa-justifications-compact]
.<<defn-grandpa-justifications-compact,GRANDPA Compact Justification Format>>
====
The *GRANDPA compact justification format* is an optimized data structure to
store a collection of pre-commits and their signatures to be submitted as part
of a commit message. Instead of storing an array of justifications, it uses the
following format:

[stem]
++++
J_(v_(0,...n))^(r,"comp") := ({V_(v_0)^(r,pc),... V_(v_n)^(r,pc)},{("Sig"_(v_0)^(r,pc),v_("id"_0)), ... ("Sig"_(v_n)^(r,pc),v_("id"_n))})
++++

where::
* stem:[V_(v_i)^(r,pc)] is a 256-bit byte array containing the pre-commit vote of authority stem:[v_i] (<<defn-voting-rounds>>).
* stem:["Sig"_(v_i)^(r,pc)] is a 512-bit byte array containing the pre-commit
signature of authority stem:[v_i] (<<defn-sign-round-vote>>).
* stem:[v_("id"_n)] is a 256-bit byte array containing the public key of authority stem:[v_i].
====

[#defn-grandpa-commit-msg]
.<<defn-grandpa-commit-msg,GRANDPA Commit Message>>
====
A *GRANDPA commit message* for block stem:[B] in round stem:[r],
stem:[M_v^(r,"Fin")(B)], is a message broadcasted by voter stem:[v] to the
network indicating that voter stem:[v] has finalized block stem:[B] in round
stem:[r]. It has the following structure:

[stem]
++++
M_v^(r,"Fin")(B) := "Enc"_("SC")(r,"id"_(bbb V),V_v^r(B),J_(v_(0,...n))^(r,"comp"))
++++

where::
* stem:[r] is an unsigned 64-bit integer indicating the round number (<<defn-voting-rounds>>).
* stem:[id_(bbb V)] is the authority set Id (<<defn-authority-list>>).
* stem:[V_v^r(B)] is a 256-bit array containing the GRANDPA vote for block
stem:[B] (<<defn-vote>>).
* stem:[J_(v_(0,...n))^(r,"comp")] is the compacted GRANDPA justification
containing observed pre-commit of authorities stem:[v_0] to stem:[v_n]
(<<defn-grandpa-justifications-compact>>).

This message is the sub-component of the GRANDPA gossip message
(<<defn-gossip-message>>) of type Id _1_.
====

[#sect-grandpa-neighbor-msg]
===== GRANDPA Neighbor Messages

Neighbor messages are sent to all connected peers but they are not
repropagated on reception. A message should be send whenever the
messages values change and at least every 5 minutes. The sender should
take the recipients state into account and avoid sending messages to
peers that are using a different voter sets or are in a different round.
Messages received from a future voter set or round can be dropped and
ignored.

[#defn-grandpa-neighbor-msg]
.<<defn-grandpa-neighbor-msg, GRANDPA Neighbor Message>>
====
A *GRANDPA Neighbor Message* is defined as:

[stem]
++++
M^("neigh") := "Enc"_("SC")(v,r,"id"_(bbb V),H_i(B_("last")))
++++

where::
* stem:[v] is an unsigned 8-bit integer indicating the version of the neighbor message, currently _1_.
* stem:[r] is an unsigned 64-bit integer indicating the round number (<<defn-voting-rounds>>).
* stem:["id"_(bbb V)] is an unsigned 64-bit integer indicating the authority
Id (<<defn-authority-list>>).
* stem:[H_i(B_("last"))] is an unsigned 32-bit integer indicating the block number of the last finalized block stem:[B_("last")].

This message is the sub-component of the GRANDPA gossip message
(<<defn-gossip-message>>) of type Id _2_.
====

[#sect-grandpa-catchup-messages]
===== GRANDPA Catch-up Messages

Whenever a Polkadot node detects that it is lagging behind the finality
procedure, it needs to initiate a _catch-up_ procedure. GRANDPA Neighbor
messages (<<defn-grandpa-neighbor-msg>>) reveal the round number for the last
finalized GRANDPA round which the node’s peers have observed. This provides the
means to identify a discrepancy in the latest finalized round number observed
among the peers. If such a discrepancy is observed, the node needs to initiate
the catch-up procedure explained in <<sect-grandpa-catchup>>).

In particular, this procedure involves sending a _catch-up request_ and
processing _catch-up response_ messages.

[#defn-grandpa-catchup-request-msg]
.<<defn-grandpa-catchup-request-msg, Catch-Up Request Message>>
====
A *GRANDPA catch-up request message* for round stem:[r],
stem:[M_(i,v)^("Cat"-q)("id"_(bbb V),r)], is a message sent from node stem:[i]
to its voting peer node stem:[v] requesting the latest status of a GRANDPA round
stem:[r' >r] of the authority set stem:[bbb V_("id")] along with the
justification of the status and has the following structure:

[stem]
++++
M_(i,v)^(r,"Cat"-q) := "Enc"_("SC")(r,"id"_(bbb V))
++++

This message is the sub-component of the GRANDPA Gossip message
(<<defn-gossip-message>>) of type Id _3_.
====

[#defn-grandpa-catchup-response-msg]
.<<defn-grandpa-catchup-response-msg, Catch-Up Response Message>>
====
A *GRANDPA catch-up response message* for round stem:[r],
stem:[M_(v,i)^("Cat"-s)("id"_(bbb V),r)], is a message sent by a node stem:[v]
to node stem:[i] in response of a catch-up request
stem:[M_(v,i)^("Cat"-q)("id"_(bbb V),r')] in which stem:[r >= r'] is the
latest GRANDPA round which v has prove of its finalization and has the following
structure:

[stem]
++++
M_(v,i)^("Cat"-s) := "Enc"_("SC")("id"_(bbb V), r, J_(0,...n)^(r,"pv")(B), J_(0,...m)^(r,"pc")(B),H_h(B'),H_i(B'))
++++

Where stem:[B] is the highest block which stem:[v] believes to be finalized in
round stem:[r] (<<defn-voting-rounds>>). stem:[B'] is the highest ancestor of
all blocks voted on in the arrays of justifications stem:[J_(0,...n)^(r,"pv")(B)]
and stem:[J_(0,...m)^(r,"pc")(B)] (<<defn-grandpa-justification>>) with the
exception of the equivocatory votes.

This message is the sub-component of the GRANDPA Gossip message
(<<defn-gossip-message>>) of type Id _4_.
====

[#sect-msg-grandpa-beefy]
==== GRANDPA BEEFY
WARNING: The BEEFY protocol is currently in early development and subject to
change.

This section defines the messages required for the GRANDPA BEEFY protocol
(<<sect-grandpa-beefy>>). Those messages are sent over the `/paritytech/beefy/1`
substream.

[#defn-grandpa-beefy-commitment]
.<<defn-grandpa-beefy-commitment, Commitment>>
====
A *commitment*, stem:[C], contains the information extracted from the finalized
block at height stem:[H_i(B_("last"))] as specified in the message body and a
datastructure of the following format:

[stem]
++++
C = (R_h,H_i(B_("last")),"id"_(bbb V))
++++

where::
* stem:[R_h] is the MMR root of all the block header hashes leading up to the
latest, finalized block.
* stem:[H_i(B_("last"))] is the block number this commitment is for. Namely the
latest, finalized block.
* stem:["id"_(bbb V)] is the current authority set Id (<<defn-authority-set-id>>).
====

[#defn-msg-beefy-gossip]
.<<defn-msg-beefy-gossip, Vote Message>>
====
A *vote message*, stem:[M_v], is direct vote created by the Polkadot Host on every
BEEFY round and is gossiped to its peers. The message is a datastructure of the
following format:

[stem]
++++
M_v = "Enc"_("SC")(C,A_("id")^("bfy"),A_("sig"))
++++

where::
* stem:[C] is the BEEFY commitment (<<defn-grandpa-beefy-commitment>>).
* stem:[A_("id")^("bfy")] is the ECDSA public key of the Polkadot Host.
* stem:[A_("sig")] is the signature created with stem:[A_("id")^("bfy")] by
signing the statement stem:[R_h] in stem:[C].
====

[#defn-grandpa-beefy-signed-commitment]
.<<defn-grandpa-beefy-signed-commitment, Signed Commitment>>
====
A *signed commitment*, stem:[M_("sc")], is a datastructure of the following format:

[stem]
++++
M_("SC") = "Enc"_("SC")(C,S_n)\
S_n = (A_0^("sig"),... A_n^("sig"))
++++

where::
* stem:[C] is the BEEFY commitment (<<defn-grandpa-beefy-commitment>>).
* stem:[S_n] is an array where its exact size matches the number of validators
in the current authority set as specified by stem:["id"_(bbb V)]
(<<defn-authority-set-id>>) in stem:[C]. Individual items are of the type
_Option_ (<<defn-option-type>>) which can contain a signature of a validator
which signed the same statement (stem:[R_h] in stem:[C]) and is active in the
current authority set. It’s critical that the signatures are sorted based on
their corresponding public key entry in the authority set.
+
For example, the signature of the validator at index 3 in the authority set must
be placed at index _3_ in stem:[S_n]. If not signature is available for that
validator, then the _Option_ variant is _None_ inserted (<<defn-option-type>>).
This sorting allows clients to map public keys to their corresponding
signatures.
====

[#defn-grandpa-beefy-signed-commitment-witness]
.<<defn-grandpa-beefy-signed-commitment-witness, Signed Commitment Witness>>
====
A *signed commitment witness*, stem:[M_("SC")^w], is a light version of the signed
BEEFY commitment (<<defn-grandpa-beefy-signed-commitment>>). Instead of
containing the entire list of signatures, it only claims which validator signed
the statement.

The message is a datastructure of the following format:

[stem]
++++
M_("SC")^w = "Enc"_("SC")(C,V_(0,... n), R_("sig"))
++++

where::
* stem:[C] is the BEEFY commitment (<<defn-grandpa-beefy-commitment>>).
* stem:[V_(0,... n)] is an array where its exact size matches the number of
validators in the current authority set as specified by stem:["id"_(bbb V)] in
stem:[C]. Individual items are booleans which indicate whether the validator has
signed the statement (_true_) or not (_false_). It’s critical that the boolean
indicators are sorted based on their corresponding public key entry in the
authority set.
+
For example, the boolean indicator of the validator at index 3 in the authority
set must be placed at index _3_ in stem:[V_n]. This sorting allows clients to
map public keys to their corresponding boolean indicators.
* stem:[R_("sig")] is the MMR root of the signatures in the original signed
BEEFY commitment (<<defn-grandpa-beefy-signed-commitment>>).
====

[#sect-network-sync]
=== Synchronization

IMPORTANT: Synchronization is mostly application specific and the protocol does not
mandate how synchronization must be conducted. The network messages are
specified in <<sect-network-messages>>. This section makes some recommendations
how a synchronization mechanism can be constructed.

Many applications that interact with the Polkadot network to some extent must be
able to retrieve certain information about the network. Depending on the
utility, this includes validators that interact with Polkadot's consensus and
need access to the full state, either from the past or just the most up-to-date
state, or light clients that are only interest in the minimum information
required in order to verify some claims about the state of the network, such as
the balance of a specific account. To allow implemenations to quickly retrieve
the required information, different types of synchronization protocols are
available, respectivel Full, Fast and Warp sync suited for different needs.

==== Full Sync

The full sync protocols is the "default" protocol that's suited for many types
of implementations, such as archive nodes (nodes that store everything),
validators that participate in Polkadots consensus and light clients that only
verify claims about the state of the network. Full sync works by listening to
announced blocks (<<sect-msg-block-announce>>) and requesting the blocks from
the announcing peers, or just the block headers in case of light clients.

The full sync protocol usually downloads the entire chain, but no such
requirements must be met. If an implemenation only wants the latest, finalized
state, it can combine it with protocols such as fast sync (<<sect-fast-sync>>)
and/or warp sync (<<sect-warp-sync>>) to make synchronization as fast as
possible.

[#sect-fast-sync]
==== Fast Sync

Fast sync works by downloading the block header history and validating the
auhtority set changes (<<sect-authority-set>>) in order to arrive at a specific
(usually the most recent) header. After the desired header has been reached and
verified, the state can be downloaded and imported (<<sect-msg-state-request>>).
Once this process has been completed, the node can proceed with a full sync.

[#sect-warp-sync]
==== Warp Sync

Warp sync (<<sect-msg-warp-sync>>) only downloads the block headers where
authority set changes occurred, so called fragments (<<defn-warp-sync-proof>>),
and by verifying the GRANDPA justifications (<<defn-grandpa-justification>>).
This protocols allows nodes to arrive at the desired state much faster than fast
sync.
