== Light Client

Light clients are applications that fetch the required data that they need from
a Polkadot node with an associated proof to validate the data. This makes it
possible to interact with the Polkadot network without requiring to run a full
node or having to trust the remote peers. The light client messages make this
functionality possible.

=== Messages

All light client messages a protobuf messages.

==== Request

A message with all possible request messages.

[cols="2,1,5"]
|===
|Type |Id |Description

|`oneof` (`request`)
|
|The request type
|===

Where the `request` can be one of the following fields:

[cols="2,1,5"]
|===
|Type |Id |Description

|`RemoteCallRequest`
|1
|

|`RemoteReadRequest`
|2
|

|`RemoteHeaderRequest`
|3
|

|`RemoteReadChildRequest`
|4
|

|`RemoteChangesRequest`
|5
|
|===

==== Response

A message with all possible response messages.

[cols="2,1,5"]
|===
|Type |Id |Description

|`oneof` (`response`)
|
|The response type
|===

Where the `response` can be one of the following fields:

[cols="2,1,5"]
|===
|Type |Id |Description

|`RemoteCallResponse`
|1
|

|`RemoteReadResponse`
|2
|

|`RemoteHeaderResponse`
|3
|

|`RemoteChangesResponse`
|4
|
|===

==== Remote Call Request

Remote call request.

[cols="2,1,5"]
|===
|Type |Id |Description

|`bytes`
|2
|Block at which to perform call

|`string`
|3
|Method name

|`bytes`
|4
|Call data
|===

