[#sect-warp-sync]
=== Synchronization

NOTE: Synchronization is mostly application specific and the protocol does not
mandate how synchronization must be conducted. The network messages are
specified in <<sect-network-messages>>. This section makes some recommendations
how a synchronization mechanism can be constructed.

Many applications that interact with the Polkadot network to some extent must be
able to retrieve certain information about the network. Depending on the
utility, this includes validators that interact with Polkadot's consensus and
need access to the full state, either from the past or just the most up-to-date
state, or light clients that are only interest in the minimum information
required in order to verify some claims about the state of the network, such as
the balance of a specific account. To allow implemenations to quickly retrieve
the required information, different types of synchronization protocols are
available, respectivel Full, Fast and Warp sync suited for different needs.

==== Full Sync

The full sync protocols is the "default" protocol that's suited for many types
of implementations, such as archive nodes (nodes that store everything),
validators that participate in Polkadots consensus and light clients that only
verify claims about the state of the network. Full sync works by listening to
announced blocks (<<sect-msg-block-announce>>) and requesting the blocks from
the announcing peers , or just the block headers in case of light clients.

The full sync protocol usually downloads the entire chain, but no such
requirements must be met. If an implemenation only wants the latest, finalized
state, it can combine it with protocols such as fast sync (<<sect-fast-sync>>)
and/or warp sync (<<sect-warp-sync>>) to make synchronization as fast as
possible.

[#sect-fast-sync]
==== Fast Sync

Fast sync works by downloading the block header history and validating the
auhtority set changes (<<sect-authority-set>>) in order to arrive at a specific
(usually the most recent) header. After the desired header has been reached and
verified, the state can be downloaded and imported (<<defn-sequence-import>>).
Once this process has been completed, the node can proceed with a full sync.

[#defn-sequence-import]
.<<defn-sequence-import,Key/Value Sequence Import>>
====
When receive state entries from the state response message
(<<defn-wrap-sync-response>>), the node must verify the entries with the entry
proof (id _1_ in _KeyValueStorage_) against the merkle root in the block header.
Once the state response message claims that all entries have been sent (id _3_
in _KeyValueStorage_), the node must use all collected entry proofs and validate
it against the merkel root.
====

[#sect-warp-sync]
==== Warp Sync

Warp sync only downloads the block headers where authority set changes occured
and by verifying the GRANDPA justifications (<<defn-grandpa-justification>>).
This protocols allows nodes to arrive at the desired state much faster than fast
sync.

TODO...