@startuml

(*) --> "Parachain Collator <math>C_rho</math> Generates <math>B</math> and <math>PoV_B</math>"
    --> "<math>C_rho</math> sends <math>PoV_B</math> to <math>rho</math>'s validator <math>V_rho</math>"
    --> "<math>V_rho</math> runs <math>rho</math>'s runtime on PoV"
    if "<math>PoV_B</math> is valid" then
    -->[true] if  "<math>V_rho</math> have seen the CandidateReceipt for <math>PoV_B</math>" then
    -->[true] Sign CandidateReceipt
    -->[Ending process] (*)

    else
    --> [False] "Gerenate CandiateReceipt"
    -->[Ending process] (*)

    endif
    else
    -->[false] "Broadcast message of invalidity for <math>PoV_B</math>"
    end if

  -->[Ending process] (*)

@enduml
