=== Binary Enconding

[#defn-byte-sequence]
.<<defn-byte-sequence, Sequence of Bytes>>
====
By a *sequences of bytes* or a *byte array*, stem:[b], of length
stem:[n], we refer to

[stem]
++++
b := (b_0, b_1, ..., b_{n - 1}) " such that " 0 <= b_i <= 255
++++

We define stem:[bbb B_n] to be the
*set of all byte arrays of length stem:[n]*. Furthermore, we
define:

[stem]
++++
bbb B := uuu_(i=0)^infty bbb B_i
++++

We represent the concatenation of byte arrays
stem:[a :=(a_0, ..., a_n)] and
stem:[b :=(b_0, ..., b_m)] by:

[stem]
++++
a |\| b :=(a_0, ..., a_n, b_0, ..., b_m)
++++
====

[#defn-bit-rep]
.<<defn-bit-rep, Bitwise Representation>>
====
For a given byte stem:[0 <= b <= 255] the *bitwise representation* in bits stem:[b_i in {0, 1}] is defined as:

[stem]
++++
b := b_7 ... b_0
++++

where

[stem]
++++
b = 2^7 b_7 + 2^6 b_6 + ... + 2^0 b_0
++++
====

[#defn-little-endian]
.<<defn-little-endian, Little Endian>>
====
By the *little-endian* representation of a non-negative integer, stem:[I],
represented as

[stem]
++++
I = (B_n ... B_0)_256
++++

in base 256, we refer to a byte array
stem:[B = (b_0, b_1, ..., b_n)] such that

[stem]
++++
b_i :=B_i
++++

Accordingly, we define the function stem:[sf "Enc"_(sf "LE")]:

[stem]
++++
sf "Enc"_(sf "LE"): bbb Z^+ -> bbb B; (B_n ... B_0)_256 |-> (B_{0,} B_1, ... , B_n)
++++
====

[#defn-uint32]
.<<defn-uint32, UINT32>>
====
By *UINT32* we refer to a non-negative integer stored in a byte array of
length stem:[4] using little-endian encoding format.
====

[#sect-scale-codec]
=== SCALE Codec
The Polkadot Host uses _Simple Concatenated Aggregate Little-Endian” (SCALE)
codec_ to encode byte arrays as well as other data structures. SCALE provides a
canonical encoding to produce consistent hash values across their
implementation, including the Merkle hash proof for the State Storage.

.Decoding
====
stem:["Dec"_("SC")(d)] refers to the decoding of a blob of data. Since the SCALE codec is not
self-describing, it’s up to the decoder to validate whether the blob of data can
be deserialized into the given type or data structure.
====

.Byte Array
[#defn-scale-byte-array]
====
The *SCALE codec* for *Byte array*, stem:[A], such that:

[stem]
++++
A := (b_1, b_2, ... b_n)
++++

such that stem:[n < 2^(536)] is a byte array referred to stem:["Enc"_("SC")(A)]
and defined as:

[stem]
++++
"Enc"_("SC")(A) := "Enc"_("SC")^("Len")(abs(A)) "||" A
++++

where stem:["Enc"_("SC")^("Len")] is defined in <<defn-sc-len-encoding>>.
====

.Tuple
[#defn-scale-tuple]
====
The *SCALE codec* for *Tuple*, stem:[T], such that:

[stem]
++++
T := (A_1,... A_n)
++++

Where stem:[A_i]’s are values of *different types*, is defined as:

[stem]
++++
"Enc"_("SC")(T) := "Enc"_("SC")(A_1) "||" "Enc"_("SC")(A_2) "||" ... "||" "Enc"_("SC")(A_n)
++++
====

In case of a tuple (or a structure), the knowledge of the shape of data is not
encoded even though it is necessary for decoding. The decoder needs to derive
that information from the context where the encoding/decoding is happening.

.Varying Data Type
[#defn-varrying-data-type]
====
We define a *varying data* type to be an ordered set of data types.

[stem]
++++
cc T = {T_1, ..., T_n}
++++

A value stem:[A] of varying date type is a pair stem:[(A_("Type"),A_("Value"))]
where stem:[A_("Type") = T_i] for some stem:[T_i in cc T] and
stem:[A_("Value")] is its value of type stem:[T_i], which can be empty. We
define stem:["idx"(T_i) = i - 1], unless it is explicitly defined as another
value in the definition of a particular varying data type.
====

In particular, we define two specific varying data which are frequently used in
various part of Polkadot Protocol:

.Option Type
[#defn-option-type]
====
The *Option* type is a varying data type of stem:[{"None",T_2}] which indicates if
data of stem:[T_2] type is available (referred to as _some_ state) or not
(referred to as _empty_, _none_ or _null_ state). The presence of type _none_,
indicated by stem:["idx"(T_("None")) = 0], implies that the data corresponding
to stem:[T_2] type is not available and contains no additional data. Where as
the presence of type stem:[T_2] indicated by stem:["idx"(T_2) = 1] implies that
the data is available.
====

.Result Type
[#defn-result-type]
====
The *Result* type is a varying data type of stem:[{T_1, T_2}] which is used to
indicate if a certain operation or function was executed successfully (referred
to as "ok" state) or not (referred to as "error" state). stem:[T_1] implies
success, stem:[T_2] implies failure. Both types can either contain additional
data or are defined as empty type otherwise.
====

.Encoding of Varying Data Type
[#defn-scale-variable-type]
====
The SCALE codec for value stem:[A = (A_("Type"), A_("Value"))] of varying data
type stem:[cc T = {T_i, ... T_n}], formally referred to as
stem:["Enc" ("SC")(A)} is defined as follows:

[stem]
++++
"Enc"_("SC")(A) := "Enc"_("SC")("idx"(A_("Type")) "||" "Enc"_("SC")(A_("Value")))
++++

Where stem:["idx"] is encoded in a fixed length integer determining the type of
stem:[A]. In particular, for the optional type defined in
<<defn-varrying-data-type>>, we have:

[stem]
++++
"Enc"_("SC")("None", phi) := 0_(bbb B_1)
++++
====

The SCALE codec does not encode the correspondence between the value of stem:[idx]
defined in <<defn-scale-variable-type>> and the data type it represents; the
decoder needs prior knowledge of such correspondence to decode the data.

.Sequence
[#defn-scale-list]
====
The *SCALE codec* for *sequence* stem:[S] such that:

[stem]
++++
S := A_1, ... A_n
++++

where stem:[A_i]’s are values of *the same type* (and the decoder is unable to
infer value of stem:[n] from the context) is defined as:

[stem]
++++
"Enc"_("SC")(S) := "Enc"_("SC")^("Len")(abs(S)) "||" "Enc"_("SC")(A_2) "||" ... "||" "Enc"_("SC")(A_n)
++++

where stem:["Enc"_("SC")^("Len")] is defined in <<defn-sc-len-encoding>>.
====

.Dictionary
====
SCALE codec for *dictionary* or *hashtable* D with key-value pairs stem:[(k_i,
v_i)]s such that:

[stem]
++++
D := {(k_1, v_1), ... (k_n, v_n)}
++++

is defined the SCALE codec of stem:[D] as a sequence of key value pairs (as
tuples):

[stem]
++++
"Enc"_("SC")(D) := "Enc"_("SC")^("Size")(abs(D)) "||" "Enc"_("SC")(k_1, v_1) "||"..."||" "Enc"_("SC")(k_n, v_n)
++++

where stem:["Enc"_("SC")^("Size")] is encoded the same way as
stem:["Enc"_("SC")^("Len")] but argument stem:["Size"] refers to the number of
key-value pairs rather than the length.
====

.Boolean
====
The *SCALE codec* for *boolean value* stem:[b] defined as a byte as follows:

[stem]
++++
"Enc"_("SC"): {"False", "True"} -> bbb B_1\
b -> {(0, b="False"),(1, b="True"):}
++++
====

.Fixed Length
[#defn-scale-fixed-length]
====
The SCALE codec, stem:["Enc"_("SC")], for other types such as fixed length
integers not defined here otherwise, is equal to little endian encoding of those
values defined in <<defn-little-endian>>.
====

.Empty
[#defn-scale-empty]
====
The SCALE codec, stem:["Enc"_("SC")], for an empty type is defined to a byte
array of zero length and depicted as stem:[phi].
====

==== Length and Compact Encoding

SCALE Length encoding is used to encode integer numbers of variying sizes prominently in an encoding length of arrays:

.Length Encoding
[#defn-sc-len-encoding]
====
*SCALE Length encoding*, stem:["Enc"_("SC")^("Len")], also known as a _compact encoding_, of a non-negative number stem:[n] is defined as follows:

[stem]
++++
"Enc"_("SC")^("Len"): bbb N -> bbb B\
n -> b := {(l_1, 0 <= n < 2^6),(i_1 i_2, 2^6 <= n < 2^14),(j_1 j_2 j_3, 2^14 <= n < 2^30),(k_1 k_2 ... k_m, 2^30<=n):}
++++

in where the least significant bits of the first byte of byte array b
are defined as follows:

[stem]
++++
l_1^1 l_1^0 = 00\
i_1^1 i_1^0 = 01\
j_1^1 j_1^0 = 10\
k_1^1 k_1^0 = 11
++++

and the rest of the bits of stem:[b] store the value of stem:[n] in
little-endian format in base-2 as follows:

[stem]
++++
n := {
	(l_1^7 ... l_1^3 l_1^2, n < 2^6),
	(i_2^7 ... i_2^0 i_1^7 .. i_1^2, 2^6 <= n < 2^14),
	(j_4^7 ... j_4^0 j_3^7 ... j_1^7 ... j_1^2, 2^14 <= n < 2^30),
	(k_2 + k_3 2^8 + k_4 2^(2 xx 8)+...+k_m2^((m-2)8),2^30 <= n)
	:}
++++

such that:

[stem]
++++
k_1^7 ... k_1^3 k_1^2 := m-4
++++
====

=== Hex Encoding

Practically, it is more convenient and efficient to store and process data which
is stored in a byte array. On the other hand, the trie keys are broken into
4-bits nibbles. Accordingly, we need a method to encode sequences of 4-bits
nibbles into byte arrays canonically. To this aim, we define
hex encoding function asciimath:["Enc" ("HE")("PK")] as follows:

.Hex Encoding
[#defn-hex-encoding]
====
Suppose that stem:["PK" = (k_1, ... k_n)] is a sequence of nibbles, then:

[stem]
++++
"Enc"_("HE")("PK") := {("Nibbles"_4,->, bbb B),("PK" = (k_1, ... k_n),->,{((16k_1+k_2,...,16k_(2i-1)+k_(2i)),n=2i),((k_1,16k_2+k_3,...,16k_(2i)+k_(2i+1)),n = 2i+1):}):}
++++
====
