Like any transaction-based transition system, Polkadot’s state is
changed by executing an ordered set of instructions. These instructions
are known as _extrinsics_. In Polkadot, the execution logic of the
state-transition function is encapsulated in a Runtime as defined in
Definition <<defn-state-machine>>. For easy
upgradability this Runtime is presented as a Wasm blob. Nonetheless, the
Polkadot Host needs to be in constant interaction with the Runtime. The
detail of such interaction is further described in Section
link_sect-entries-into-runtime[3.1].

In Section link_sect-extrinsics[3.2], we specify the procedure of the
process where the extrinsics are submitted, pre-processed and validated
by Runtime and queued to be applied to the current state.

To make state replication feasible, Polkadot journals and batches series
of its extrinsics together into a structure known as a _block_, before
propagating them to other nodes, similar to most other prominent
distributed ledger systems. The specification of the Polkadot block as
well as the process of verifying its validity are both explained in
Section link_sect-state-replication[3.3].

[#sect-entries-into-runtime]
=== Interacting with the Runtime

The Runtime as defined in Definition link_defn-runtime[[defn-runtime]]
is the code implementing the logic of the chain. This code is decoupled
from the Polkadot Host to make the the logic of the chain easily
upgradable without the need to upgrade the Polkadot Host itself. The
general procedure to interact with the Runtime is described in Algorithm
link_algo-runtime-interaction[[algo-runtime-interaction]].

[#algo-runtime-interaction]
==== Algorithm: Interact-With-Runtime
****
Algorithm: stem:["Interact-With-Runtime"(F, H_b(B),(A_1,...,A_n))]

where

* stem:[F] is the runtime entry call.
* stem:[H_b(B)] is the block hash indicating the state at the end of stem:[B].
* stem:[A_1,...,A_n] are arguments to be passed to the runtime entry.

which executes the following steps:

. stem:[S_b larr "Set-State-At"(H_b(B))]
. stem:[A larr "Enc"_(SC)(A_1,...,A_n)]
. stem:["Call-Runtime-Entry"(R_B,RE_B,F,A,A_(len))]

****

In this section, we describe the details upon which the Polkadot Host is
interacting with the Runtime. In particular, Set-State-At and Call-Runtime-Entry
procedures called in Algorithm
link_algo-runtime-interaction[[algo-runtime-interaction]] are explained in
Notation link_nota-call-into-runtime[[nota-call-into-runtime]] and Definition
link_defn-set-state-at[[defn-set-state-at]] respectively. stem:[R_B] is the
Runtime code loaded from stem:[S_B], as described in Notation
link_nota-runtime-code-at-state[[nota-runtime-code-at-state]], and
stem:[RE_B] is the Polkadot Host API, as described in
Notation link_nota-host-api-at-state[[nota-host-api-at-state]].

[#sect-loading-runtime-code]
==== Loading the Runtime Code

The Polkadot Host expects to receive the code for the Runtime of the
chain as a compiled WebAssembly (Wasm) Blob. The current runtime is
stored in the state database under the key represented as a byte array:

[stem]
++++
b := "3A,63,6F,64,65"
++++

which is the ASCII byte representation of the string "`:code`"" (see Section
link_sect-genesis-block[11]). As a result of storing the Runtime as
part of the state, the Runtime code itself becomes state sensitive and
calls to Runtime can change the Runtime code itself. Therefore the
Polkadot Host needs to always make sure to provide the Runtime
corresponding to the state in which the entry has been called.
Accordingly, we define stem:[R_B] (<<notat-runtime-code-at-state>>).

The initial Runtime code of the chain is provided as part of the genesis
state (see Section link_sect-genesis-block[11]) and subsequent calls to
the Runtime have the ability to, in turn, upgrade the Runtime by
replacing this Wasm blob with the help of the storage API (see Section
link_sect-host-api[12]).

[#notat-runtime-code-at-state]
===== Notation: Runtime Code at State
****
By stem:[R_B], we refer to the Runtime code stored in the state storage at the
end of the execution of block stem:[B].
****

[#sect-code-executor]
==== Code Executor

The Polkadot Host executes the calls of Runtime entries inside a Wasm
Virtual Machine (VM), which in turn provides the Runtime with access to
the Polkadot Host API. This part of the Polkadot Host is referred to as
the _*Executor*._

Definition link_nota-call-into-runtime[[nota-call-into-runtime]]
introduces the notation for calling the runtime entry which is used
whenever an algorithm of the Polkadot Host needs to access the runtime.

It is acceptable behavior that the Runtime panics during execution of a
function in order to indicate an error. The Polkadot Host must be able
to catch that panic and recover from it.

In this section, we specify the general setup for an Executor that calls
into the Runtime. In Section link_sect-runtime-entries[13] we specify
the parameters and return values for each Runtime entry separately.

[#notat-call-into-runtime]
===== Notation: Call Runtime Entry
****
By

[stem]
++++
"Call-Runtime-Entry"(R,RE,"Runtime-Entry",A,A_len)
++++

we refer to the task using the executor to invoke the while passing an
stem:[A_1, ..., A_n] argument to it and using the encoding described in Section
link_sect-runtime-send-args-to-runtime-enteries[3.1.2.2].
****

[#sect-memory-management]
===== Memory Management

The Polkadot Host is responsible for managing the WASM heap memory
starting at the exported symbol as a part of implementing the allocator
Host API (see Section link_sect-ext-allocator[12.7]) and the same
allocator should be used for any other heap allocation to be used by the
Polkadot Runtime.

The size of the provided WASM memory should be based on the value of the
storage key (an unsigned 64-bit integer), where each page has the size
of 64KB. This memory shoule be made available to the Polkadot Runtime
for import under the symbol name `memory`.

[#sect-runtime-send-args-to-runtime-enteries]
===== Sending Data to a Runtime Entry

In general, all data exchanged between the Polkadot Host and the Runtime
is encoded using SCALE codec described in Section
link_sect-scale-codec[10.1]. Therefore all runtime entries have the
following identical Wasm function signatures:

++++
(func $runtime_entry (param $data i32) (param $len i32) (result i64))
++++

In each invocation of a Runtime entry, the argument(s) which are
supposed to be sent to the entry, need to be SCALE encoded into a byte
array stem:[B] (see Definition link_sect-scale-codec[10.1]) and
copied into a section of Wasm shared memory managed by the shared
allocator described in Section link_sect-memory-management[3.1.2.1].

When the Wasm method , corresponding to the entry, is invoked, two
integers are passed as arguments. The first argument is set to the
memory adress of the byte array stem:[B] in Wasm memory. The
second argument sets the length of the encoded data stored in
stem:[B].

[#sect-runtime-return-value]
===== Receiving Data from a Runtime Entry

The value which is returned from the invocation is an integer,
representing two consecutive integers in which the least significant one
indicates the pointer to the offset of the result returned by the entry
encoded in SCALE codec in the memory buffer. The most significant one
provides the size of the blob.

[#sect-handling-runtime-state-update]
===== Handling Runtimes update to the State

In order for the Runtime to carry on various tasks, it manipulates the
current state by means of executing calls to various Polkadot Host APIs
(see Appendix link_sect-host-api[12]). It is the duty of Host APIs to
determine the context in which these changes should persist. For
example, if Polkdot Host needs to validate a transaction using entry
(see Section link_sect-rte-validate-transaction[13.3.4.1]), it needs to
sandbox the changes to the state just for that Runtime call and prevent
the global state of the system from being influence by the call to such
a Runtime entry. This includes reverting the state of function calls
which return errors or panic.

As a rule of thumb, any state changes resulting from Runtime enteries
are not persistant with the exception of state changes resulting from
calling (see Section link_sect-rte-core-execute-block[13.3.1.2]) while
Polkadot Host is importing a block (see Section
link_sect-block-validation[3.3.2]).

For more information on managing multiple variant of state see Section
link_sect-managing-multiple-states[3.3.3].
