Like any transaction-based transition system, Polkadot’s state is
changed by executing an ordered set of instructions. These instructions
are known as _extrinsics_. In Polkadot, the execution logic of the
state-transition function is encapsulated in a Runtime as defined in
Definition link:#defn-state-machine[[defn-state-machine]]. For easy
upgradability this Runtime is presented as a Wasm blob. Nonetheless, the
Polkadot Host needs to be in constant interaction with the Runtime. The
detail of such interaction is further described in Section
link:#sect-entries-into-runtime[3.1].

In Section link:#sect-extrinsics[3.2], we specify the procedure of the
process where the extrinsics are submitted, pre-processed and validated
by Runtime and queued to be applied to the current state.

To make state replication feasible, Polkadot journals and batches series
of its extrinsics together into a structure known as a _block_, before
propagating them to other nodes, similar to most other prominent
distributed ledger systems. The specification of the Polkadot block as
well as the process of verifying its validity are both explained in
Section link:#sect-state-replication[3.3].

[#sect-entries-into-runtime]
=== Interacting with the Runtime

