[#sect-runtime-txqueue-module]
=== Module TaggedTransactionQueue

IMPORTANT: This section describes *Version 2* of this API. Please check `Core_version` (<<defn-rt-core-version>>) to ensure compatibility.

All calls in this module require `Core_initialize_block` (<<sect-rte-core-initialize-block>>) to be called beforehand.

[#sect-rte-validate-transaction]
==== `TaggedTransactionQueue_validate_transaction`

This entry is invoked against extrinsics submitted through a transaction network
message (<<sect-msg-transactions>>) or by an offchain worker through the Host API
(<<sect-ext-offchain-submit-transaction>>).

It indicates if the submitted blob represents a valid extrinsics, the
order in which it should be applied and if it should be gossiped to
other peers. Furthermore this function gets called internally when
executing blocks with the runtime function as described in <<sect-rte-core-execute-block>>.

Arguments::
* The source of the transaction as defined in <<defn-transaction-source>>.
* A byte array that contains the transaction.
* The hash of the parent of the block that the transaction is included in.
+
.TransactionSource
[#defn-transaction-source]
====
*TransactionSource* is an enum describing the source of a transaction and can
have one of the following values:

.The _TransactionSource_ enum
[cols="<1,<2,<7",options="header",]
|===
|Id |Name |Description
|0 | _InBlock_ |Transaction is already included in a block.
|1 | _Local_ |Transaction is coming from a local source, e.g. off-chain worker.
|2 | _External_ |Transaction has been received externally, e.g. over the network.
|===
====

Return::
* This function returns a _Result_ as defined in <<defn-result-type>> which contains
the type _ValidTransaction_  as defined in <<defn-valid-transaction>> on success
and the type _TransactionValidityError_ as defined in
<<defn-rte-transaction-validity-error>> on failure.
+
.ValidTransaction
[#defn-valid-transaction]
====
*ValidTransaction* is a tuple that contains information concerning a valid transaction.

.The tuple provided by in the case the transaction is judged to be valid.
[cols="<1,<7,<2",options="header",]
|===
|*Name* |*Description* |*Type*

|_Priority_
|Determines the ordering of two transactions that have all their dependencies
(required tags) are satisfied.
|Unsigned 64bit integer

|_Requires_
|List of tags specifying extrinsics which should be applied before the current
exrinsics can be applied.
|Array containing inner arrays

|_Provides_
|Informs Runtime  of the extrinsics depending on the tags in the list that can be
applied after current extrinsics are being applied. Describes the minimum number
of blocks for the validity to be correct
|Array containing inner arrays

|_Longevity_
|After this period, the transaction should be removed from the pool or revalidated.
|Unsigned 64-bit integer

|_Propagate_
|A flag indicating if the transaction should be gossiped to other peers.
|Boolean
|===
====

NOTE: If _Propagate_ is set to `false` the transaction will still be considered for inclusion in blocks that are authored on the current node, but should not be gossiped to other peers.

NOTE: If this function gets called by the Polkadot Host in order to validate a transaction received from peers, the Polkadot Host disregards and rewinds state changes resulting in such a call.
