= Availability & Validity
:description: Availability & Validity
:doctype: book
:toc:
:stem:
:sectnums: all

[preface]
== Introduction

As clarified in Chapter 1, Polkadot serves as a replicated shared-state machine designed to resolve scalability issues and interoperability among blockchains. The validators of Polkadot execute transactions and participate in the consensus of Polkadots primary chain, the so called relay chain. Parachains are independent networks that maintain their own state and are connected to the relay chain. Those parachains can take advantage of the relay chain consensus mechanism, including sending and receiving messages to and from other parachains. Parachain nodes that send parachain blocks, known as candidates, to the validators in order to be inlcuded in relay chain are referred to as collators.

The Polkadot relay chain validators are responsible for guaranteeing the validity of both relay chain and parachain blocks. Additionally, the validators are required to keep enough parachain blocks that should be included in the relay chain available in their local storage in order to make those retrievable by peers, who lack the information, to reliably confirm the issued validity statements about parachain blocks. The Availability & Validity (AnV) protocol consists of multiple steps for successfully upholding those responsibilities.

Parachain blocks themselves are produced by collators as described in Section 7.3, whereas the relay chain validators only verify their validity (and later, their availability). It is possible that the collators of a parachain  produces multiple parachain block candidates for a child of a specific block. Subsequently, they send the block candadiates to the the relay chain validators who are assigned to the specific parachain. The assignment is determined by the Runtime as described in Section 7.4. Those validators are then required to check the validity of submitted candidates as described in Section 7.5, then issue and collect statements about the validity of candidates to other validators as described in Section 7.4.1. This process is known as candidate backing. Once a candidate meets a specified criteria for inclusion, the selected relay chain block author then choses any of the backed candidate for each parachain and includes those into the relay chain block as described in Section 7.4.2.

Every relay chain validator must fetch the proposed candidates and issue votes on whether they have the candidate saved in their local storage, so called availability votes as described in Section 7.6.1, then also collect the votes sent by other validators and include them in the relay chain state, as described in Section 7.4.2. This process ensures that only relay chain blocks get finalized where each candidate is available on enough nodes of validators.

Parachain candidates contained in non-finalized (Section ?) relay chain blocks must then be retrieved by a secondary set of relay chain validators, unrelated from the candidate backing process, who are randomly assigned to determine the validity of specific parachains based on a VRF lottery and are then required to vote on the validity of those candidates as described in Section 7.7. This process is known as approval voting. If a validator does not have the candidate data, it must recover the candidate data as described in Section 7.6.2.

== Preliminaries

[#defn-collator]
.Collator
****
A collator is a parachain node that sends parachain blocks, known as candidates as defined in Definition 7.2, to the relay chain validators. The relay chain validators are not concerned how the collator works or how it creates candidates.
****

[#defn-candidate]
.Candidate
****
A candidate is a submitted parachain block as defined in Definition 7.3 to the relay chain validators. A parachain block stops being referred to as a candidate as soon it has been finalized.
****

[#defn-para-block]
.Parachain Block
****
A parachain block or a Proof-of-Validity block (PoV block) contains the necessary data to for parachain specific state transition logic. Relay chain validators are not concerned with the inner structure of the block and treat it as a byte array.
****

[#defn-head-data]
.Head Data
****
The head data is contains information about a parachain block as defined in Definition 7.3. The head data is returned by executing the parachain Runtime and relay chain validators are not concerned with its inner structure and treat it as a byte arrays.
****

[#defn-para-id]
.Parachain Id
****
The Parachain Id is a unique, unsigned 32-bit integer which serves as an identifier of a parachain, assigned by the Runtime.
****

[#defn-availability-core]
.Availability Core
****
Availability cores are slots used to process parachains. The Runtime assigns each parachain to a availability core and validators can fetch information about the cores, such as parachain block candidates, by calling the appropriate Runtime API as described in Section 7.8.3. Validators are not concerned with the internal workings from the Runtimes perspective.
****

[#defn-validator-groups]
.Validator Groups
****
Validator groups indicate which validators are responsible for creating backable candidates for certain parachains, as described in Section 7.4, and are assigned by the Runtime. Validators are not concerned with the internal workings from the Runtimes perspective. Collators can use this information for submitting blocks.
****

[#defn-upward-message]
.Upward Message
****
An upward message is an opaque byte array sent from a parachain to a relay chain.
****

[#defn-downward-message]
.Downward Message
****
Definition 2. A downward message is an opaque byte array received by the parachain from the relay chain.
****

[#defn-outbound-hrmp-message]
.Outbound HRMP message
****
Definition 3. An outbound HRMP message (Horizontal Relay-routed Message Passing) is sent from the perspective of a sender of a parachain to an other parachain by passing it through the relay chain. It's a datastructure of the following format:

[stem]
++++
(I,M)
++++

where I is the recipient Id as defined in Definition 7.5 and M is an upward message as defined in Definition 7.8. 
****

[#defn-inbound-hrmp-message]
.Inbound HRMP message
****
An inbound HRMP message (Horizontal Relay-routed Message Passing) is seen from the perspective of a recipient parachain sent from an other parachain by passing it through the relay chain. It's a datastructure of the following format:

[stem]
++++
(N,M)
++++

where N is the relay chain block number at which the message was passed down to the recipient parachain and M is a downward message as defined in Definition 7.9.
****

[#sect-collations]
== Collations

Collations are proposed <<defn-candidate, candidates>> to the Polkadot relay chain validators. The Polkodat network protocol is agnostic on what candidate productionis mechanism each parachain uses and does not specify or mandate any of such production methods (e.g. BABE-GRANDPA, Aura, etc). Furthermore, the relay chain validator host implementation itself does not directly interpret or process teh internal transactions of the candidate, but rather rely on the parachain Runtime to validate the candidate, as described in Section 7.5. Collators, which are parachain nodes which produce candidate proposals and send them to the relay chain validator, must prepare pieces of data specified in Definition 7.12 in order to correctly comply with the requirements of the parachain protocol.

[#defn-collation]
.Collation
****
A collation is a datastructure which contains the proposed parachain candidate, including an optional validation parachain Runtime update and upward messages. The collation datastructure, C, is a datastructure of the following format:

[stem]
++++
C = (M,H,R,h,P,p,w)\
M = (u_n,…u_m)\
H = (z_n,…z_m)
++++

where

• stem:[M] is an array of upward messages, u, interpreted by the relay chain itself, as defined in Definition 7.8.
• stem:[H] is an array of outbound horizontal messages, z, interpreted by other parachains, as defined in Definition 7.10
• stem:[R] is an Option type as defined in Definition ? which can contain a parachain Runtime update. The new Runtime code is an array of bytes.
• stem:[h] is the head data as defined in Definition 7.4 produced as a result of execution of the parachain specific logic.
• stem:[P] is the PoV block as defined in Definition ?.
• stem:[p] is an unsigned 32-bit integer indicating the number of downward messages processed as defined in Definition 7.9.
• stem:[w] is an unsigned 32-bit integer indicating the mark up to which all inbound HRMP messages have been processed by the parachain.
****

[#sect-candidate-backing]
== Candidate Backing

The Polkadot validator receives an arbitrary number of parachain candidates with associated proofs from untrusted collators. The validator must verify and select a specific quantity of the proposed candidates and issue those as backable candidates to its peers. A candidate is considered backable when at least 2/3 of all assigned validators have issued a Valid statement about that candidate, as described in Section 7.4.1. Validators can retrieve information about assignments via the Runtime APIs 7.8.2 respectively 7.8.3.

[#sect-statements]
=== Statements

The assigned validator checks the validity of the proposed parachains blocks as described in Section 7.5 and issues Valid statements as defined in Definition 7.13 to its peers if the verification succeeded. Broadcasting failed verification as Valid statements is a slashable offense. The validator must only issue one Seconded statement, based on an arbitrary metric, which implies an explicit vote for a candidate to be included in the relay chain.

WARNING: TODO: reference disputes

This protocol attempts to produce as many backable candidates as possible, but does not attempt to determine a final candidate for inclusion. Once a parachain candidate has been seconded by at least one other validator and enough Valid statements have been issued about that candidate to meet the 2/3 quorum, the candidate is ready to be inlcuded in the relay chain as described in Section 7.4.2.

The validator issues validity statements votes in form of a validator protocol message as defined in Definition 7.35.

[#defn-statement]
.Statement
****
A statement, stem:[S], is a datastructure of the following format:

[stem]
++++
S = (d,A_i,A_s)\
d = {(1,->,C_r),(2,->,C_h):}
++++

where

•  stem:[d] is a varying datatype where 1 indicates that the validator “seconds” a candidate, meaning that the candidate should be included in the relay chain, followed by the committed candidate receipt, stem:[C_r], as defined in Definition 7.17. 2 indicates that the validator has deemed the candidate valid, followed by the candidate hash.
•  stem:[C_h] is the candidate hash.
•  stem:[A_i] is the validator index in the authority set that signed this statement.
•  stem:[A_s] is the signature of the validator.
****

[#defn-bitfield-array]
.Bitfield Array
****
A bitfield array contains single-bit values which indidate whether a candidate is available. The number of items is equal of to the number of availability cores as defined in Definition 7.6 and each bit represents a vote on the corresponding core in the given order. Respectively, if the single bit equals 1, then the Polkadot validator claims that the availability core is occupied, there exists a committed candidate receipt as defined in Definition 7.17 and that the validator has a stored chunk of the parachain block as defined in Definition 7.6.2.
****

== Inclusion

The Polkadot validator includes the backed candidates as inherent data as defined in Definition 7.15 into a block as described in Section ?. The relay chain block author decides on whatever metric which candidate should be selected for inclusion, as long as that candidate is valid and meets the validity quorum of 2/3+ as described in Section 7.4.1. The candidate approval process as described in Section 7.7 ensures that only relay chain blocks are finalized where each candidate for each availability core meets the requirement of 2/3+ availability votes.

[#defn-parachain-inherent-data]
.Parachain Inherent Data
****
The parachain inherent data contains backed candidates and is included when authoring a relay chain block. The datastructure, stem:[I], is of the following format:

[stem]
++++
I = (A,T,D,P_h)\
T = (C_0,…C_n)\
D = (*d_n,…d_m)\
C = (R,V,i)\
V = (a_n,…a_m)\
a = {(1,->,s),(2,->,s):}\
A = (L_n,…L_m)\
L = (b,v_i,s)
++++

where

•  stem:[A] is an array of signed bitfields by validators claiming the candidate is available (or not). The array must be sorted by validator index corresponding to the authority set as described in Section ?.
•  stem:[T] is an array of backed candidates for inclusing in the current block.
•  stem:[D] is an array of disputes.
•  stem:[P_h] is the parachain parent head data as defined in Definition 7.4.
•  stem:[d] is a dispute statement as described in Section 7.7.3.
•  stem:[R] is a committed candidate receipt as defined in Definition 7.17.
•  stem:[V] is an array of validity votes themselves, expressed as signatures.
•  stem:[i] is a bitfield of indices of the validators within the validator group as defined in Definition 7.7.
•  stem:[a] is either an implicit or explicit attestation of the validity of a parachain candidate, where 1 implies an implicit vote (in correspondence of a Seconded statement) and 2 implies an explicit attestation (in correspondence of a Valid statement). Both variants are followed by the signature of the validator.
•  stem:[s] is the signature of the validator.
•  stem:[b] the availability bitfield as described in Section 7.6.1.
•  stem:[v_i] is the validator index of the authority set as defined in Definition ?.
****

[#defn-candidate-receipt]
.Candidate Receipt
****
A candidate receipt, stem:[R], contains information about the candidate and a proof of the results of its execution. It's a datastructure of the following format:

[stem]
++++
R = (D,C_h)
++++

where stem:[D] is the candidate descriptor as defined in Definition 7.18 and stem:[C_h] is the hash of candidate commitments as defined in Definition 7.19.
****

.Committed Candidate Receipt
****
The committed candidate receipt, stem:[R], contains information about the candidate and the the result of its execution that is included in the relay chain. This type is similiar to the candidate receipt as defined in Definition 7.16, but actually contains the execution results rather than just a hash of it. It's a datastructure of the following format:

[stem]
++++
R = (D,C)
++++

where stem:[D] is the candidate descriptor as defined in Definition 7.18 and stem:[C] is the candidate commitments as defined in Definition 7.19.
****

.Candidate Descriptor
****
The candidate descriptor, stem:[D], is a unique descriptor of a candidate receipt. It's a datastructure of the following format:

[stem]
++++
D = (p,H,C_i,V,B,r,s,p_h,R_h)
++++

where

•  stem:[p] is the parachain Id as defined in Definition 7.5.
•  stem:[H] is the hash of the relay chain block the candidate is executed in the context of.
•  stem:[C_i] is the collators public key.
•  stem:[V] is the hash of the persisted validation data as defined in Definition 7.33.
•  stem:[B] is the hash of the PoV block.
•  stem:[r] is the root of the block's erasure encoding Merkle tree. [clarify]
•  stem:[s] the collator signature of the concatenated components p, H, R_h and B.
•  stem:[p_h] is the hash of the parachain head data as described in Definition 7.4 of this candidate.
•  stem:[R_h] is the hash of the parachain Runtime.
****

.Candidate Commitments
****
The candidate commitments, stem:[C], is the result of the execution and validation of a parachain (or parathread) candidate whose produced values must be committed to the relay chain. Those values are retrieved from the validation result as defined in Definition 7.21. A candidate commitment is a datastructure of the following format:

[stem]
++++
C =(M_u,M_h,R,h,p,w)
++++

where:

•  stem:[M_u] is an array of upward messages sent by the parachain. Each individual message, m, is an array of bytes.
•  stem:[M_h] is an array of outbound horizontal messages sent by the parachain. Each individual messages, t, is a datastructure as defined in Definition 7.10.
•  stem:[R] is an Option value as described in Section ? that can contain a new parachain Runtime in case of an update.
•  stem:[h] is the parachain head data as described in Definition 7.4.
•  stem:[p] is a unsigned 32-bit intiger indicating the number of downward messages that were processed by the parachain. It is expected that the parachain processes the messages from frist to last.
•  stem:[w] is a unsigned 32-bit integer indicating the watermark which specifies the relay chain block number up to which all inbound horizontal messages have been processed.
****

== Candidate Validation

Received candidates submitted by collators and must have its validity verified by the assigned Polkadot validators. For each candidate to be valid, the validator must successfully verify the following conditions in the following order:

. The candidate does not exceed any parameters in the persisted validation data as defined in Definition 7.33.
. The signature of the collator is valid.
. Validate the candidate by executing the parachain Runtime as defined in Definition 7.5.1.

If all steps are valid, the Polkadot validator must create the necessary candidate commitments as defined in Definition 7.19 and submit the appropriate statement for each candidate as described in Section 7.4.1.

=== Parachain Runtime

Parachain Runtimes are stored in the relay chain state, and can either be fetched by the parachain Id or the Runtime hash via the relay chain Runtime API as described in Section 7.8.7 and 7.8.8 respectively. The retrieved parachain Runtime might need to be decompressed based on the magic identifier as described in Section 7.5.2.

In order to validate a parachain block, the Polkadot validator must prepare the validation parameters as defined in Definition 7.20, then use its local Wasm execution environment as described in Section ? to execute the validate_block parachain Runtime API by passing on the validation parameters as an argument. The parachain Runtime function returns the validation result as defined in Definition 7.21.

.Validation Parameters
****
The validation parameters structure, stem:[P], is required to validate a candidate against a parachain Runtime. It's a datastructure of the following format:

[stem]
++++
P = (h,b,B_i,S_r)
++++

where

•  stem:[h] is the parachain head data as defined in Definition 7.4.
•  stem:[b] is the block body as defined in Definition 7.3.
•  stem:[B_i] is the latest relay chain block number.
•  stem:[S_r] is the relay chain block storage root as defined in Definition ?.
****

.Validation Result
****
The validation result is returned by the validate_block parachain Runtime API after attempting to validate a parachain block. Those results are then used in candidate commitments as defined in Definition ?., which then will be inserted into the relay chain via the parachain inherent data as described in Definition 7.15. The validation result, stem:[V], is a datastructure of the following format:

[stem]
++++
V   = (h,R,M_u,M_h,p_,w)\
M_u = (m_0,…m_n)\
M_h = (t_0,…t_n)
++++

where

•  stem:[h] is the parachain head data as defined in Definition 7.4.
•  stem:[R] is an Option value as described in Section ? that can contain a new parachain Runtime in case of an update.
•  stem:[M_u] is an array of upward messages sent by the parachain. Each individual message, m, is an array of bytes.
•  stem:[M_h] is an array of outbound horizontal messages sent by the parachain. Each individual message, t, is a datastructure as defined in Definition 7.10.
•  stem:[p] is a unsigned 32-bit integer indicating the number of downward messages that were processed by the parachain. It is expected that the parachain processes the messages from first to last.
•  stem:[w] is a unsigned 32-bit integer indicating the watermark which specifies the relay chain block number up to which all inbound horizontal messages have been processed.
****

=== Runtime Compression

WARNING: TODO

