[#sect-hash-functions]
=== Hash Functions

[#sect-blake2]
=== BLAKE2

BLAKE2 is a collection of cryptographic hash functions known for their high
speed. Their design closely resembles BLAKE which has been a finalist in the
SHA-3 competition.

Polkadot is using the Blake2b variant which is optimized for 64-bit platforms.
Unless otherwise specified, the Blake2b hash function with a 256-bit output is
used whenever Blake2b is invoked in this document. The detailed specification
and sample implementations of all variants of Blake2 hash functions can be found
in RFC 7693 .

[#sect-randomness]
=== Randomness

NOTE: TBH

[#sect-vrf]
=== VRF

NOTE: TBH

[#sect-cryptographic-keys]
=== Cryptographic Keys

Various types of keys are used in Polkadot to prove the identity of the actors
involved in the Polkadot Protocols. To improve the security of the users, each
key type has its own unique function and must be treated differently, as
described by this Section.

[#defn-account-key]
==== Account Key
****
*Account key stem:[(sk^a,pk^a)]* is a key pair of type of either of the schemes in the following
table:

TODO: References

.List of the public key scheme which can be used for an account key
|===
|Key Scheme| Description

|sr25519
|Schnorr signature on Ristretto compressed ed25519 points as implemented in TODO

|ed25519
|The standard ed25519 signature complying with TODO

|secp256k1
|Only for outgoing transfer transactions.
|===

An account key can be used to sign transactions among other accounts and
balance-related functions.

There are two prominent subcategories of account keys namely "stash keys" and
"controller keys", each being used for a different function. Keys defined in
Definitions link_defn-account-key[[defn-account-key]],
link_defn-stash-key[[defn-stash-key]] and
link_defn-controller-key[[defn-controller-key]] are created and managed by the
user independent of the Polkadot implementation. The user notifies the network
about the used keys by submitting a transaction, as defined in
link_sect-creating-controller-key[9.5.2] and link_sect-certifying-keys[9.5.5]
respectively.
****

[#defn-stash-key]
==== Stash Key
****
The *Stash key* is a type of account key that holds funds bonded for staking
(described in Section link_sect-staking-funds[9.5.1]) to a particular
controller key (defined in Definition
link_defn-controller-key[[defn-controller-key]]). As a result, one may actively
participate with a stash key keeping the stash key offline in a secure location.
It can also be used to designate a Proxy account to vote in governance
proposals, as described in link_sect-creating-controller-key[9.5.2]. The Stash
key holds the majority of the users’ funds and should neither be shared with
anyone, saved on an online device, nor used to submit extrinsics.
****

[#defn-controller-key]
==== Controller Key
****
The *Controller key* is a type of account key that acts on behalf of the Stash
account. It signs transactions that make decisions regarding the nomination and
the validation of the other keys. It is a key that will be in direct control of
a user and should mostly be kept offline, used to submit manual extrinsics. It
sets preferences like payout account and commission, as described in
link_sect-controller-settings[9.5.4]. If used for a validator, it certifies the
session keys, as described in link_sect-certifying-keys[9.5.5]. It only needs
the required funds to pay transaction fees [TODO: key needing fund needs to be
defined].
****

[#defn-session-key]
==== Session Keys
****
*Session keys* are short-lived keys that are used to authenticate validator
operations. Session keys are generated by the Polkadot Host and should be
changed regularly due to security reasons. Nonetheless, no validity period is
enforced by the Polkadot protocol on session keys. Various types of keys used by
the Polkadot Host are presented in Table link_tabl-session-keys[9.1]_:_

.List of key schemes which are used for session keys depending on the protocol
|===
|Protocol |Key scheme

|GRANDPA |ED25519
|BABE |SR25519
|I’m Online |SR25519
|Parachain |SR25519
|===

Session keys must be accessible by certain Polkadot Host APIs defined in
Appendix link_sect-host-api[12]. Session keys are _not_ meant to control the
majority of the users’ funds and should only be used for their intended purpose.
[TODO: key managing fund need to be defined]
****

[#sect-staking-funds]
==== Holding and staking funds

NOTE: TBH

[#sect-creating-controller-key]
==== Creating a Controller key

NOTE: TBH

[#sect-designating-proxy]
==== Designating a proxy for voting

NOTE: TBH

[#sect-controller-settings]
==== Controller settings

NOTE: TBH

[#sect-certifying-keys]
==== Certifying keys

Due to security considerations and Runtime upgrades, the session keys are
supposed to  be changed regularly. As such, the new session keys need to be
certified by a controller key before putting them in use. The controller only
needs to create a certificate by signing a session public key and broadcasting
this certificate via an extrinsic. [TODO: spec the detail of the data structure
of the certificate etc.]
