[#sect-scale-codec]
=== SCALE Codec

The Polkadot Host uses _Simple Concatenated Aggregate Little-Endian” (SCALE)
codec_ to encode byte arrays as well as other data structures. SCALE provides a
canonical encoding to produce consistent hash values across their
implementation, including the Merkle hash proof for the State Storage.

[#defn-scale-byte-array]
==== Byte Array
The *SCALE codec* for *Byte array*, stem:[A], such that:

[stem]
++++
A := (b_1, b_2, ... b_n)
++++

such that stem:[n < 2^(536)] is a byte array referred to stem:["Enc"_("SC")(A)]
and defined as:

[stem]
++++
"Enc"_("SC")(A) := "Enc"_("SC")^("Len")(||A||)||A
++++

where stem:["Enc"_("SC")^("Len)] is defined in Definition
link:#defn-sc-len-encoding[[defn-sc-len-encoding]].

[#defn-scale-tuple]
==== Tuple
The *SCALE codec* for *Tuple*, stem:[$T$], such that:

[stem]
++++
T := (A_1,... A_n)
++++

Where stem:[A_i]’s are values of *different types*, is defined as:

[stem]
++++
"Enc"_("SC")(T) := "Enc"_("SC")(A_1)||"Enc"_("SC")(A_2)||...||"Enc"_("SC")(A_n)
++++

In case of a tuple (or a structure), the knowledge of the shape of data is not
encoded even though it is necessary for decoding. The decoder needs to derive
that information from the context where the encoding/decoding is happening.
