name: Publish website

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    if:  github.repository_owner == 'w3f'
    name: build and deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v2
        with:
          node-version: "18.x"
      - name: Initialize submodules
        run: git submodule update --remote
      - name: Publish
        run: |
          git config --global user.email "grants-deployer@users.noreply.github.com"
          git config --global user.name "grants-deployer"
          echo "machine github.com login grants-deployer password ${{ secrets.ACCESS_KEY }}" > ~/.netrc
          cd website && npm i && npm run build && GIT_USER=grants-deployer PUBLISHING=true npm run deploy
