name: deb-spec-runtime

on:
  push:
    branches:
    - main
  pull_request:
    paths:
    - '.github/workflows/runtime-spec.deb.yml'
    - 'runtime-spec/**'
  release:
    types: [published]

jobs:
  build:
    name: deb-build-spec-runtime
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y latexmk texlive texlive-luatex texlive-science texlive-latex-extra
    - name: Build runtime specification
      run: make -C runtime-spec
    - name: Upload runtime specification
      uses: actions/upload-artifact@v2
      with:
        name: polkadot-runtime-spec.pdf
        path: runtime-spec/polkadot-runtime-spec.pdf
    - name: Release runtime specification
      uses: actions/upload-release-asset@v1
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: runtime-spec/polkadot-runtime-spec.pdf
        asset_name: polkadot-runtime-spec_${{ github.event.release.tag_name }}.pdf
        asset_content_type: application/pdf
      if: github.event_name == 'release'

  diff:
    name: deb-diff-spec-runtime
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 2
      if: github.event_name == 'push'
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
      if: github.event_name == 'pull_request' || github.event_name == 'release'
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y latexmk texlive texlive-luatex texlive-science texlive-latex-extra latexdiff
    - name: Determine comparison target
      run: echo "REV=HEAD~1" >> $GITHUB_ENV
      if: github.event_name == 'push'
    - name: Determine comparison target
      run: echo "REV=origin/${GITHUB_BASE_REF}" >> $GITHUB_ENV
      if: github.event_name == 'pull_request'
    - name: Determine comparison target
      run: echo "REV=$(git describe --tags --abbrev=0 HEAD~1)" >> $GITHUB_ENV
      if: github.event_name == 'release'
    - name: Compare runtime specification
      run: make -C runtime-spec diff
    - name: Upload runtime specification diff
      uses: actions/upload-artifact@v2
      with:
        name: polkadot-runtime-spec.diff.pdf
        path: runtime-spec/polkadot-runtime-spec.diff.pdf
    - name: Release runtime specification diff
      uses: actions/upload-release-asset@v1
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: runtime-spec/polkadot-runtime-spec.diff.pdf
        asset_name: polkadot-runtime-spec_${{ github.event.release.tag_name }}.diff_${{ env.REV }}.pdf
        asset_content_type: application/pdf
      if: github.event_name == 'release'
