name: nix-spec-runtime

on:
  push:
    branches:
    - main
  pull_request:
    paths:
    - '.github/workflows/runtime-spec.nix.yml'
    - 'runtime-spec/**'

jobs:
  build:
    name: nix-build-spec-runtime
    runs-on: ubuntu-20.04
    steps:
    - uses: cachix/install-nix-action@v15
    - uses: cachix/cachix-action@v10
      with:
        name: polkadot-spec
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - name: Build runtime specification
      run: nix build github:${{ github.repository }}/${{ github.sha }}#runtime-spec
