name: Check runtime specification (Nix)

on:
  push:
    branches:
    - main
  pull_request:
    paths:
    - '.github/workflows/runtime-spec.nix.yml'
    - 'runtime-spec/**'

jobs:
  nix-build:
    name: Compile runtime specification
    runs-on: ubuntu-20.04
    container: nixpkgs/nix-flakes:nixos-20.09
    steps:
    - uses: cachix/cachix-action@v10
      with:
        name: polkadot-spec
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - name: Build runtime specification
      run: nix build github:${{ github.repository }}/${{ github.sha }}#polkadot-runtime-spec

